// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: BuyCustomFeature.proto

package BuyCustomFeature

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "moneyx.golang.framework/integration/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CustomFeatureCheckCustomerActivationIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	ManagerId     string                 `protobuf:"bytes,3,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,5,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomFeatureCheckCustomerActivationIntegratedCommand) Reset() {
	*x = CustomFeatureCheckCustomerActivationIntegratedCommand{}
	mi := &file_BuyCustomFeature_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomFeatureCheckCustomerActivationIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomFeatureCheckCustomerActivationIntegratedCommand) ProtoMessage() {}

func (x *CustomFeatureCheckCustomerActivationIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyCustomFeature_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomFeatureCheckCustomerActivationIntegratedCommand.ProtoReflect.Descriptor instead.
func (*CustomFeatureCheckCustomerActivationIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyCustomFeature_proto_rawDescGZIP(), []int{0}
}

func (x *CustomFeatureCheckCustomerActivationIntegratedCommand) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CustomFeatureCheckCustomerActivationIntegratedCommand) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CustomFeatureCheckCustomerActivationIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *CustomFeatureCheckCustomerActivationIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CustomFeatureCheckCustomerActivationIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CustomFeatureCheckCustomerActivationResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsEnable      bool                   `protobuf:"varint,1,opt,name=IsEnable,proto3" json:"IsEnable,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=CustomerId,proto3" json:"CustomerId,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,3,opt,name=Failure,proto3" json:"Failure,omitempty"`
	ManagerId     string                 `protobuf:"bytes,4,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomFeatureCheckCustomerActivationResponseIntegratedCommand) Reset() {
	*x = CustomFeatureCheckCustomerActivationResponseIntegratedCommand{}
	mi := &file_BuyCustomFeature_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomFeatureCheckCustomerActivationResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomFeatureCheckCustomerActivationResponseIntegratedCommand) ProtoMessage() {}

func (x *CustomFeatureCheckCustomerActivationResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyCustomFeature_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomFeatureCheckCustomerActivationResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*CustomFeatureCheckCustomerActivationResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyCustomFeature_proto_rawDescGZIP(), []int{1}
}

func (x *CustomFeatureCheckCustomerActivationResponseIntegratedCommand) GetIsEnable() bool {
	if x != nil {
		return x.IsEnable
	}
	return false
}

func (x *CustomFeatureCheckCustomerActivationResponseIntegratedCommand) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CustomFeatureCheckCustomerActivationResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *CustomFeatureCheckCustomerActivationResponseIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *CustomFeatureCheckCustomerActivationResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CustomFeatureCheckCustomerActivationResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CustomFeatureCreditReductionIntegratedCommand struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber         string                 `protobuf:"bytes,1,opt,name=AccountNumber,proto3" json:"AccountNumber,omitempty"`
	PackageName           string                 `protobuf:"bytes,2,opt,name=PackageName,proto3" json:"PackageName,omitempty"`
	TransactionId         string                 `protobuf:"bytes,3,opt,name=TransactionId,proto3" json:"TransactionId,omitempty"`
	ExchangerProfit       *common.Money          `protobuf:"bytes,4,opt,name=ExchangerProfit,proto3" json:"ExchangerProfit,omitempty"`
	ExchangerPrice        *common.Money          `protobuf:"bytes,5,opt,name=ExchangerPrice,proto3" json:"ExchangerPrice,omitempty"`
	OperatorName          string                 `protobuf:"bytes,6,opt,name=OperatorName,proto3" json:"OperatorName,omitempty"`
	MobileNumber          string                 `protobuf:"bytes,7,opt,name=MobileNumber,proto3" json:"MobileNumber,omitempty"`
	ManagerId             string                 `protobuf:"bytes,8,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId         string                 `protobuf:"bytes,9,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id                    string                 `protobuf:"bytes,10,opt,name=Id,proto3" json:"Id,omitempty"`
	PackageConvertedPrice *common.Money          `protobuf:"bytes,11,opt,name=PackageConvertedPrice,proto3" json:"PackageConvertedPrice,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CustomFeatureCreditReductionIntegratedCommand) Reset() {
	*x = CustomFeatureCreditReductionIntegratedCommand{}
	mi := &file_BuyCustomFeature_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomFeatureCreditReductionIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomFeatureCreditReductionIntegratedCommand) ProtoMessage() {}

func (x *CustomFeatureCreditReductionIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyCustomFeature_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomFeatureCreditReductionIntegratedCommand.ProtoReflect.Descriptor instead.
func (*CustomFeatureCreditReductionIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyCustomFeature_proto_rawDescGZIP(), []int{2}
}

func (x *CustomFeatureCreditReductionIntegratedCommand) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *CustomFeatureCreditReductionIntegratedCommand) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *CustomFeatureCreditReductionIntegratedCommand) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CustomFeatureCreditReductionIntegratedCommand) GetExchangerProfit() *common.Money {
	if x != nil {
		return x.ExchangerProfit
	}
	return nil
}

func (x *CustomFeatureCreditReductionIntegratedCommand) GetExchangerPrice() *common.Money {
	if x != nil {
		return x.ExchangerPrice
	}
	return nil
}

func (x *CustomFeatureCreditReductionIntegratedCommand) GetOperatorName() string {
	if x != nil {
		return x.OperatorName
	}
	return ""
}

func (x *CustomFeatureCreditReductionIntegratedCommand) GetMobileNumber() string {
	if x != nil {
		return x.MobileNumber
	}
	return ""
}

func (x *CustomFeatureCreditReductionIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *CustomFeatureCreditReductionIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CustomFeatureCreditReductionIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CustomFeatureCreditReductionIntegratedCommand) GetPackageConvertedPrice() *common.Money {
	if x != nil {
		return x.PackageConvertedPrice
	}
	return nil
}

type CommitOrRollbackCustomFeatureCreditReductionIntegratedCommand struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	IsCommitted   bool                               `protobuf:"varint,1,opt,name=IsCommitted,proto3" json:"IsCommitted,omitempty"`
	Context       *common.CreditReductionMetaContext `protobuf:"bytes,2,opt,name=Context,proto3" json:"Context,omitempty"`
	CorrelationId string                             `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                             `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOrRollbackCustomFeatureCreditReductionIntegratedCommand) Reset() {
	*x = CommitOrRollbackCustomFeatureCreditReductionIntegratedCommand{}
	mi := &file_BuyCustomFeature_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOrRollbackCustomFeatureCreditReductionIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOrRollbackCustomFeatureCreditReductionIntegratedCommand) ProtoMessage() {}

func (x *CommitOrRollbackCustomFeatureCreditReductionIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyCustomFeature_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOrRollbackCustomFeatureCreditReductionIntegratedCommand.ProtoReflect.Descriptor instead.
func (*CommitOrRollbackCustomFeatureCreditReductionIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyCustomFeature_proto_rawDescGZIP(), []int{3}
}

func (x *CommitOrRollbackCustomFeatureCreditReductionIntegratedCommand) GetIsCommitted() bool {
	if x != nil {
		return x.IsCommitted
	}
	return false
}

func (x *CommitOrRollbackCustomFeatureCreditReductionIntegratedCommand) GetContext() *common.CreditReductionMetaContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CommitOrRollbackCustomFeatureCreditReductionIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CommitOrRollbackCustomFeatureCreditReductionIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CustomFeatureCreditReductionResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDone        bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=Failure,proto3" json:"Failure,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomFeatureCreditReductionResponseIntegratedCommand) Reset() {
	*x = CustomFeatureCreditReductionResponseIntegratedCommand{}
	mi := &file_BuyCustomFeature_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomFeatureCreditReductionResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomFeatureCreditReductionResponseIntegratedCommand) ProtoMessage() {}

func (x *CustomFeatureCreditReductionResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyCustomFeature_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomFeatureCreditReductionResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*CustomFeatureCreditReductionResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyCustomFeature_proto_rawDescGZIP(), []int{4}
}

func (x *CustomFeatureCreditReductionResponseIntegratedCommand) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *CustomFeatureCreditReductionResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *CustomFeatureCreditReductionResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CustomFeatureCreditReductionResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddAccountringCustomFeatureDocumentsIntegratedCommand struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	BuyChargeInfo *common.BuyChargeAccountingInfo `protobuf:"bytes,1,opt,name=BuyChargeInfo,proto3" json:"BuyChargeInfo,omitempty"`
	CustomerId    string                          `protobuf:"bytes,2,opt,name=CustomerId,proto3" json:"CustomerId,omitempty"`
	ManagerId     string                          `protobuf:"bytes,3,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId string                          `protobuf:"bytes,4,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                          `protobuf:"bytes,5,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAccountringCustomFeatureDocumentsIntegratedCommand) Reset() {
	*x = AddAccountringCustomFeatureDocumentsIntegratedCommand{}
	mi := &file_BuyCustomFeature_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAccountringCustomFeatureDocumentsIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAccountringCustomFeatureDocumentsIntegratedCommand) ProtoMessage() {}

func (x *AddAccountringCustomFeatureDocumentsIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyCustomFeature_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAccountringCustomFeatureDocumentsIntegratedCommand.ProtoReflect.Descriptor instead.
func (*AddAccountringCustomFeatureDocumentsIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyCustomFeature_proto_rawDescGZIP(), []int{5}
}

func (x *AddAccountringCustomFeatureDocumentsIntegratedCommand) GetBuyChargeInfo() *common.BuyChargeAccountingInfo {
	if x != nil {
		return x.BuyChargeInfo
	}
	return nil
}

func (x *AddAccountringCustomFeatureDocumentsIntegratedCommand) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *AddAccountringCustomFeatureDocumentsIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *AddAccountringCustomFeatureDocumentsIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AddAccountringCustomFeatureDocumentsIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddAccountingCustomFeatureDocumentsResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDone        bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=Failure,proto3" json:"Failure,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAccountingCustomFeatureDocumentsResponseIntegratedCommand) Reset() {
	*x = AddAccountingCustomFeatureDocumentsResponseIntegratedCommand{}
	mi := &file_BuyCustomFeature_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAccountingCustomFeatureDocumentsResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAccountingCustomFeatureDocumentsResponseIntegratedCommand) ProtoMessage() {}

func (x *AddAccountingCustomFeatureDocumentsResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyCustomFeature_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAccountingCustomFeatureDocumentsResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*AddAccountingCustomFeatureDocumentsResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyCustomFeature_proto_rawDescGZIP(), []int{6}
}

func (x *AddAccountingCustomFeatureDocumentsResponseIntegratedCommand) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *AddAccountingCustomFeatureDocumentsResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *AddAccountingCustomFeatureDocumentsResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AddAccountingCustomFeatureDocumentsResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CommitOrRollbackAddedCustomFeatureAccountingDocumentIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCommitted   bool                   `protobuf:"varint,1,opt,name=IsCommitted,proto3" json:"IsCommitted,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOrRollbackAddedCustomFeatureAccountingDocumentIntegratedCommand) Reset() {
	*x = CommitOrRollbackAddedCustomFeatureAccountingDocumentIntegratedCommand{}
	mi := &file_BuyCustomFeature_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOrRollbackAddedCustomFeatureAccountingDocumentIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOrRollbackAddedCustomFeatureAccountingDocumentIntegratedCommand) ProtoMessage() {}

func (x *CommitOrRollbackAddedCustomFeatureAccountingDocumentIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyCustomFeature_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOrRollbackAddedCustomFeatureAccountingDocumentIntegratedCommand.ProtoReflect.Descriptor instead.
func (*CommitOrRollbackAddedCustomFeatureAccountingDocumentIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyCustomFeature_proto_rawDescGZIP(), []int{7}
}

func (x *CommitOrRollbackAddedCustomFeatureAccountingDocumentIntegratedCommand) GetIsCommitted() bool {
	if x != nil {
		return x.IsCommitted
	}
	return false
}

func (x *CommitOrRollbackAddedCustomFeatureAccountingDocumentIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CommitOrRollbackAddedCustomFeatureAccountingDocumentIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SubmitOrCancelCustomFeatureIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDone        bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	ManagerId     string                 `protobuf:"bytes,3,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,5,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOrCancelCustomFeatureIntegratedCommand) Reset() {
	*x = SubmitOrCancelCustomFeatureIntegratedCommand{}
	mi := &file_BuyCustomFeature_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrCancelCustomFeatureIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrCancelCustomFeatureIntegratedCommand) ProtoMessage() {}

func (x *SubmitOrCancelCustomFeatureIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyCustomFeature_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrCancelCustomFeatureIntegratedCommand.ProtoReflect.Descriptor instead.
func (*SubmitOrCancelCustomFeatureIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyCustomFeature_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitOrCancelCustomFeatureIntegratedCommand) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *SubmitOrCancelCustomFeatureIntegratedCommand) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubmitOrCancelCustomFeatureIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *SubmitOrCancelCustomFeatureIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *SubmitOrCancelCustomFeatureIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_BuyCustomFeature_proto protoreflect.FileDescriptor

const file_BuyCustomFeature_proto_rawDesc = "" +
	"\n" +
	"\x16BuyCustomFeature.proto\x12\x10BuyCustomFeature\x1a\fCommon.proto\"\xc5\x01\n" +
	"5CustomFeatureCheckCustomerActivationIntegratedCommand\x12\x1a\n" +
	"\bUserName\x18\x01 \x01(\tR\bUserName\x12\x1c\n" +
	"\tAccountId\x18\x02 \x01(\tR\tAccountId\x12\x1c\n" +
	"\tManagerId\x18\x03 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x04 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x05 \x01(\tR\x02Id\"\xfa\x01\n" +
	"=CustomFeatureCheckCustomerActivationResponseIntegratedCommand\x12\x1a\n" +
	"\bIsEnable\x18\x01 \x01(\bR\bIsEnable\x12\x1e\n" +
	"\n" +
	"CustomerId\x18\x02 \x01(\tR\n" +
	"CustomerId\x12)\n" +
	"\aFailure\x18\x03 \x01(\v2\x0f.Common.FailureR\aFailure\x12\x1c\n" +
	"\tManagerId\x18\x04 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x05 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x06 \x01(\tR\x02Id\"\xee\x03\n" +
	"-CustomFeatureCreditReductionIntegratedCommand\x12$\n" +
	"\rAccountNumber\x18\x01 \x01(\tR\rAccountNumber\x12 \n" +
	"\vPackageName\x18\x02 \x01(\tR\vPackageName\x12$\n" +
	"\rTransactionId\x18\x03 \x01(\tR\rTransactionId\x127\n" +
	"\x0fExchangerProfit\x18\x04 \x01(\v2\r.Common.MoneyR\x0fExchangerProfit\x125\n" +
	"\x0eExchangerPrice\x18\x05 \x01(\v2\r.Common.MoneyR\x0eExchangerPrice\x12\"\n" +
	"\fOperatorName\x18\x06 \x01(\tR\fOperatorName\x12\"\n" +
	"\fMobileNumber\x18\a \x01(\tR\fMobileNumber\x12\x1c\n" +
	"\tManagerId\x18\b \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\t \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\n" +
	" \x01(\tR\x02Id\x12C\n" +
	"\x15PackageConvertedPrice\x18\v \x01(\v2\r.Common.MoneyR\x15PackageConvertedPrice\"\xd5\x01\n" +
	"=CommitOrRollbackCustomFeatureCreditReductionIntegratedCommand\x12 \n" +
	"\vIsCommitted\x18\x01 \x01(\bR\vIsCommitted\x12<\n" +
	"\aContext\x18\x02 \x01(\v2\".Common.CreditReductionMetaContextR\aContext\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\xb0\x01\n" +
	"5CustomFeatureCreditReductionResponseIntegratedCommand\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12)\n" +
	"\aFailure\x18\x02 \x01(\v2\x0f.Common.FailureR\aFailure\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\xf2\x01\n" +
	"5AddAccountringCustomFeatureDocumentsIntegratedCommand\x12E\n" +
	"\rBuyChargeInfo\x18\x01 \x01(\v2\x1f.Common.BuyChargeAccountingInfoR\rBuyChargeInfo\x12\x1e\n" +
	"\n" +
	"CustomerId\x18\x02 \x01(\tR\n" +
	"CustomerId\x12\x1c\n" +
	"\tManagerId\x18\x03 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x04 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x05 \x01(\tR\x02Id\"\xb7\x01\n" +
	"<AddAccountingCustomFeatureDocumentsResponseIntegratedCommand\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12)\n" +
	"\aFailure\x18\x02 \x01(\v2\x0f.Common.FailureR\aFailure\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\x9f\x01\n" +
	"ECommitOrRollbackAddedCustomFeatureAccountingDocumentIntegratedCommand\x12 \n" +
	"\vIsCommitted\x18\x01 \x01(\bR\vIsCommitted\x12$\n" +
	"\rCorrelationId\x18\x02 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x03 \x01(\tR\x02Id\"\xb4\x01\n" +
	",SubmitOrCancelCustomFeatureIntegratedCommand\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage\x12\x1c\n" +
	"\tManagerId\x18\x03 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x04 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x05 \x01(\tR\x02IdBbZ4moneyx.golang.framework/integration/BuyCustomFeature\xaa\x02)Ariyana.Framework.Schema.BuyCustomFeatureb\x06proto3"

var (
	file_BuyCustomFeature_proto_rawDescOnce sync.Once
	file_BuyCustomFeature_proto_rawDescData []byte
)

func file_BuyCustomFeature_proto_rawDescGZIP() []byte {
	file_BuyCustomFeature_proto_rawDescOnce.Do(func() {
		file_BuyCustomFeature_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_BuyCustomFeature_proto_rawDesc), len(file_BuyCustomFeature_proto_rawDesc)))
	})
	return file_BuyCustomFeature_proto_rawDescData
}

var file_BuyCustomFeature_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_BuyCustomFeature_proto_goTypes = []any{
	(*CustomFeatureCheckCustomerActivationIntegratedCommand)(nil),                 // 0: BuyCustomFeature.CustomFeatureCheckCustomerActivationIntegratedCommand
	(*CustomFeatureCheckCustomerActivationResponseIntegratedCommand)(nil),         // 1: BuyCustomFeature.CustomFeatureCheckCustomerActivationResponseIntegratedCommand
	(*CustomFeatureCreditReductionIntegratedCommand)(nil),                         // 2: BuyCustomFeature.CustomFeatureCreditReductionIntegratedCommand
	(*CommitOrRollbackCustomFeatureCreditReductionIntegratedCommand)(nil),         // 3: BuyCustomFeature.CommitOrRollbackCustomFeatureCreditReductionIntegratedCommand
	(*CustomFeatureCreditReductionResponseIntegratedCommand)(nil),                 // 4: BuyCustomFeature.CustomFeatureCreditReductionResponseIntegratedCommand
	(*AddAccountringCustomFeatureDocumentsIntegratedCommand)(nil),                 // 5: BuyCustomFeature.AddAccountringCustomFeatureDocumentsIntegratedCommand
	(*AddAccountingCustomFeatureDocumentsResponseIntegratedCommand)(nil),          // 6: BuyCustomFeature.AddAccountingCustomFeatureDocumentsResponseIntegratedCommand
	(*CommitOrRollbackAddedCustomFeatureAccountingDocumentIntegratedCommand)(nil), // 7: BuyCustomFeature.CommitOrRollbackAddedCustomFeatureAccountingDocumentIntegratedCommand
	(*SubmitOrCancelCustomFeatureIntegratedCommand)(nil),                          // 8: BuyCustomFeature.SubmitOrCancelCustomFeatureIntegratedCommand
	(*common.Failure)(nil),                    // 9: Common.Failure
	(*common.Money)(nil),                      // 10: Common.Money
	(*common.CreditReductionMetaContext)(nil), // 11: Common.CreditReductionMetaContext
	(*common.BuyChargeAccountingInfo)(nil),    // 12: Common.BuyChargeAccountingInfo
}
var file_BuyCustomFeature_proto_depIdxs = []int32{
	9,  // 0: BuyCustomFeature.CustomFeatureCheckCustomerActivationResponseIntegratedCommand.Failure:type_name -> Common.Failure
	10, // 1: BuyCustomFeature.CustomFeatureCreditReductionIntegratedCommand.ExchangerProfit:type_name -> Common.Money
	10, // 2: BuyCustomFeature.CustomFeatureCreditReductionIntegratedCommand.ExchangerPrice:type_name -> Common.Money
	10, // 3: BuyCustomFeature.CustomFeatureCreditReductionIntegratedCommand.PackageConvertedPrice:type_name -> Common.Money
	11, // 4: BuyCustomFeature.CommitOrRollbackCustomFeatureCreditReductionIntegratedCommand.Context:type_name -> Common.CreditReductionMetaContext
	9,  // 5: BuyCustomFeature.CustomFeatureCreditReductionResponseIntegratedCommand.Failure:type_name -> Common.Failure
	12, // 6: BuyCustomFeature.AddAccountringCustomFeatureDocumentsIntegratedCommand.BuyChargeInfo:type_name -> Common.BuyChargeAccountingInfo
	9,  // 7: BuyCustomFeature.AddAccountingCustomFeatureDocumentsResponseIntegratedCommand.Failure:type_name -> Common.Failure
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_BuyCustomFeature_proto_init() }
func file_BuyCustomFeature_proto_init() {
	if File_BuyCustomFeature_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_BuyCustomFeature_proto_rawDesc), len(file_BuyCustomFeature_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_BuyCustomFeature_proto_goTypes,
		DependencyIndexes: file_BuyCustomFeature_proto_depIdxs,
		MessageInfos:      file_BuyCustomFeature_proto_msgTypes,
	}.Build()
	File_BuyCustomFeature_proto = out.File
	file_BuyCustomFeature_proto_goTypes = nil
	file_BuyCustomFeature_proto_depIdxs = nil
}
