// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: RemoveAccount.proto

package RemoveAccount

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "moneyx.golang.framework/integration/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoveAccountNameFromIdentityIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=CustomerId,proto3" json:"CustomerId,omitempty"`
	AccountNumber string                 `protobuf:"bytes,2,opt,name=AccountNumber,proto3" json:"AccountNumber,omitempty"`
	ManagerId     string                 `protobuf:"bytes,3,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,5,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAccountNameFromIdentityIntegratedCommand) Reset() {
	*x = RemoveAccountNameFromIdentityIntegratedCommand{}
	mi := &file_RemoveAccount_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAccountNameFromIdentityIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAccountNameFromIdentityIntegratedCommand) ProtoMessage() {}

func (x *RemoveAccountNameFromIdentityIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_RemoveAccount_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAccountNameFromIdentityIntegratedCommand.ProtoReflect.Descriptor instead.
func (*RemoveAccountNameFromIdentityIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_RemoveAccount_proto_rawDescGZIP(), []int{0}
}

func (x *RemoveAccountNameFromIdentityIntegratedCommand) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *RemoveAccountNameFromIdentityIntegratedCommand) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *RemoveAccountNameFromIdentityIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *RemoveAccountNameFromIdentityIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RemoveAccountNameFromIdentityIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveAccountNameFromIdentityResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDone        bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=Failure,proto3" json:"Failure,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAccountNameFromIdentityResponseIntegratedCommand) Reset() {
	*x = RemoveAccountNameFromIdentityResponseIntegratedCommand{}
	mi := &file_RemoveAccount_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAccountNameFromIdentityResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAccountNameFromIdentityResponseIntegratedCommand) ProtoMessage() {}

func (x *RemoveAccountNameFromIdentityResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_RemoveAccount_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAccountNameFromIdentityResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*RemoveAccountNameFromIdentityResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_RemoveAccount_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveAccountNameFromIdentityResponseIntegratedCommand) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *RemoveAccountNameFromIdentityResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *RemoveAccountNameFromIdentityResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RemoveAccountNameFromIdentityResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CommitOrRollbackRemovedAccountNameFromIdentityIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCommitted   bool                   `protobuf:"varint,1,opt,name=IsCommitted,proto3" json:"IsCommitted,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOrRollbackRemovedAccountNameFromIdentityIntegratedCommand) Reset() {
	*x = CommitOrRollbackRemovedAccountNameFromIdentityIntegratedCommand{}
	mi := &file_RemoveAccount_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOrRollbackRemovedAccountNameFromIdentityIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOrRollbackRemovedAccountNameFromIdentityIntegratedCommand) ProtoMessage() {}

func (x *CommitOrRollbackRemovedAccountNameFromIdentityIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_RemoveAccount_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOrRollbackRemovedAccountNameFromIdentityIntegratedCommand.ProtoReflect.Descriptor instead.
func (*CommitOrRollbackRemovedAccountNameFromIdentityIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_RemoveAccount_proto_rawDescGZIP(), []int{2}
}

func (x *CommitOrRollbackRemovedAccountNameFromIdentityIntegratedCommand) GetIsCommitted() bool {
	if x != nil {
		return x.IsCommitted
	}
	return false
}

func (x *CommitOrRollbackRemovedAccountNameFromIdentityIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CommitOrRollbackRemovedAccountNameFromIdentityIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_RemoveAccount_proto protoreflect.FileDescriptor

const file_RemoveAccount_proto_rawDesc = "" +
	"\n" +
	"\x13RemoveAccount.proto\x12\rRemoveAccount\x1a\fCommon.proto\"\xca\x01\n" +
	".RemoveAccountNameFromIdentityIntegratedCommand\x12\x1e\n" +
	"\n" +
	"CustomerId\x18\x01 \x01(\tR\n" +
	"CustomerId\x12$\n" +
	"\rAccountNumber\x18\x02 \x01(\tR\rAccountNumber\x12\x1c\n" +
	"\tManagerId\x18\x03 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x04 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x05 \x01(\tR\x02Id\"\xb1\x01\n" +
	"6RemoveAccountNameFromIdentityResponseIntegratedCommand\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12)\n" +
	"\aFailure\x18\x02 \x01(\v2\x0f.Common.FailureR\aFailure\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\x99\x01\n" +
	"?CommitOrRollbackRemovedAccountNameFromIdentityIntegratedCommand\x12 \n" +
	"\vIsCommitted\x18\x01 \x01(\bR\vIsCommitted\x12$\n" +
	"\rCorrelationId\x18\x02 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x03 \x01(\tR\x02IdB\\Z1moneyx.golang.framework/integration/RemoveAccount\xaa\x02&Ariyana.Framework.Schema.RemoveAccountb\x06proto3"

var (
	file_RemoveAccount_proto_rawDescOnce sync.Once
	file_RemoveAccount_proto_rawDescData []byte
)

func file_RemoveAccount_proto_rawDescGZIP() []byte {
	file_RemoveAccount_proto_rawDescOnce.Do(func() {
		file_RemoveAccount_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_RemoveAccount_proto_rawDesc), len(file_RemoveAccount_proto_rawDesc)))
	})
	return file_RemoveAccount_proto_rawDescData
}

var file_RemoveAccount_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_RemoveAccount_proto_goTypes = []any{
	(*RemoveAccountNameFromIdentityIntegratedCommand)(nil),                  // 0: RemoveAccount.RemoveAccountNameFromIdentityIntegratedCommand
	(*RemoveAccountNameFromIdentityResponseIntegratedCommand)(nil),          // 1: RemoveAccount.RemoveAccountNameFromIdentityResponseIntegratedCommand
	(*CommitOrRollbackRemovedAccountNameFromIdentityIntegratedCommand)(nil), // 2: RemoveAccount.CommitOrRollbackRemovedAccountNameFromIdentityIntegratedCommand
	(*common.Failure)(nil), // 3: Common.Failure
}
var file_RemoveAccount_proto_depIdxs = []int32{
	3, // 0: RemoveAccount.RemoveAccountNameFromIdentityResponseIntegratedCommand.Failure:type_name -> Common.Failure
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_RemoveAccount_proto_init() }
func file_RemoveAccount_proto_init() {
	if File_RemoveAccount_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_RemoveAccount_proto_rawDesc), len(file_RemoveAccount_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_RemoveAccount_proto_goTypes,
		DependencyIndexes: file_RemoveAccount_proto_depIdxs,
		MessageInfos:      file_RemoveAccount_proto_msgTypes,
	}.Build()
	File_RemoveAccount_proto = out.File
	file_RemoveAccount_proto_goTypes = nil
	file_RemoveAccount_proto_depIdxs = nil
}
