// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: RemoveExportedDataFile.proto

package RemoveExportedDataFile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoveExportedDataFileIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileIds       []*ToRemoveFileItem    `protobuf:"bytes,1,rep,name=FileIds,proto3" json:"FileIds,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveExportedDataFileIntegratedCommand) Reset() {
	*x = RemoveExportedDataFileIntegratedCommand{}
	mi := &file_RemoveExportedDataFile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveExportedDataFileIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveExportedDataFileIntegratedCommand) ProtoMessage() {}

func (x *RemoveExportedDataFileIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_RemoveExportedDataFile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveExportedDataFileIntegratedCommand.ProtoReflect.Descriptor instead.
func (*RemoveExportedDataFileIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_RemoveExportedDataFile_proto_rawDescGZIP(), []int{0}
}

func (x *RemoveExportedDataFileIntegratedCommand) GetFileIds() []*ToRemoveFileItem {
	if x != nil {
		return x.FileIds
	}
	return nil
}

func (x *RemoveExportedDataFileIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RemoveExportedDataFileIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveExportedDataFileResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDone        bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveExportedDataFileResponseIntegratedCommand) Reset() {
	*x = RemoveExportedDataFileResponseIntegratedCommand{}
	mi := &file_RemoveExportedDataFile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveExportedDataFileResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveExportedDataFileResponseIntegratedCommand) ProtoMessage() {}

func (x *RemoveExportedDataFileResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_RemoveExportedDataFile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveExportedDataFileResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*RemoveExportedDataFileResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_RemoveExportedDataFile_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveExportedDataFileResponseIntegratedCommand) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *RemoveExportedDataFileResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RemoveExportedDataFileResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RollbackRemovedExportedDataFileIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRemovedExportedDataFileIntegratedCommand) Reset() {
	*x = RollbackRemovedExportedDataFileIntegratedCommand{}
	mi := &file_RemoveExportedDataFile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRemovedExportedDataFileIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRemovedExportedDataFileIntegratedCommand) ProtoMessage() {}

func (x *RollbackRemovedExportedDataFileIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_RemoveExportedDataFile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRemovedExportedDataFileIntegratedCommand.ProtoReflect.Descriptor instead.
func (*RollbackRemovedExportedDataFileIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_RemoveExportedDataFile_proto_rawDescGZIP(), []int{2}
}

func (x *RollbackRemovedExportedDataFileIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RollbackRemovedExportedDataFileIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ToRemoveFileItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=FileId,proto3" json:"FileId,omitempty"`
	ManagerId     string                 `protobuf:"bytes,2,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToRemoveFileItem) Reset() {
	*x = ToRemoveFileItem{}
	mi := &file_RemoveExportedDataFile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToRemoveFileItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToRemoveFileItem) ProtoMessage() {}

func (x *ToRemoveFileItem) ProtoReflect() protoreflect.Message {
	mi := &file_RemoveExportedDataFile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToRemoveFileItem.ProtoReflect.Descriptor instead.
func (*ToRemoveFileItem) Descriptor() ([]byte, []int) {
	return file_RemoveExportedDataFile_proto_rawDescGZIP(), []int{3}
}

func (x *ToRemoveFileItem) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *ToRemoveFileItem) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

var File_RemoveExportedDataFile_proto protoreflect.FileDescriptor

const file_RemoveExportedDataFile_proto_rawDesc = "" +
	"\n" +
	"\x1cRemoveExportedDataFile.proto\x12\x16RemoveExportedDataFile\"\xa3\x01\n" +
	"'RemoveExportedDataFileIntegratedCommand\x12B\n" +
	"\aFileIds\x18\x01 \x03(\v2(.RemoveExportedDataFile.ToRemoveFileItemR\aFileIds\x12$\n" +
	"\rCorrelationId\x18\x02 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x03 \x01(\tR\x02Id\"\x7f\n" +
	"/RemoveExportedDataFileResponseIntegratedCommand\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12$\n" +
	"\rCorrelationId\x18\x02 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x03 \x01(\tR\x02Id\"h\n" +
	"0RollbackRemovedExportedDataFileIntegratedCommand\x12$\n" +
	"\rCorrelationId\x18\x01 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x02 \x01(\tR\x02Id\"H\n" +
	"\x10ToRemoveFileItem\x12\x16\n" +
	"\x06FileId\x18\x01 \x01(\tR\x06FileId\x12\x1c\n" +
	"\tManagerId\x18\x02 \x01(\tR\tManagerIdBnZ:moneyx.golang.framework/integration/RemoveExportedDataFile\xaa\x02/Ariyana.Framework.Schema.RemoveExportedDataFileb\x06proto3"

var (
	file_RemoveExportedDataFile_proto_rawDescOnce sync.Once
	file_RemoveExportedDataFile_proto_rawDescData []byte
)

func file_RemoveExportedDataFile_proto_rawDescGZIP() []byte {
	file_RemoveExportedDataFile_proto_rawDescOnce.Do(func() {
		file_RemoveExportedDataFile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_RemoveExportedDataFile_proto_rawDesc), len(file_RemoveExportedDataFile_proto_rawDesc)))
	})
	return file_RemoveExportedDataFile_proto_rawDescData
}

var file_RemoveExportedDataFile_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_RemoveExportedDataFile_proto_goTypes = []any{
	(*RemoveExportedDataFileIntegratedCommand)(nil),          // 0: RemoveExportedDataFile.RemoveExportedDataFileIntegratedCommand
	(*RemoveExportedDataFileResponseIntegratedCommand)(nil),  // 1: RemoveExportedDataFile.RemoveExportedDataFileResponseIntegratedCommand
	(*RollbackRemovedExportedDataFileIntegratedCommand)(nil), // 2: RemoveExportedDataFile.RollbackRemovedExportedDataFileIntegratedCommand
	(*ToRemoveFileItem)(nil),                                 // 3: RemoveExportedDataFile.ToRemoveFileItem
}
var file_RemoveExportedDataFile_proto_depIdxs = []int32{
	3, // 0: RemoveExportedDataFile.RemoveExportedDataFileIntegratedCommand.FileIds:type_name -> RemoveExportedDataFile.ToRemoveFileItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_RemoveExportedDataFile_proto_init() }
func file_RemoveExportedDataFile_proto_init() {
	if File_RemoveExportedDataFile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_RemoveExportedDataFile_proto_rawDesc), len(file_RemoveExportedDataFile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_RemoveExportedDataFile_proto_goTypes,
		DependencyIndexes: file_RemoveExportedDataFile_proto_depIdxs,
		MessageInfos:      file_RemoveExportedDataFile_proto_msgTypes,
	}.Build()
	File_RemoveExportedDataFile_proto = out.File
	file_RemoveExportedDataFile_proto_goTypes = nil
	file_RemoveExportedDataFile_proto_depIdxs = nil
}
