// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: BuyAfghanMTN.proto

package BuyAfghanMTN

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "moneyx.golang.framework/integration/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AfghanMTNCheckCustomerActivationResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsEnable      bool                   `protobuf:"varint,1,opt,name=IsEnable,proto3" json:"IsEnable,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=CustomerId,proto3" json:"CustomerId,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,3,opt,name=Failure,proto3" json:"Failure,omitempty"`
	ManagerId     string                 `protobuf:"bytes,4,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AfghanMTNCheckCustomerActivationResponseIntegratedCommand) Reset() {
	*x = AfghanMTNCheckCustomerActivationResponseIntegratedCommand{}
	mi := &file_BuyAfghanMTN_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AfghanMTNCheckCustomerActivationResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AfghanMTNCheckCustomerActivationResponseIntegratedCommand) ProtoMessage() {}

func (x *AfghanMTNCheckCustomerActivationResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyAfghanMTN_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AfghanMTNCheckCustomerActivationResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*AfghanMTNCheckCustomerActivationResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyAfghanMTN_proto_rawDescGZIP(), []int{0}
}

func (x *AfghanMTNCheckCustomerActivationResponseIntegratedCommand) GetIsEnable() bool {
	if x != nil {
		return x.IsEnable
	}
	return false
}

func (x *AfghanMTNCheckCustomerActivationResponseIntegratedCommand) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *AfghanMTNCheckCustomerActivationResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *AfghanMTNCheckCustomerActivationResponseIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *AfghanMTNCheckCustomerActivationResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AfghanMTNCheckCustomerActivationResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AfghanMTNCheckManagerChargeActivationIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManagerId     string                 `protobuf:"bytes,1,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AfghanMTNCheckManagerChargeActivationIntegratedCommand) Reset() {
	*x = AfghanMTNCheckManagerChargeActivationIntegratedCommand{}
	mi := &file_BuyAfghanMTN_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AfghanMTNCheckManagerChargeActivationIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AfghanMTNCheckManagerChargeActivationIntegratedCommand) ProtoMessage() {}

func (x *AfghanMTNCheckManagerChargeActivationIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyAfghanMTN_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AfghanMTNCheckManagerChargeActivationIntegratedCommand.ProtoReflect.Descriptor instead.
func (*AfghanMTNCheckManagerChargeActivationIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyAfghanMTN_proto_rawDescGZIP(), []int{1}
}

func (x *AfghanMTNCheckManagerChargeActivationIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *AfghanMTNCheckManagerChargeActivationIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AfghanMTNCheckManagerChargeActivationIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AfghanMTNCheckManagerChargeActivationResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsEnable      bool                   `protobuf:"varint,1,opt,name=IsEnable,proto3" json:"IsEnable,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=Failure,proto3" json:"Failure,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AfghanMTNCheckManagerChargeActivationResponseIntegratedCommand) Reset() {
	*x = AfghanMTNCheckManagerChargeActivationResponseIntegratedCommand{}
	mi := &file_BuyAfghanMTN_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AfghanMTNCheckManagerChargeActivationResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AfghanMTNCheckManagerChargeActivationResponseIntegratedCommand) ProtoMessage() {}

func (x *AfghanMTNCheckManagerChargeActivationResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyAfghanMTN_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AfghanMTNCheckManagerChargeActivationResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*AfghanMTNCheckManagerChargeActivationResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyAfghanMTN_proto_rawDescGZIP(), []int{2}
}

func (x *AfghanMTNCheckManagerChargeActivationResponseIntegratedCommand) GetIsEnable() bool {
	if x != nil {
		return x.IsEnable
	}
	return false
}

func (x *AfghanMTNCheckManagerChargeActivationResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *AfghanMTNCheckManagerChargeActivationResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AfghanMTNCheckManagerChargeActivationResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BuyAfghanMTNChargeByKarimyarIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AmountPackage float64                `protobuf:"fixed64,1,opt,name=AmountPackage,proto3" json:"AmountPackage,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=TransactionId,proto3" json:"TransactionId,omitempty"`
	ChargeNumber  string                 `protobuf:"bytes,3,opt,name=ChargeNumber,proto3" json:"ChargeNumber,omitempty"`
	PackageCode   string                 `protobuf:"bytes,4,opt,name=PackageCode,proto3" json:"PackageCode,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyAfghanMTNChargeByKarimyarIntegratedCommand) Reset() {
	*x = BuyAfghanMTNChargeByKarimyarIntegratedCommand{}
	mi := &file_BuyAfghanMTN_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyAfghanMTNChargeByKarimyarIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyAfghanMTNChargeByKarimyarIntegratedCommand) ProtoMessage() {}

func (x *BuyAfghanMTNChargeByKarimyarIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyAfghanMTN_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyAfghanMTNChargeByKarimyarIntegratedCommand.ProtoReflect.Descriptor instead.
func (*BuyAfghanMTNChargeByKarimyarIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyAfghanMTN_proto_rawDescGZIP(), []int{3}
}

func (x *BuyAfghanMTNChargeByKarimyarIntegratedCommand) GetAmountPackage() float64 {
	if x != nil {
		return x.AmountPackage
	}
	return 0
}

func (x *BuyAfghanMTNChargeByKarimyarIntegratedCommand) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *BuyAfghanMTNChargeByKarimyarIntegratedCommand) GetChargeNumber() string {
	if x != nil {
		return x.ChargeNumber
	}
	return ""
}

func (x *BuyAfghanMTNChargeByKarimyarIntegratedCommand) GetPackageCode() string {
	if x != nil {
		return x.PackageCode
	}
	return ""
}

func (x *BuyAfghanMTNChargeByKarimyarIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BuyAfghanMTNChargeByKarimyarIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BuyAfghanMTNChargeByKarimyarResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDone        bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=Failure,proto3" json:"Failure,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	ResponseId    string                 `protobuf:"bytes,5,opt,name=ResponseId,proto3" json:"ResponseId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyAfghanMTNChargeByKarimyarResponseIntegratedCommand) Reset() {
	*x = BuyAfghanMTNChargeByKarimyarResponseIntegratedCommand{}
	mi := &file_BuyAfghanMTN_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyAfghanMTNChargeByKarimyarResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyAfghanMTNChargeByKarimyarResponseIntegratedCommand) ProtoMessage() {}

func (x *BuyAfghanMTNChargeByKarimyarResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyAfghanMTN_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyAfghanMTNChargeByKarimyarResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*BuyAfghanMTNChargeByKarimyarResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyAfghanMTN_proto_rawDescGZIP(), []int{4}
}

func (x *BuyAfghanMTNChargeByKarimyarResponseIntegratedCommand) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *BuyAfghanMTNChargeByKarimyarResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *BuyAfghanMTNChargeByKarimyarResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BuyAfghanMTNChargeByKarimyarResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BuyAfghanMTNChargeByKarimyarResponseIntegratedCommand) GetResponseId() string {
	if x != nil {
		return x.ResponseId
	}
	return ""
}

type BuyAfghanMTNChargeByNaqdinehIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AmountPackage float64                `protobuf:"fixed64,1,opt,name=AmountPackage,proto3" json:"AmountPackage,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=TransactionId,proto3" json:"TransactionId,omitempty"`
	ChargeNumber  string                 `protobuf:"bytes,3,opt,name=ChargeNumber,proto3" json:"ChargeNumber,omitempty"`
	PackageCode   string                 `protobuf:"bytes,4,opt,name=PackageCode,proto3" json:"PackageCode,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyAfghanMTNChargeByNaqdinehIntegratedCommand) Reset() {
	*x = BuyAfghanMTNChargeByNaqdinehIntegratedCommand{}
	mi := &file_BuyAfghanMTN_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyAfghanMTNChargeByNaqdinehIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyAfghanMTNChargeByNaqdinehIntegratedCommand) ProtoMessage() {}

func (x *BuyAfghanMTNChargeByNaqdinehIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyAfghanMTN_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyAfghanMTNChargeByNaqdinehIntegratedCommand.ProtoReflect.Descriptor instead.
func (*BuyAfghanMTNChargeByNaqdinehIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyAfghanMTN_proto_rawDescGZIP(), []int{5}
}

func (x *BuyAfghanMTNChargeByNaqdinehIntegratedCommand) GetAmountPackage() float64 {
	if x != nil {
		return x.AmountPackage
	}
	return 0
}

func (x *BuyAfghanMTNChargeByNaqdinehIntegratedCommand) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *BuyAfghanMTNChargeByNaqdinehIntegratedCommand) GetChargeNumber() string {
	if x != nil {
		return x.ChargeNumber
	}
	return ""
}

func (x *BuyAfghanMTNChargeByNaqdinehIntegratedCommand) GetPackageCode() string {
	if x != nil {
		return x.PackageCode
	}
	return ""
}

func (x *BuyAfghanMTNChargeByNaqdinehIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BuyAfghanMTNChargeByNaqdinehIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BuyAfghanMTNChargeByNaqdinehResponseIntegratedCommand struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	IsDone                   bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	Failure                  *common.Failure        `protobuf:"bytes,2,opt,name=Failure,proto3" json:"Failure,omitempty"`
	ServiceProviderRefNumber string                 `protobuf:"bytes,3,opt,name=ServiceProviderRefNumber,proto3" json:"ServiceProviderRefNumber,omitempty"`
	CorrelationId            string                 `protobuf:"bytes,4,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id                       string                 `protobuf:"bytes,5,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *BuyAfghanMTNChargeByNaqdinehResponseIntegratedCommand) Reset() {
	*x = BuyAfghanMTNChargeByNaqdinehResponseIntegratedCommand{}
	mi := &file_BuyAfghanMTN_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyAfghanMTNChargeByNaqdinehResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyAfghanMTNChargeByNaqdinehResponseIntegratedCommand) ProtoMessage() {}

func (x *BuyAfghanMTNChargeByNaqdinehResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyAfghanMTN_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyAfghanMTNChargeByNaqdinehResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*BuyAfghanMTNChargeByNaqdinehResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyAfghanMTN_proto_rawDescGZIP(), []int{6}
}

func (x *BuyAfghanMTNChargeByNaqdinehResponseIntegratedCommand) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *BuyAfghanMTNChargeByNaqdinehResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *BuyAfghanMTNChargeByNaqdinehResponseIntegratedCommand) GetServiceProviderRefNumber() string {
	if x != nil {
		return x.ServiceProviderRefNumber
	}
	return ""
}

func (x *BuyAfghanMTNChargeByNaqdinehResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BuyAfghanMTNChargeByNaqdinehResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BuyAfghanMTNChargeCreditReductionIntegratedCommand struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	AccountId              string                 `protobuf:"bytes,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	PackageTitle           string                 `protobuf:"bytes,2,opt,name=PackageTitle,proto3" json:"PackageTitle,omitempty"`
	ChargeTransactionId    string                 `protobuf:"bytes,3,opt,name=ChargeTransactionId,proto3" json:"ChargeTransactionId,omitempty"`
	Commission             *common.Money          `protobuf:"bytes,4,opt,name=Commission,proto3" json:"Commission,omitempty"`
	ExchangerDeductedMoney *common.Money          `protobuf:"bytes,5,opt,name=ExchangerDeductedMoney,proto3" json:"ExchangerDeductedMoney,omitempty"`
	OperatorName           string                 `protobuf:"bytes,6,opt,name=OperatorName,proto3" json:"OperatorName,omitempty"`
	PhoneNumber            string                 `protobuf:"bytes,7,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	ManagerId              string                 `protobuf:"bytes,8,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId          string                 `protobuf:"bytes,9,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id                     string                 `protobuf:"bytes,10,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BuyAfghanMTNChargeCreditReductionIntegratedCommand) Reset() {
	*x = BuyAfghanMTNChargeCreditReductionIntegratedCommand{}
	mi := &file_BuyAfghanMTN_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyAfghanMTNChargeCreditReductionIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyAfghanMTNChargeCreditReductionIntegratedCommand) ProtoMessage() {}

func (x *BuyAfghanMTNChargeCreditReductionIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyAfghanMTN_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyAfghanMTNChargeCreditReductionIntegratedCommand.ProtoReflect.Descriptor instead.
func (*BuyAfghanMTNChargeCreditReductionIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyAfghanMTN_proto_rawDescGZIP(), []int{7}
}

func (x *BuyAfghanMTNChargeCreditReductionIntegratedCommand) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *BuyAfghanMTNChargeCreditReductionIntegratedCommand) GetPackageTitle() string {
	if x != nil {
		return x.PackageTitle
	}
	return ""
}

func (x *BuyAfghanMTNChargeCreditReductionIntegratedCommand) GetChargeTransactionId() string {
	if x != nil {
		return x.ChargeTransactionId
	}
	return ""
}

func (x *BuyAfghanMTNChargeCreditReductionIntegratedCommand) GetCommission() *common.Money {
	if x != nil {
		return x.Commission
	}
	return nil
}

func (x *BuyAfghanMTNChargeCreditReductionIntegratedCommand) GetExchangerDeductedMoney() *common.Money {
	if x != nil {
		return x.ExchangerDeductedMoney
	}
	return nil
}

func (x *BuyAfghanMTNChargeCreditReductionIntegratedCommand) GetOperatorName() string {
	if x != nil {
		return x.OperatorName
	}
	return ""
}

func (x *BuyAfghanMTNChargeCreditReductionIntegratedCommand) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *BuyAfghanMTNChargeCreditReductionIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *BuyAfghanMTNChargeCreditReductionIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BuyAfghanMTNChargeCreditReductionIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BuyAfghanMTNChargeCreditReductionResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDone        bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=Failure,proto3" json:"Failure,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyAfghanMTNChargeCreditReductionResponseIntegratedCommand) Reset() {
	*x = BuyAfghanMTNChargeCreditReductionResponseIntegratedCommand{}
	mi := &file_BuyAfghanMTN_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyAfghanMTNChargeCreditReductionResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyAfghanMTNChargeCreditReductionResponseIntegratedCommand) ProtoMessage() {}

func (x *BuyAfghanMTNChargeCreditReductionResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyAfghanMTN_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyAfghanMTNChargeCreditReductionResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*BuyAfghanMTNChargeCreditReductionResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyAfghanMTN_proto_rawDescGZIP(), []int{8}
}

func (x *BuyAfghanMTNChargeCreditReductionResponseIntegratedCommand) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *BuyAfghanMTNChargeCreditReductionResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *BuyAfghanMTNChargeCreditReductionResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BuyAfghanMTNChargeCreditReductionResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CommitOrRollbackAddedBuyAfghanMTNChargeAccountingDocumentIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCommitted   bool                   `protobuf:"varint,1,opt,name=IsCommitted,proto3" json:"IsCommitted,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOrRollbackAddedBuyAfghanMTNChargeAccountingDocumentIntegratedCommand) Reset() {
	*x = CommitOrRollbackAddedBuyAfghanMTNChargeAccountingDocumentIntegratedCommand{}
	mi := &file_BuyAfghanMTN_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOrRollbackAddedBuyAfghanMTNChargeAccountingDocumentIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOrRollbackAddedBuyAfghanMTNChargeAccountingDocumentIntegratedCommand) ProtoMessage() {}

func (x *CommitOrRollbackAddedBuyAfghanMTNChargeAccountingDocumentIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyAfghanMTN_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOrRollbackAddedBuyAfghanMTNChargeAccountingDocumentIntegratedCommand.ProtoReflect.Descriptor instead.
func (*CommitOrRollbackAddedBuyAfghanMTNChargeAccountingDocumentIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyAfghanMTN_proto_rawDescGZIP(), []int{9}
}

func (x *CommitOrRollbackAddedBuyAfghanMTNChargeAccountingDocumentIntegratedCommand) GetIsCommitted() bool {
	if x != nil {
		return x.IsCommitted
	}
	return false
}

func (x *CommitOrRollbackAddedBuyAfghanMTNChargeAccountingDocumentIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CommitOrRollbackAddedBuyAfghanMTNChargeAccountingDocumentIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CommitOrRollbackBuyAfghanMTNChargeCreditReductionIntegratedCommand struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	IsCommitted   bool                               `protobuf:"varint,1,opt,name=IsCommitted,proto3" json:"IsCommitted,omitempty"`
	Context       *common.CreditReductionMetaContext `protobuf:"bytes,2,opt,name=Context,proto3" json:"Context,omitempty"`
	CorrelationId string                             `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                             `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOrRollbackBuyAfghanMTNChargeCreditReductionIntegratedCommand) Reset() {
	*x = CommitOrRollbackBuyAfghanMTNChargeCreditReductionIntegratedCommand{}
	mi := &file_BuyAfghanMTN_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOrRollbackBuyAfghanMTNChargeCreditReductionIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOrRollbackBuyAfghanMTNChargeCreditReductionIntegratedCommand) ProtoMessage() {}

func (x *CommitOrRollbackBuyAfghanMTNChargeCreditReductionIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyAfghanMTN_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOrRollbackBuyAfghanMTNChargeCreditReductionIntegratedCommand.ProtoReflect.Descriptor instead.
func (*CommitOrRollbackBuyAfghanMTNChargeCreditReductionIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyAfghanMTN_proto_rawDescGZIP(), []int{10}
}

func (x *CommitOrRollbackBuyAfghanMTNChargeCreditReductionIntegratedCommand) GetIsCommitted() bool {
	if x != nil {
		return x.IsCommitted
	}
	return false
}

func (x *CommitOrRollbackBuyAfghanMTNChargeCreditReductionIntegratedCommand) GetContext() *common.CreditReductionMetaContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CommitOrRollbackBuyAfghanMTNChargeCreditReductionIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CommitOrRollbackBuyAfghanMTNChargeCreditReductionIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RollbackBuyAfghanMTNChargeDocumentsIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackBuyAfghanMTNChargeDocumentsIntegratedCommand) Reset() {
	*x = RollbackBuyAfghanMTNChargeDocumentsIntegratedCommand{}
	mi := &file_BuyAfghanMTN_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackBuyAfghanMTNChargeDocumentsIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackBuyAfghanMTNChargeDocumentsIntegratedCommand) ProtoMessage() {}

func (x *RollbackBuyAfghanMTNChargeDocumentsIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyAfghanMTN_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackBuyAfghanMTNChargeDocumentsIntegratedCommand.ProtoReflect.Descriptor instead.
func (*RollbackBuyAfghanMTNChargeDocumentsIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyAfghanMTN_proto_rawDescGZIP(), []int{11}
}

func (x *RollbackBuyAfghanMTNChargeDocumentsIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RollbackBuyAfghanMTNChargeDocumentsIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddAccountingBuyAfghanMTNChargeDocumentsIntegratedCommand struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	BuyChargeInfo *common.BuyChargeAccountingInfo `protobuf:"bytes,1,opt,name=BuyChargeInfo,proto3" json:"BuyChargeInfo,omitempty"`
	CustomerId    string                          `protobuf:"bytes,2,opt,name=CustomerId,proto3" json:"CustomerId,omitempty"`
	ManagerId     string                          `protobuf:"bytes,3,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId string                          `protobuf:"bytes,4,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                          `protobuf:"bytes,5,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAccountingBuyAfghanMTNChargeDocumentsIntegratedCommand) Reset() {
	*x = AddAccountingBuyAfghanMTNChargeDocumentsIntegratedCommand{}
	mi := &file_BuyAfghanMTN_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAccountingBuyAfghanMTNChargeDocumentsIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAccountingBuyAfghanMTNChargeDocumentsIntegratedCommand) ProtoMessage() {}

func (x *AddAccountingBuyAfghanMTNChargeDocumentsIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyAfghanMTN_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAccountingBuyAfghanMTNChargeDocumentsIntegratedCommand.ProtoReflect.Descriptor instead.
func (*AddAccountingBuyAfghanMTNChargeDocumentsIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyAfghanMTN_proto_rawDescGZIP(), []int{12}
}

func (x *AddAccountingBuyAfghanMTNChargeDocumentsIntegratedCommand) GetBuyChargeInfo() *common.BuyChargeAccountingInfo {
	if x != nil {
		return x.BuyChargeInfo
	}
	return nil
}

func (x *AddAccountingBuyAfghanMTNChargeDocumentsIntegratedCommand) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *AddAccountingBuyAfghanMTNChargeDocumentsIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *AddAccountingBuyAfghanMTNChargeDocumentsIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AddAccountingBuyAfghanMTNChargeDocumentsIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddAccountingBuyAfghanMTNChargeDocumentsResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDone        bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=Failure,proto3" json:"Failure,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAccountingBuyAfghanMTNChargeDocumentsResponseIntegratedCommand) Reset() {
	*x = AddAccountingBuyAfghanMTNChargeDocumentsResponseIntegratedCommand{}
	mi := &file_BuyAfghanMTN_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAccountingBuyAfghanMTNChargeDocumentsResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAccountingBuyAfghanMTNChargeDocumentsResponseIntegratedCommand) ProtoMessage() {}

func (x *AddAccountingBuyAfghanMTNChargeDocumentsResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyAfghanMTN_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAccountingBuyAfghanMTNChargeDocumentsResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*AddAccountingBuyAfghanMTNChargeDocumentsResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyAfghanMTN_proto_rawDescGZIP(), []int{13}
}

func (x *AddAccountingBuyAfghanMTNChargeDocumentsResponseIntegratedCommand) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *AddAccountingBuyAfghanMTNChargeDocumentsResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *AddAccountingBuyAfghanMTNChargeDocumentsResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AddAccountingBuyAfghanMTNChargeDocumentsResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AfghanMTNCheckCustomerActivationIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	ManagerId     string                 `protobuf:"bytes,3,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,5,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AfghanMTNCheckCustomerActivationIntegratedCommand) Reset() {
	*x = AfghanMTNCheckCustomerActivationIntegratedCommand{}
	mi := &file_BuyAfghanMTN_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AfghanMTNCheckCustomerActivationIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AfghanMTNCheckCustomerActivationIntegratedCommand) ProtoMessage() {}

func (x *AfghanMTNCheckCustomerActivationIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyAfghanMTN_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AfghanMTNCheckCustomerActivationIntegratedCommand.ProtoReflect.Descriptor instead.
func (*AfghanMTNCheckCustomerActivationIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyAfghanMTN_proto_rawDescGZIP(), []int{14}
}

func (x *AfghanMTNCheckCustomerActivationIntegratedCommand) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *AfghanMTNCheckCustomerActivationIntegratedCommand) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AfghanMTNCheckCustomerActivationIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *AfghanMTNCheckCustomerActivationIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AfghanMTNCheckCustomerActivationIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_BuyAfghanMTN_proto protoreflect.FileDescriptor

const file_BuyAfghanMTN_proto_rawDesc = "" +
	"\n" +
	"\x12BuyAfghanMTN.proto\x12\fBuyAfghanMTN\x1a\fCommon.proto\"\xf6\x01\n" +
	"9AfghanMTNCheckCustomerActivationResponseIntegratedCommand\x12\x1a\n" +
	"\bIsEnable\x18\x01 \x01(\bR\bIsEnable\x12\x1e\n" +
	"\n" +
	"CustomerId\x18\x02 \x01(\tR\n" +
	"CustomerId\x12)\n" +
	"\aFailure\x18\x03 \x01(\v2\x0f.Common.FailureR\aFailure\x12\x1c\n" +
	"\tManagerId\x18\x04 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x05 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x06 \x01(\tR\x02Id\"\x8c\x01\n" +
	"6AfghanMTNCheckManagerChargeActivationIntegratedCommand\x12\x1c\n" +
	"\tManagerId\x18\x01 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x02 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x03 \x01(\tR\x02Id\"\xbd\x01\n" +
	">AfghanMTNCheckManagerChargeActivationResponseIntegratedCommand\x12\x1a\n" +
	"\bIsEnable\x18\x01 \x01(\bR\bIsEnable\x12)\n" +
	"\aFailure\x18\x02 \x01(\v2\x0f.Common.FailureR\aFailure\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\xf7\x01\n" +
	"-BuyAfghanMTNChargeByKarimyarIntegratedCommand\x12$\n" +
	"\rAmountPackage\x18\x01 \x01(\x01R\rAmountPackage\x12$\n" +
	"\rTransactionId\x18\x02 \x01(\tR\rTransactionId\x12\"\n" +
	"\fChargeNumber\x18\x03 \x01(\tR\fChargeNumber\x12 \n" +
	"\vPackageCode\x18\x04 \x01(\tR\vPackageCode\x12$\n" +
	"\rCorrelationId\x18\x05 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x06 \x01(\tR\x02Id\"\xd0\x01\n" +
	"5BuyAfghanMTNChargeByKarimyarResponseIntegratedCommand\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12)\n" +
	"\aFailure\x18\x02 \x01(\v2\x0f.Common.FailureR\aFailure\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\x12\x1e\n" +
	"\n" +
	"ResponseId\x18\x05 \x01(\tR\n" +
	"ResponseId\"\xf7\x01\n" +
	"-BuyAfghanMTNChargeByNaqdinehIntegratedCommand\x12$\n" +
	"\rAmountPackage\x18\x01 \x01(\x01R\rAmountPackage\x12$\n" +
	"\rTransactionId\x18\x02 \x01(\tR\rTransactionId\x12\"\n" +
	"\fChargeNumber\x18\x03 \x01(\tR\fChargeNumber\x12 \n" +
	"\vPackageCode\x18\x04 \x01(\tR\vPackageCode\x12$\n" +
	"\rCorrelationId\x18\x05 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x06 \x01(\tR\x02Id\"\xec\x01\n" +
	"5BuyAfghanMTNChargeByNaqdinehResponseIntegratedCommand\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12)\n" +
	"\aFailure\x18\x02 \x01(\v2\x0f.Common.FailureR\aFailure\x12:\n" +
	"\x18ServiceProviderRefNumber\x18\x03 \x01(\tR\x18ServiceProviderRefNumber\x12$\n" +
	"\rCorrelationId\x18\x04 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x05 \x01(\tR\x02Id\"\xb8\x03\n" +
	"2BuyAfghanMTNChargeCreditReductionIntegratedCommand\x12\x1c\n" +
	"\tAccountId\x18\x01 \x01(\tR\tAccountId\x12\"\n" +
	"\fPackageTitle\x18\x02 \x01(\tR\fPackageTitle\x120\n" +
	"\x13ChargeTransactionId\x18\x03 \x01(\tR\x13ChargeTransactionId\x12-\n" +
	"\n" +
	"Commission\x18\x04 \x01(\v2\r.Common.MoneyR\n" +
	"Commission\x12E\n" +
	"\x16ExchangerDeductedMoney\x18\x05 \x01(\v2\r.Common.MoneyR\x16ExchangerDeductedMoney\x12\"\n" +
	"\fOperatorName\x18\x06 \x01(\tR\fOperatorName\x12 \n" +
	"\vPhoneNumber\x18\a \x01(\tR\vPhoneNumber\x12\x1c\n" +
	"\tManagerId\x18\b \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\t \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\n" +
	" \x01(\tR\x02Id\"\xb5\x01\n" +
	":BuyAfghanMTNChargeCreditReductionResponseIntegratedCommand\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12)\n" +
	"\aFailure\x18\x02 \x01(\v2\x0f.Common.FailureR\aFailure\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\xa4\x01\n" +
	"JCommitOrRollbackAddedBuyAfghanMTNChargeAccountingDocumentIntegratedCommand\x12 \n" +
	"\vIsCommitted\x18\x01 \x01(\bR\vIsCommitted\x12$\n" +
	"\rCorrelationId\x18\x02 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x03 \x01(\tR\x02Id\"\xda\x01\n" +
	"BCommitOrRollbackBuyAfghanMTNChargeCreditReductionIntegratedCommand\x12 \n" +
	"\vIsCommitted\x18\x01 \x01(\bR\vIsCommitted\x12<\n" +
	"\aContext\x18\x02 \x01(\v2\".Common.CreditReductionMetaContextR\aContext\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"l\n" +
	"4RollbackBuyAfghanMTNChargeDocumentsIntegratedCommand\x12$\n" +
	"\rCorrelationId\x18\x01 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x02 \x01(\tR\x02Id\"\xf6\x01\n" +
	"9AddAccountingBuyAfghanMTNChargeDocumentsIntegratedCommand\x12E\n" +
	"\rBuyChargeInfo\x18\x01 \x01(\v2\x1f.Common.BuyChargeAccountingInfoR\rBuyChargeInfo\x12\x1e\n" +
	"\n" +
	"CustomerId\x18\x02 \x01(\tR\n" +
	"CustomerId\x12\x1c\n" +
	"\tManagerId\x18\x03 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x04 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x05 \x01(\tR\x02Id\"\xbc\x01\n" +
	"AAddAccountingBuyAfghanMTNChargeDocumentsResponseIntegratedCommand\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12)\n" +
	"\aFailure\x18\x02 \x01(\v2\x0f.Common.FailureR\aFailure\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\xc1\x01\n" +
	"1AfghanMTNCheckCustomerActivationIntegratedCommand\x12\x1a\n" +
	"\bUserName\x18\x01 \x01(\tR\bUserName\x12\x1c\n" +
	"\tAccountId\x18\x02 \x01(\tR\tAccountId\x12\x1c\n" +
	"\tManagerId\x18\x03 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x04 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x05 \x01(\tR\x02IdBZZ0moneyx.golang.framework/integration/BuyAfghanMTN\xaa\x02%Ariyana.Framework.Schema.BuyAfghanMTNb\x06proto3"

var (
	file_BuyAfghanMTN_proto_rawDescOnce sync.Once
	file_BuyAfghanMTN_proto_rawDescData []byte
)

func file_BuyAfghanMTN_proto_rawDescGZIP() []byte {
	file_BuyAfghanMTN_proto_rawDescOnce.Do(func() {
		file_BuyAfghanMTN_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_BuyAfghanMTN_proto_rawDesc), len(file_BuyAfghanMTN_proto_rawDesc)))
	})
	return file_BuyAfghanMTN_proto_rawDescData
}

var file_BuyAfghanMTN_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_BuyAfghanMTN_proto_goTypes = []any{
	(*AfghanMTNCheckCustomerActivationResponseIntegratedCommand)(nil),                  // 0: BuyAfghanMTN.AfghanMTNCheckCustomerActivationResponseIntegratedCommand
	(*AfghanMTNCheckManagerChargeActivationIntegratedCommand)(nil),                     // 1: BuyAfghanMTN.AfghanMTNCheckManagerChargeActivationIntegratedCommand
	(*AfghanMTNCheckManagerChargeActivationResponseIntegratedCommand)(nil),             // 2: BuyAfghanMTN.AfghanMTNCheckManagerChargeActivationResponseIntegratedCommand
	(*BuyAfghanMTNChargeByKarimyarIntegratedCommand)(nil),                              // 3: BuyAfghanMTN.BuyAfghanMTNChargeByKarimyarIntegratedCommand
	(*BuyAfghanMTNChargeByKarimyarResponseIntegratedCommand)(nil),                      // 4: BuyAfghanMTN.BuyAfghanMTNChargeByKarimyarResponseIntegratedCommand
	(*BuyAfghanMTNChargeByNaqdinehIntegratedCommand)(nil),                              // 5: BuyAfghanMTN.BuyAfghanMTNChargeByNaqdinehIntegratedCommand
	(*BuyAfghanMTNChargeByNaqdinehResponseIntegratedCommand)(nil),                      // 6: BuyAfghanMTN.BuyAfghanMTNChargeByNaqdinehResponseIntegratedCommand
	(*BuyAfghanMTNChargeCreditReductionIntegratedCommand)(nil),                         // 7: BuyAfghanMTN.BuyAfghanMTNChargeCreditReductionIntegratedCommand
	(*BuyAfghanMTNChargeCreditReductionResponseIntegratedCommand)(nil),                 // 8: BuyAfghanMTN.BuyAfghanMTNChargeCreditReductionResponseIntegratedCommand
	(*CommitOrRollbackAddedBuyAfghanMTNChargeAccountingDocumentIntegratedCommand)(nil), // 9: BuyAfghanMTN.CommitOrRollbackAddedBuyAfghanMTNChargeAccountingDocumentIntegratedCommand
	(*CommitOrRollbackBuyAfghanMTNChargeCreditReductionIntegratedCommand)(nil),         // 10: BuyAfghanMTN.CommitOrRollbackBuyAfghanMTNChargeCreditReductionIntegratedCommand
	(*RollbackBuyAfghanMTNChargeDocumentsIntegratedCommand)(nil),                       // 11: BuyAfghanMTN.RollbackBuyAfghanMTNChargeDocumentsIntegratedCommand
	(*AddAccountingBuyAfghanMTNChargeDocumentsIntegratedCommand)(nil),                  // 12: BuyAfghanMTN.AddAccountingBuyAfghanMTNChargeDocumentsIntegratedCommand
	(*AddAccountingBuyAfghanMTNChargeDocumentsResponseIntegratedCommand)(nil),          // 13: BuyAfghanMTN.AddAccountingBuyAfghanMTNChargeDocumentsResponseIntegratedCommand
	(*AfghanMTNCheckCustomerActivationIntegratedCommand)(nil),                          // 14: BuyAfghanMTN.AfghanMTNCheckCustomerActivationIntegratedCommand
	(*common.Failure)(nil),                    // 15: Common.Failure
	(*common.Money)(nil),                      // 16: Common.Money
	(*common.CreditReductionMetaContext)(nil), // 17: Common.CreditReductionMetaContext
	(*common.BuyChargeAccountingInfo)(nil),    // 18: Common.BuyChargeAccountingInfo
}
var file_BuyAfghanMTN_proto_depIdxs = []int32{
	15, // 0: BuyAfghanMTN.AfghanMTNCheckCustomerActivationResponseIntegratedCommand.Failure:type_name -> Common.Failure
	15, // 1: BuyAfghanMTN.AfghanMTNCheckManagerChargeActivationResponseIntegratedCommand.Failure:type_name -> Common.Failure
	15, // 2: BuyAfghanMTN.BuyAfghanMTNChargeByKarimyarResponseIntegratedCommand.Failure:type_name -> Common.Failure
	15, // 3: BuyAfghanMTN.BuyAfghanMTNChargeByNaqdinehResponseIntegratedCommand.Failure:type_name -> Common.Failure
	16, // 4: BuyAfghanMTN.BuyAfghanMTNChargeCreditReductionIntegratedCommand.Commission:type_name -> Common.Money
	16, // 5: BuyAfghanMTN.BuyAfghanMTNChargeCreditReductionIntegratedCommand.ExchangerDeductedMoney:type_name -> Common.Money
	15, // 6: BuyAfghanMTN.BuyAfghanMTNChargeCreditReductionResponseIntegratedCommand.Failure:type_name -> Common.Failure
	17, // 7: BuyAfghanMTN.CommitOrRollbackBuyAfghanMTNChargeCreditReductionIntegratedCommand.Context:type_name -> Common.CreditReductionMetaContext
	18, // 8: BuyAfghanMTN.AddAccountingBuyAfghanMTNChargeDocumentsIntegratedCommand.BuyChargeInfo:type_name -> Common.BuyChargeAccountingInfo
	15, // 9: BuyAfghanMTN.AddAccountingBuyAfghanMTNChargeDocumentsResponseIntegratedCommand.Failure:type_name -> Common.Failure
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_BuyAfghanMTN_proto_init() }
func file_BuyAfghanMTN_proto_init() {
	if File_BuyAfghanMTN_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_BuyAfghanMTN_proto_rawDesc), len(file_BuyAfghanMTN_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_BuyAfghanMTN_proto_goTypes,
		DependencyIndexes: file_BuyAfghanMTN_proto_depIdxs,
		MessageInfos:      file_BuyAfghanMTN_proto_msgTypes,
	}.Build()
	File_BuyAfghanMTN_proto = out.File
	file_BuyAfghanMTN_proto_goTypes = nil
	file_BuyAfghanMTN_proto_depIdxs = nil
}
