// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: BuyEtisalatInternet.proto

package BuyEtisalatInternet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "moneyx.golang.framework/integration/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuyEtisalatInternetIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=TransactionId,proto3" json:"TransactionId,omitempty"`
	PackageName   string                 `protobuf:"bytes,2,opt,name=PackageName,proto3" json:"PackageName,omitempty"`
	ChargeNumber  string                 `protobuf:"bytes,3,opt,name=ChargeNumber,proto3" json:"ChargeNumber,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,5,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyEtisalatInternetIntegratedCommand) Reset() {
	*x = BuyEtisalatInternetIntegratedCommand{}
	mi := &file_BuyEtisalatInternet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyEtisalatInternetIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyEtisalatInternetIntegratedCommand) ProtoMessage() {}

func (x *BuyEtisalatInternetIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyEtisalatInternet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyEtisalatInternetIntegratedCommand.ProtoReflect.Descriptor instead.
func (*BuyEtisalatInternetIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyEtisalatInternet_proto_rawDescGZIP(), []int{0}
}

func (x *BuyEtisalatInternetIntegratedCommand) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *BuyEtisalatInternetIntegratedCommand) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *BuyEtisalatInternetIntegratedCommand) GetChargeNumber() string {
	if x != nil {
		return x.ChargeNumber
	}
	return ""
}

func (x *BuyEtisalatInternetIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BuyEtisalatInternetIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BuyEtisalatInternetResponseIntegratedCommand struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	IsDone                   bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	Failure                  *common.Failure        `protobuf:"bytes,2,opt,name=Failure,proto3" json:"Failure,omitempty"`
	ServiceProviderRefNumber string                 `protobuf:"bytes,3,opt,name=ServiceProviderRefNumber,proto3" json:"ServiceProviderRefNumber,omitempty"`
	CorrelationId            string                 `protobuf:"bytes,4,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id                       string                 `protobuf:"bytes,5,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *BuyEtisalatInternetResponseIntegratedCommand) Reset() {
	*x = BuyEtisalatInternetResponseIntegratedCommand{}
	mi := &file_BuyEtisalatInternet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyEtisalatInternetResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyEtisalatInternetResponseIntegratedCommand) ProtoMessage() {}

func (x *BuyEtisalatInternetResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyEtisalatInternet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyEtisalatInternetResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*BuyEtisalatInternetResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyEtisalatInternet_proto_rawDescGZIP(), []int{1}
}

func (x *BuyEtisalatInternetResponseIntegratedCommand) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *BuyEtisalatInternetResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *BuyEtisalatInternetResponseIntegratedCommand) GetServiceProviderRefNumber() string {
	if x != nil {
		return x.ServiceProviderRefNumber
	}
	return ""
}

func (x *BuyEtisalatInternetResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BuyEtisalatInternetResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BuyEtisalatInternetCreditReductionIntegratedCommand struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	AccountId              string                 `protobuf:"bytes,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	PackageTitle           string                 `protobuf:"bytes,2,opt,name=PackageTitle,proto3" json:"PackageTitle,omitempty"`
	ChargeTransactionId    string                 `protobuf:"bytes,3,opt,name=ChargeTransactionId,proto3" json:"ChargeTransactionId,omitempty"`
	Commission             *common.Money          `protobuf:"bytes,4,opt,name=Commission,proto3" json:"Commission,omitempty"`
	ExchangerDeductedMoney *common.Money          `protobuf:"bytes,5,opt,name=ExchangerDeductedMoney,proto3" json:"ExchangerDeductedMoney,omitempty"`
	OperatorName           string                 `protobuf:"bytes,6,opt,name=OperatorName,proto3" json:"OperatorName,omitempty"`
	PhoneNumber            string                 `protobuf:"bytes,7,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	ManagerId              string                 `protobuf:"bytes,8,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId          string                 `protobuf:"bytes,9,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id                     string                 `protobuf:"bytes,10,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BuyEtisalatInternetCreditReductionIntegratedCommand) Reset() {
	*x = BuyEtisalatInternetCreditReductionIntegratedCommand{}
	mi := &file_BuyEtisalatInternet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyEtisalatInternetCreditReductionIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyEtisalatInternetCreditReductionIntegratedCommand) ProtoMessage() {}

func (x *BuyEtisalatInternetCreditReductionIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyEtisalatInternet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyEtisalatInternetCreditReductionIntegratedCommand.ProtoReflect.Descriptor instead.
func (*BuyEtisalatInternetCreditReductionIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyEtisalatInternet_proto_rawDescGZIP(), []int{2}
}

func (x *BuyEtisalatInternetCreditReductionIntegratedCommand) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *BuyEtisalatInternetCreditReductionIntegratedCommand) GetPackageTitle() string {
	if x != nil {
		return x.PackageTitle
	}
	return ""
}

func (x *BuyEtisalatInternetCreditReductionIntegratedCommand) GetChargeTransactionId() string {
	if x != nil {
		return x.ChargeTransactionId
	}
	return ""
}

func (x *BuyEtisalatInternetCreditReductionIntegratedCommand) GetCommission() *common.Money {
	if x != nil {
		return x.Commission
	}
	return nil
}

func (x *BuyEtisalatInternetCreditReductionIntegratedCommand) GetExchangerDeductedMoney() *common.Money {
	if x != nil {
		return x.ExchangerDeductedMoney
	}
	return nil
}

func (x *BuyEtisalatInternetCreditReductionIntegratedCommand) GetOperatorName() string {
	if x != nil {
		return x.OperatorName
	}
	return ""
}

func (x *BuyEtisalatInternetCreditReductionIntegratedCommand) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *BuyEtisalatInternetCreditReductionIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *BuyEtisalatInternetCreditReductionIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BuyEtisalatInternetCreditReductionIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BuyEtisalatInternetCreditReductionResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDone        bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=Failure,proto3" json:"Failure,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyEtisalatInternetCreditReductionResponseIntegratedCommand) Reset() {
	*x = BuyEtisalatInternetCreditReductionResponseIntegratedCommand{}
	mi := &file_BuyEtisalatInternet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyEtisalatInternetCreditReductionResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyEtisalatInternetCreditReductionResponseIntegratedCommand) ProtoMessage() {}

func (x *BuyEtisalatInternetCreditReductionResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyEtisalatInternet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyEtisalatInternetCreditReductionResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*BuyEtisalatInternetCreditReductionResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyEtisalatInternet_proto_rawDescGZIP(), []int{3}
}

func (x *BuyEtisalatInternetCreditReductionResponseIntegratedCommand) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *BuyEtisalatInternetCreditReductionResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *BuyEtisalatInternetCreditReductionResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BuyEtisalatInternetCreditReductionResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EtisalatInternetCheckCustomerActivationIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	ManagerId     string                 `protobuf:"bytes,3,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,5,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EtisalatInternetCheckCustomerActivationIntegratedCommand) Reset() {
	*x = EtisalatInternetCheckCustomerActivationIntegratedCommand{}
	mi := &file_BuyEtisalatInternet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtisalatInternetCheckCustomerActivationIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtisalatInternetCheckCustomerActivationIntegratedCommand) ProtoMessage() {}

func (x *EtisalatInternetCheckCustomerActivationIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyEtisalatInternet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtisalatInternetCheckCustomerActivationIntegratedCommand.ProtoReflect.Descriptor instead.
func (*EtisalatInternetCheckCustomerActivationIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyEtisalatInternet_proto_rawDescGZIP(), []int{4}
}

func (x *EtisalatInternetCheckCustomerActivationIntegratedCommand) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *EtisalatInternetCheckCustomerActivationIntegratedCommand) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *EtisalatInternetCheckCustomerActivationIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *EtisalatInternetCheckCustomerActivationIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *EtisalatInternetCheckCustomerActivationIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EtisalatInternetCheckCustomerActivationResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsEnable      bool                   `protobuf:"varint,1,opt,name=IsEnable,proto3" json:"IsEnable,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=CustomerId,proto3" json:"CustomerId,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,3,opt,name=Failure,proto3" json:"Failure,omitempty"`
	ManagerId     string                 `protobuf:"bytes,4,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EtisalatInternetCheckCustomerActivationResponseIntegratedCommand) Reset() {
	*x = EtisalatInternetCheckCustomerActivationResponseIntegratedCommand{}
	mi := &file_BuyEtisalatInternet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtisalatInternetCheckCustomerActivationResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtisalatInternetCheckCustomerActivationResponseIntegratedCommand) ProtoMessage() {}

func (x *EtisalatInternetCheckCustomerActivationResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyEtisalatInternet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtisalatInternetCheckCustomerActivationResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*EtisalatInternetCheckCustomerActivationResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyEtisalatInternet_proto_rawDescGZIP(), []int{5}
}

func (x *EtisalatInternetCheckCustomerActivationResponseIntegratedCommand) GetIsEnable() bool {
	if x != nil {
		return x.IsEnable
	}
	return false
}

func (x *EtisalatInternetCheckCustomerActivationResponseIntegratedCommand) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *EtisalatInternetCheckCustomerActivationResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *EtisalatInternetCheckCustomerActivationResponseIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *EtisalatInternetCheckCustomerActivationResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *EtisalatInternetCheckCustomerActivationResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EtisalatInternetCheckManagerChargeActivationIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManagerId     string                 `protobuf:"bytes,1,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EtisalatInternetCheckManagerChargeActivationIntegratedCommand) Reset() {
	*x = EtisalatInternetCheckManagerChargeActivationIntegratedCommand{}
	mi := &file_BuyEtisalatInternet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtisalatInternetCheckManagerChargeActivationIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtisalatInternetCheckManagerChargeActivationIntegratedCommand) ProtoMessage() {}

func (x *EtisalatInternetCheckManagerChargeActivationIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyEtisalatInternet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtisalatInternetCheckManagerChargeActivationIntegratedCommand.ProtoReflect.Descriptor instead.
func (*EtisalatInternetCheckManagerChargeActivationIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyEtisalatInternet_proto_rawDescGZIP(), []int{6}
}

func (x *EtisalatInternetCheckManagerChargeActivationIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *EtisalatInternetCheckManagerChargeActivationIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *EtisalatInternetCheckManagerChargeActivationIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EtisalatInternetCheckManagerChargeActivationResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsEnable      bool                   `protobuf:"varint,1,opt,name=IsEnable,proto3" json:"IsEnable,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=Failure,proto3" json:"Failure,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EtisalatInternetCheckManagerChargeActivationResponseIntegratedCommand) Reset() {
	*x = EtisalatInternetCheckManagerChargeActivationResponseIntegratedCommand{}
	mi := &file_BuyEtisalatInternet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtisalatInternetCheckManagerChargeActivationResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtisalatInternetCheckManagerChargeActivationResponseIntegratedCommand) ProtoMessage() {}

func (x *EtisalatInternetCheckManagerChargeActivationResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyEtisalatInternet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtisalatInternetCheckManagerChargeActivationResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*EtisalatInternetCheckManagerChargeActivationResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyEtisalatInternet_proto_rawDescGZIP(), []int{7}
}

func (x *EtisalatInternetCheckManagerChargeActivationResponseIntegratedCommand) GetIsEnable() bool {
	if x != nil {
		return x.IsEnable
	}
	return false
}

func (x *EtisalatInternetCheckManagerChargeActivationResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *EtisalatInternetCheckManagerChargeActivationResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *EtisalatInternetCheckManagerChargeActivationResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddAccountingBuyEtisalatInternetDocumentsIntegratedCommand struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	BuyChargeInfo *common.BuyChargeAccountingInfo `protobuf:"bytes,1,opt,name=BuyChargeInfo,proto3" json:"BuyChargeInfo,omitempty"`
	CustomerId    string                          `protobuf:"bytes,2,opt,name=CustomerId,proto3" json:"CustomerId,omitempty"`
	ManagerId     string                          `protobuf:"bytes,3,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId string                          `protobuf:"bytes,4,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                          `protobuf:"bytes,5,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAccountingBuyEtisalatInternetDocumentsIntegratedCommand) Reset() {
	*x = AddAccountingBuyEtisalatInternetDocumentsIntegratedCommand{}
	mi := &file_BuyEtisalatInternet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAccountingBuyEtisalatInternetDocumentsIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAccountingBuyEtisalatInternetDocumentsIntegratedCommand) ProtoMessage() {}

func (x *AddAccountingBuyEtisalatInternetDocumentsIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyEtisalatInternet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAccountingBuyEtisalatInternetDocumentsIntegratedCommand.ProtoReflect.Descriptor instead.
func (*AddAccountingBuyEtisalatInternetDocumentsIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyEtisalatInternet_proto_rawDescGZIP(), []int{8}
}

func (x *AddAccountingBuyEtisalatInternetDocumentsIntegratedCommand) GetBuyChargeInfo() *common.BuyChargeAccountingInfo {
	if x != nil {
		return x.BuyChargeInfo
	}
	return nil
}

func (x *AddAccountingBuyEtisalatInternetDocumentsIntegratedCommand) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *AddAccountingBuyEtisalatInternetDocumentsIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *AddAccountingBuyEtisalatInternetDocumentsIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AddAccountingBuyEtisalatInternetDocumentsIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddAccountingBuyEtisalatInternetDocumentsResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDone        bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=Failure,proto3" json:"Failure,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAccountingBuyEtisalatInternetDocumentsResponseIntegratedCommand) Reset() {
	*x = AddAccountingBuyEtisalatInternetDocumentsResponseIntegratedCommand{}
	mi := &file_BuyEtisalatInternet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAccountingBuyEtisalatInternetDocumentsResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAccountingBuyEtisalatInternetDocumentsResponseIntegratedCommand) ProtoMessage() {}

func (x *AddAccountingBuyEtisalatInternetDocumentsResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyEtisalatInternet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAccountingBuyEtisalatInternetDocumentsResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*AddAccountingBuyEtisalatInternetDocumentsResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyEtisalatInternet_proto_rawDescGZIP(), []int{9}
}

func (x *AddAccountingBuyEtisalatInternetDocumentsResponseIntegratedCommand) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *AddAccountingBuyEtisalatInternetDocumentsResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *AddAccountingBuyEtisalatInternetDocumentsResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AddAccountingBuyEtisalatInternetDocumentsResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CommitOrRollbackAddedBuyEtisalatInternetAccountingDocumentIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCommitted   bool                   `protobuf:"varint,1,opt,name=IsCommitted,proto3" json:"IsCommitted,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOrRollbackAddedBuyEtisalatInternetAccountingDocumentIntegratedCommand) Reset() {
	*x = CommitOrRollbackAddedBuyEtisalatInternetAccountingDocumentIntegratedCommand{}
	mi := &file_BuyEtisalatInternet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOrRollbackAddedBuyEtisalatInternetAccountingDocumentIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOrRollbackAddedBuyEtisalatInternetAccountingDocumentIntegratedCommand) ProtoMessage() {}

func (x *CommitOrRollbackAddedBuyEtisalatInternetAccountingDocumentIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyEtisalatInternet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOrRollbackAddedBuyEtisalatInternetAccountingDocumentIntegratedCommand.ProtoReflect.Descriptor instead.
func (*CommitOrRollbackAddedBuyEtisalatInternetAccountingDocumentIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyEtisalatInternet_proto_rawDescGZIP(), []int{10}
}

func (x *CommitOrRollbackAddedBuyEtisalatInternetAccountingDocumentIntegratedCommand) GetIsCommitted() bool {
	if x != nil {
		return x.IsCommitted
	}
	return false
}

func (x *CommitOrRollbackAddedBuyEtisalatInternetAccountingDocumentIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CommitOrRollbackAddedBuyEtisalatInternetAccountingDocumentIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CommitOrRollbackBuyEtisalatInternetCreditReductionIntegratedCommand struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	IsCommitted   bool                               `protobuf:"varint,1,opt,name=IsCommitted,proto3" json:"IsCommitted,omitempty"`
	Context       *common.CreditReductionMetaContext `protobuf:"bytes,2,opt,name=Context,proto3" json:"Context,omitempty"`
	CorrelationId string                             `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                             `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOrRollbackBuyEtisalatInternetCreditReductionIntegratedCommand) Reset() {
	*x = CommitOrRollbackBuyEtisalatInternetCreditReductionIntegratedCommand{}
	mi := &file_BuyEtisalatInternet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOrRollbackBuyEtisalatInternetCreditReductionIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOrRollbackBuyEtisalatInternetCreditReductionIntegratedCommand) ProtoMessage() {}

func (x *CommitOrRollbackBuyEtisalatInternetCreditReductionIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyEtisalatInternet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOrRollbackBuyEtisalatInternetCreditReductionIntegratedCommand.ProtoReflect.Descriptor instead.
func (*CommitOrRollbackBuyEtisalatInternetCreditReductionIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyEtisalatInternet_proto_rawDescGZIP(), []int{11}
}

func (x *CommitOrRollbackBuyEtisalatInternetCreditReductionIntegratedCommand) GetIsCommitted() bool {
	if x != nil {
		return x.IsCommitted
	}
	return false
}

func (x *CommitOrRollbackBuyEtisalatInternetCreditReductionIntegratedCommand) GetContext() *common.CreditReductionMetaContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CommitOrRollbackBuyEtisalatInternetCreditReductionIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CommitOrRollbackBuyEtisalatInternetCreditReductionIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_BuyEtisalatInternet_proto protoreflect.FileDescriptor

const file_BuyEtisalatInternet_proto_rawDesc = "" +
	"\n" +
	"\x19BuyEtisalatInternet.proto\x12\x13BuyEtisalatInternet\x1a\fCommon.proto\"\xc8\x01\n" +
	"$BuyEtisalatInternetIntegratedCommand\x12$\n" +
	"\rTransactionId\x18\x01 \x01(\tR\rTransactionId\x12 \n" +
	"\vPackageName\x18\x02 \x01(\tR\vPackageName\x12\"\n" +
	"\fChargeNumber\x18\x03 \x01(\tR\fChargeNumber\x12$\n" +
	"\rCorrelationId\x18\x04 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x05 \x01(\tR\x02Id\"\xe3\x01\n" +
	",BuyEtisalatInternetResponseIntegratedCommand\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12)\n" +
	"\aFailure\x18\x02 \x01(\v2\x0f.Common.FailureR\aFailure\x12:\n" +
	"\x18ServiceProviderRefNumber\x18\x03 \x01(\tR\x18ServiceProviderRefNumber\x12$\n" +
	"\rCorrelationId\x18\x04 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x05 \x01(\tR\x02Id\"\xb9\x03\n" +
	"3BuyEtisalatInternetCreditReductionIntegratedCommand\x12\x1c\n" +
	"\tAccountId\x18\x01 \x01(\tR\tAccountId\x12\"\n" +
	"\fPackageTitle\x18\x02 \x01(\tR\fPackageTitle\x120\n" +
	"\x13ChargeTransactionId\x18\x03 \x01(\tR\x13ChargeTransactionId\x12-\n" +
	"\n" +
	"Commission\x18\x04 \x01(\v2\r.Common.MoneyR\n" +
	"Commission\x12E\n" +
	"\x16ExchangerDeductedMoney\x18\x05 \x01(\v2\r.Common.MoneyR\x16ExchangerDeductedMoney\x12\"\n" +
	"\fOperatorName\x18\x06 \x01(\tR\fOperatorName\x12 \n" +
	"\vPhoneNumber\x18\a \x01(\tR\vPhoneNumber\x12\x1c\n" +
	"\tManagerId\x18\b \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\t \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\n" +
	" \x01(\tR\x02Id\"\xb6\x01\n" +
	";BuyEtisalatInternetCreditReductionResponseIntegratedCommand\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12)\n" +
	"\aFailure\x18\x02 \x01(\v2\x0f.Common.FailureR\aFailure\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\xc8\x01\n" +
	"8EtisalatInternetCheckCustomerActivationIntegratedCommand\x12\x1a\n" +
	"\bUserName\x18\x01 \x01(\tR\bUserName\x12\x1c\n" +
	"\tAccountId\x18\x02 \x01(\tR\tAccountId\x12\x1c\n" +
	"\tManagerId\x18\x03 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x04 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x05 \x01(\tR\x02Id\"\xfd\x01\n" +
	"@EtisalatInternetCheckCustomerActivationResponseIntegratedCommand\x12\x1a\n" +
	"\bIsEnable\x18\x01 \x01(\bR\bIsEnable\x12\x1e\n" +
	"\n" +
	"CustomerId\x18\x02 \x01(\tR\n" +
	"CustomerId\x12)\n" +
	"\aFailure\x18\x03 \x01(\v2\x0f.Common.FailureR\aFailure\x12\x1c\n" +
	"\tManagerId\x18\x04 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x05 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x06 \x01(\tR\x02Id\"\x93\x01\n" +
	"=EtisalatInternetCheckManagerChargeActivationIntegratedCommand\x12\x1c\n" +
	"\tManagerId\x18\x01 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x02 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x03 \x01(\tR\x02Id\"\xc4\x01\n" +
	"EEtisalatInternetCheckManagerChargeActivationResponseIntegratedCommand\x12\x1a\n" +
	"\bIsEnable\x18\x01 \x01(\bR\bIsEnable\x12)\n" +
	"\aFailure\x18\x02 \x01(\v2\x0f.Common.FailureR\aFailure\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\xf7\x01\n" +
	":AddAccountingBuyEtisalatInternetDocumentsIntegratedCommand\x12E\n" +
	"\rBuyChargeInfo\x18\x01 \x01(\v2\x1f.Common.BuyChargeAccountingInfoR\rBuyChargeInfo\x12\x1e\n" +
	"\n" +
	"CustomerId\x18\x02 \x01(\tR\n" +
	"CustomerId\x12\x1c\n" +
	"\tManagerId\x18\x03 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x04 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x05 \x01(\tR\x02Id\"\xbd\x01\n" +
	"BAddAccountingBuyEtisalatInternetDocumentsResponseIntegratedCommand\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12)\n" +
	"\aFailure\x18\x02 \x01(\v2\x0f.Common.FailureR\aFailure\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\xa5\x01\n" +
	"KCommitOrRollbackAddedBuyEtisalatInternetAccountingDocumentIntegratedCommand\x12 \n" +
	"\vIsCommitted\x18\x01 \x01(\bR\vIsCommitted\x12$\n" +
	"\rCorrelationId\x18\x02 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x03 \x01(\tR\x02Id\"\xdb\x01\n" +
	"CCommitOrRollbackBuyEtisalatInternetCreditReductionIntegratedCommand\x12 \n" +
	"\vIsCommitted\x18\x01 \x01(\bR\vIsCommitted\x12<\n" +
	"\aContext\x18\x02 \x01(\v2\".Common.CreditReductionMetaContextR\aContext\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02IdBhZ7moneyx.golang.framework/integration/BuyEtisalatInternet\xaa\x02,Ariyana.Framework.Schema.BuyEtisalatInternetb\x06proto3"

var (
	file_BuyEtisalatInternet_proto_rawDescOnce sync.Once
	file_BuyEtisalatInternet_proto_rawDescData []byte
)

func file_BuyEtisalatInternet_proto_rawDescGZIP() []byte {
	file_BuyEtisalatInternet_proto_rawDescOnce.Do(func() {
		file_BuyEtisalatInternet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_BuyEtisalatInternet_proto_rawDesc), len(file_BuyEtisalatInternet_proto_rawDesc)))
	})
	return file_BuyEtisalatInternet_proto_rawDescData
}

var file_BuyEtisalatInternet_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_BuyEtisalatInternet_proto_goTypes = []any{
	(*BuyEtisalatInternetIntegratedCommand)(nil),                                        // 0: BuyEtisalatInternet.BuyEtisalatInternetIntegratedCommand
	(*BuyEtisalatInternetResponseIntegratedCommand)(nil),                                // 1: BuyEtisalatInternet.BuyEtisalatInternetResponseIntegratedCommand
	(*BuyEtisalatInternetCreditReductionIntegratedCommand)(nil),                         // 2: BuyEtisalatInternet.BuyEtisalatInternetCreditReductionIntegratedCommand
	(*BuyEtisalatInternetCreditReductionResponseIntegratedCommand)(nil),                 // 3: BuyEtisalatInternet.BuyEtisalatInternetCreditReductionResponseIntegratedCommand
	(*EtisalatInternetCheckCustomerActivationIntegratedCommand)(nil),                    // 4: BuyEtisalatInternet.EtisalatInternetCheckCustomerActivationIntegratedCommand
	(*EtisalatInternetCheckCustomerActivationResponseIntegratedCommand)(nil),            // 5: BuyEtisalatInternet.EtisalatInternetCheckCustomerActivationResponseIntegratedCommand
	(*EtisalatInternetCheckManagerChargeActivationIntegratedCommand)(nil),               // 6: BuyEtisalatInternet.EtisalatInternetCheckManagerChargeActivationIntegratedCommand
	(*EtisalatInternetCheckManagerChargeActivationResponseIntegratedCommand)(nil),       // 7: BuyEtisalatInternet.EtisalatInternetCheckManagerChargeActivationResponseIntegratedCommand
	(*AddAccountingBuyEtisalatInternetDocumentsIntegratedCommand)(nil),                  // 8: BuyEtisalatInternet.AddAccountingBuyEtisalatInternetDocumentsIntegratedCommand
	(*AddAccountingBuyEtisalatInternetDocumentsResponseIntegratedCommand)(nil),          // 9: BuyEtisalatInternet.AddAccountingBuyEtisalatInternetDocumentsResponseIntegratedCommand
	(*CommitOrRollbackAddedBuyEtisalatInternetAccountingDocumentIntegratedCommand)(nil), // 10: BuyEtisalatInternet.CommitOrRollbackAddedBuyEtisalatInternetAccountingDocumentIntegratedCommand
	(*CommitOrRollbackBuyEtisalatInternetCreditReductionIntegratedCommand)(nil),         // 11: BuyEtisalatInternet.CommitOrRollbackBuyEtisalatInternetCreditReductionIntegratedCommand
	(*common.Failure)(nil),                    // 12: Common.Failure
	(*common.Money)(nil),                      // 13: Common.Money
	(*common.BuyChargeAccountingInfo)(nil),    // 14: Common.BuyChargeAccountingInfo
	(*common.CreditReductionMetaContext)(nil), // 15: Common.CreditReductionMetaContext
}
var file_BuyEtisalatInternet_proto_depIdxs = []int32{
	12, // 0: BuyEtisalatInternet.BuyEtisalatInternetResponseIntegratedCommand.Failure:type_name -> Common.Failure
	13, // 1: BuyEtisalatInternet.BuyEtisalatInternetCreditReductionIntegratedCommand.Commission:type_name -> Common.Money
	13, // 2: BuyEtisalatInternet.BuyEtisalatInternetCreditReductionIntegratedCommand.ExchangerDeductedMoney:type_name -> Common.Money
	12, // 3: BuyEtisalatInternet.BuyEtisalatInternetCreditReductionResponseIntegratedCommand.Failure:type_name -> Common.Failure
	12, // 4: BuyEtisalatInternet.EtisalatInternetCheckCustomerActivationResponseIntegratedCommand.Failure:type_name -> Common.Failure
	12, // 5: BuyEtisalatInternet.EtisalatInternetCheckManagerChargeActivationResponseIntegratedCommand.Failure:type_name -> Common.Failure
	14, // 6: BuyEtisalatInternet.AddAccountingBuyEtisalatInternetDocumentsIntegratedCommand.BuyChargeInfo:type_name -> Common.BuyChargeAccountingInfo
	12, // 7: BuyEtisalatInternet.AddAccountingBuyEtisalatInternetDocumentsResponseIntegratedCommand.Failure:type_name -> Common.Failure
	15, // 8: BuyEtisalatInternet.CommitOrRollbackBuyEtisalatInternetCreditReductionIntegratedCommand.Context:type_name -> Common.CreditReductionMetaContext
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_BuyEtisalatInternet_proto_init() }
func file_BuyEtisalatInternet_proto_init() {
	if File_BuyEtisalatInternet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_BuyEtisalatInternet_proto_rawDesc), len(file_BuyEtisalatInternet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_BuyEtisalatInternet_proto_goTypes,
		DependencyIndexes: file_BuyEtisalatInternet_proto_depIdxs,
		MessageInfos:      file_BuyEtisalatInternet_proto_msgTypes,
	}.Build()
	File_BuyEtisalatInternet_proto = out.File
	file_BuyEtisalatInternet_proto_goTypes = nil
	file_BuyEtisalatInternet_proto_depIdxs = nil
}
