// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: AddFmcgOrder.proto

package AddFmcgOrder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RejectAddedFmcgOrderIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MizbanId      string                 `protobuf:"bytes,1,opt,name=MizbanId,proto3" json:"MizbanId,omitempty"`
	OrderId       int32                  `protobuf:"varint,2,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectAddedFmcgOrderIntegratedCommand) Reset() {
	*x = RejectAddedFmcgOrderIntegratedCommand{}
	mi := &file_AddFmcgOrder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectAddedFmcgOrderIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectAddedFmcgOrderIntegratedCommand) ProtoMessage() {}

func (x *RejectAddedFmcgOrderIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_AddFmcgOrder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectAddedFmcgOrderIntegratedCommand.ProtoReflect.Descriptor instead.
func (*RejectAddedFmcgOrderIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_AddFmcgOrder_proto_rawDescGZIP(), []int{0}
}

func (x *RejectAddedFmcgOrderIntegratedCommand) GetMizbanId() string {
	if x != nil {
		return x.MizbanId
	}
	return ""
}

func (x *RejectAddedFmcgOrderIntegratedCommand) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *RejectAddedFmcgOrderIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RejectAddedFmcgOrderIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RejectAddedFmcgOrderResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDone        bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectAddedFmcgOrderResponseIntegratedCommand) Reset() {
	*x = RejectAddedFmcgOrderResponseIntegratedCommand{}
	mi := &file_AddFmcgOrder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectAddedFmcgOrderResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectAddedFmcgOrderResponseIntegratedCommand) ProtoMessage() {}

func (x *RejectAddedFmcgOrderResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_AddFmcgOrder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectAddedFmcgOrderResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*RejectAddedFmcgOrderResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_AddFmcgOrder_proto_rawDescGZIP(), []int{1}
}

func (x *RejectAddedFmcgOrderResponseIntegratedCommand) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *RejectAddedFmcgOrderResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RejectAddedFmcgOrderResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_AddFmcgOrder_proto protoreflect.FileDescriptor

const file_AddFmcgOrder_proto_rawDesc = "" +
	"\n" +
	"\x12AddFmcgOrder.proto\x12\fAddFmcgOrder\"\x93\x01\n" +
	"%RejectAddedFmcgOrderIntegratedCommand\x12\x1a\n" +
	"\bMizbanId\x18\x01 \x01(\tR\bMizbanId\x12\x18\n" +
	"\aOrderId\x18\x02 \x01(\x05R\aOrderId\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"}\n" +
	"-RejectAddedFmcgOrderResponseIntegratedCommand\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12$\n" +
	"\rCorrelationId\x18\x02 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x03 \x01(\tR\x02IdBZZ0moneyx.golang.framework/integration/AddFmcgOrder\xaa\x02%Ariyana.Framework.Schema.AddFmcgOrderb\x06proto3"

var (
	file_AddFmcgOrder_proto_rawDescOnce sync.Once
	file_AddFmcgOrder_proto_rawDescData []byte
)

func file_AddFmcgOrder_proto_rawDescGZIP() []byte {
	file_AddFmcgOrder_proto_rawDescOnce.Do(func() {
		file_AddFmcgOrder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AddFmcgOrder_proto_rawDesc), len(file_AddFmcgOrder_proto_rawDesc)))
	})
	return file_AddFmcgOrder_proto_rawDescData
}

var file_AddFmcgOrder_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_AddFmcgOrder_proto_goTypes = []any{
	(*RejectAddedFmcgOrderIntegratedCommand)(nil),         // 0: AddFmcgOrder.RejectAddedFmcgOrderIntegratedCommand
	(*RejectAddedFmcgOrderResponseIntegratedCommand)(nil), // 1: AddFmcgOrder.RejectAddedFmcgOrderResponseIntegratedCommand
}
var file_AddFmcgOrder_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_AddFmcgOrder_proto_init() }
func file_AddFmcgOrder_proto_init() {
	if File_AddFmcgOrder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AddFmcgOrder_proto_rawDesc), len(file_AddFmcgOrder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AddFmcgOrder_proto_goTypes,
		DependencyIndexes: file_AddFmcgOrder_proto_depIdxs,
		MessageInfos:      file_AddFmcgOrder_proto_msgTypes,
	}.Build()
	File_AddFmcgOrder_proto = out.File
	file_AddFmcgOrder_proto_goTypes = nil
	file_AddFmcgOrder_proto_depIdxs = nil
}
