// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: AddBankCheckoutByIndex.proto

package AddBankCheckoutByIndex

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "moneyx.golang.framework/integration/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddBankCheckoutByIndexIntegratedCommand struct {
	state                protoimpl.MessageState    `protogen:"open.v1"`
	BankId               string                    `protobuf:"bytes,1,opt,name=BankId,proto3" json:"BankId,omitempty"`
	ArchiveDocumentsItem []*common.BankDocumentDto `protobuf:"bytes,2,rep,name=ArchiveDocumentsItem,proto3" json:"ArchiveDocumentsItem,omitempty"`
	CorrelationId        string                    `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id                   string                    `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AddBankCheckoutByIndexIntegratedCommand) Reset() {
	*x = AddBankCheckoutByIndexIntegratedCommand{}
	mi := &file_AddBankCheckoutByIndex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBankCheckoutByIndexIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBankCheckoutByIndexIntegratedCommand) ProtoMessage() {}

func (x *AddBankCheckoutByIndexIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_AddBankCheckoutByIndex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBankCheckoutByIndexIntegratedCommand.ProtoReflect.Descriptor instead.
func (*AddBankCheckoutByIndexIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_AddBankCheckoutByIndex_proto_rawDescGZIP(), []int{0}
}

func (x *AddBankCheckoutByIndexIntegratedCommand) GetBankId() string {
	if x != nil {
		return x.BankId
	}
	return ""
}

func (x *AddBankCheckoutByIndexIntegratedCommand) GetArchiveDocumentsItem() []*common.BankDocumentDto {
	if x != nil {
		return x.ArchiveDocumentsItem
	}
	return nil
}

func (x *AddBankCheckoutByIndexIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AddBankCheckoutByIndexIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddBankCheckoutByIndexResponseIntegratedCommand struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	BankResponseIsSuccessful bool                   `protobuf:"varint,1,opt,name=BankResponseIsSuccessful,proto3" json:"BankResponseIsSuccessful,omitempty"`
	Failure                  *common.Failure        `protobuf:"bytes,2,opt,name=Failure,proto3" json:"Failure,omitempty"`
	CorrelationId            string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id                       string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AddBankCheckoutByIndexResponseIntegratedCommand) Reset() {
	*x = AddBankCheckoutByIndexResponseIntegratedCommand{}
	mi := &file_AddBankCheckoutByIndex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBankCheckoutByIndexResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBankCheckoutByIndexResponseIntegratedCommand) ProtoMessage() {}

func (x *AddBankCheckoutByIndexResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_AddBankCheckoutByIndex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBankCheckoutByIndexResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*AddBankCheckoutByIndexResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_AddBankCheckoutByIndex_proto_rawDescGZIP(), []int{1}
}

func (x *AddBankCheckoutByIndexResponseIntegratedCommand) GetBankResponseIsSuccessful() bool {
	if x != nil {
		return x.BankResponseIsSuccessful
	}
	return false
}

func (x *AddBankCheckoutByIndexResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *AddBankCheckoutByIndexResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AddBankCheckoutByIndexResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CommitOrRollbackAddedBankCheckoutByIndexIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCommitted   bool                   `protobuf:"varint,1,opt,name=IsCommitted,proto3" json:"IsCommitted,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOrRollbackAddedBankCheckoutByIndexIntegratedCommand) Reset() {
	*x = CommitOrRollbackAddedBankCheckoutByIndexIntegratedCommand{}
	mi := &file_AddBankCheckoutByIndex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOrRollbackAddedBankCheckoutByIndexIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOrRollbackAddedBankCheckoutByIndexIntegratedCommand) ProtoMessage() {}

func (x *CommitOrRollbackAddedBankCheckoutByIndexIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_AddBankCheckoutByIndex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOrRollbackAddedBankCheckoutByIndexIntegratedCommand.ProtoReflect.Descriptor instead.
func (*CommitOrRollbackAddedBankCheckoutByIndexIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_AddBankCheckoutByIndex_proto_rawDescGZIP(), []int{2}
}

func (x *CommitOrRollbackAddedBankCheckoutByIndexIntegratedCommand) GetIsCommitted() bool {
	if x != nil {
		return x.IsCommitted
	}
	return false
}

func (x *CommitOrRollbackAddedBankCheckoutByIndexIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CommitOrRollbackAddedBankCheckoutByIndexIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_AddBankCheckoutByIndex_proto protoreflect.FileDescriptor

const file_AddBankCheckoutByIndex_proto_rawDesc = "" +
	"\n" +
	"\x1cAddBankCheckoutByIndex.proto\x12\x16AddBankCheckoutByIndex\x1a\fCommon.proto\"\xc4\x01\n" +
	"'AddBankCheckoutByIndexIntegratedCommand\x12\x16\n" +
	"\x06BankId\x18\x01 \x01(\tR\x06BankId\x12K\n" +
	"\x14ArchiveDocumentsItem\x18\x02 \x03(\v2\x17.Common.BankDocumentDtoR\x14ArchiveDocumentsItem\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\xce\x01\n" +
	"/AddBankCheckoutByIndexResponseIntegratedCommand\x12:\n" +
	"\x18BankResponseIsSuccessful\x18\x01 \x01(\bR\x18BankResponseIsSuccessful\x12)\n" +
	"\aFailure\x18\x02 \x01(\v2\x0f.Common.FailureR\aFailure\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\x93\x01\n" +
	"9CommitOrRollbackAddedBankCheckoutByIndexIntegratedCommand\x12 \n" +
	"\vIsCommitted\x18\x01 \x01(\bR\vIsCommitted\x12$\n" +
	"\rCorrelationId\x18\x02 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x03 \x01(\tR\x02IdBnZ:moneyx.golang.framework/integration/AddBankCheckoutByIndex\xaa\x02/Ariyana.Framework.Schema.AddBankCheckoutByIndexb\x06proto3"

var (
	file_AddBankCheckoutByIndex_proto_rawDescOnce sync.Once
	file_AddBankCheckoutByIndex_proto_rawDescData []byte
)

func file_AddBankCheckoutByIndex_proto_rawDescGZIP() []byte {
	file_AddBankCheckoutByIndex_proto_rawDescOnce.Do(func() {
		file_AddBankCheckoutByIndex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AddBankCheckoutByIndex_proto_rawDesc), len(file_AddBankCheckoutByIndex_proto_rawDesc)))
	})
	return file_AddBankCheckoutByIndex_proto_rawDescData
}

var file_AddBankCheckoutByIndex_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_AddBankCheckoutByIndex_proto_goTypes = []any{
	(*AddBankCheckoutByIndexIntegratedCommand)(nil),                   // 0: AddBankCheckoutByIndex.AddBankCheckoutByIndexIntegratedCommand
	(*AddBankCheckoutByIndexResponseIntegratedCommand)(nil),           // 1: AddBankCheckoutByIndex.AddBankCheckoutByIndexResponseIntegratedCommand
	(*CommitOrRollbackAddedBankCheckoutByIndexIntegratedCommand)(nil), // 2: AddBankCheckoutByIndex.CommitOrRollbackAddedBankCheckoutByIndexIntegratedCommand
	(*common.BankDocumentDto)(nil),                                    // 3: Common.BankDocumentDto
	(*common.Failure)(nil),                                            // 4: Common.Failure
}
var file_AddBankCheckoutByIndex_proto_depIdxs = []int32{
	3, // 0: AddBankCheckoutByIndex.AddBankCheckoutByIndexIntegratedCommand.ArchiveDocumentsItem:type_name -> Common.BankDocumentDto
	4, // 1: AddBankCheckoutByIndex.AddBankCheckoutByIndexResponseIntegratedCommand.Failure:type_name -> Common.Failure
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_AddBankCheckoutByIndex_proto_init() }
func file_AddBankCheckoutByIndex_proto_init() {
	if File_AddBankCheckoutByIndex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AddBankCheckoutByIndex_proto_rawDesc), len(file_AddBankCheckoutByIndex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AddBankCheckoutByIndex_proto_goTypes,
		DependencyIndexes: file_AddBankCheckoutByIndex_proto_depIdxs,
		MessageInfos:      file_AddBankCheckoutByIndex_proto_msgTypes,
	}.Build()
	File_AddBankCheckoutByIndex_proto = out.File
	file_AddBankCheckoutByIndex_proto_goTypes = nil
	file_AddBankCheckoutByIndex_proto_depIdxs = nil
}
