// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: DetermineDocumentWithAccountingTransaction.proto

package DetermineDocumentWithAccountingTransaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "moneyx.golang.framework/integration/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DetermineDocumentWithAccountingTransactionFilesIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*common.FileItem     `protobuf:"bytes,1,rep,name=Files,proto3" json:"Files,omitempty"`
	ManagerId     string                 `protobuf:"bytes,2,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetermineDocumentWithAccountingTransactionFilesIntegratedCommand) Reset() {
	*x = DetermineDocumentWithAccountingTransactionFilesIntegratedCommand{}
	mi := &file_DetermineDocumentWithAccountingTransaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetermineDocumentWithAccountingTransactionFilesIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetermineDocumentWithAccountingTransactionFilesIntegratedCommand) ProtoMessage() {}

func (x *DetermineDocumentWithAccountingTransactionFilesIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_DetermineDocumentWithAccountingTransaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetermineDocumentWithAccountingTransactionFilesIntegratedCommand.ProtoReflect.Descriptor instead.
func (*DetermineDocumentWithAccountingTransactionFilesIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_DetermineDocumentWithAccountingTransaction_proto_rawDescGZIP(), []int{0}
}

func (x *DetermineDocumentWithAccountingTransactionFilesIntegratedCommand) GetFiles() []*common.FileItem {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *DetermineDocumentWithAccountingTransactionFilesIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *DetermineDocumentWithAccountingTransactionFilesIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *DetermineDocumentWithAccountingTransactionFilesIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DetermineDocumentWithAccountingTransactionFilesResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	NewFileIds    []string               `protobuf:"bytes,2,rep,name=NewFileIds,proto3" json:"NewFileIds,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetermineDocumentWithAccountingTransactionFilesResponseIntegratedCommand) Reset() {
	*x = DetermineDocumentWithAccountingTransactionFilesResponseIntegratedCommand{}
	mi := &file_DetermineDocumentWithAccountingTransaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetermineDocumentWithAccountingTransactionFilesResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetermineDocumentWithAccountingTransactionFilesResponseIntegratedCommand) ProtoMessage() {}

func (x *DetermineDocumentWithAccountingTransactionFilesResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_DetermineDocumentWithAccountingTransaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetermineDocumentWithAccountingTransactionFilesResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*DetermineDocumentWithAccountingTransactionFilesResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_DetermineDocumentWithAccountingTransaction_proto_rawDescGZIP(), []int{1}
}

func (x *DetermineDocumentWithAccountingTransactionFilesResponseIntegratedCommand) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *DetermineDocumentWithAccountingTransactionFilesResponseIntegratedCommand) GetNewFileIds() []string {
	if x != nil {
		return x.NewFileIds
	}
	return nil
}

func (x *DetermineDocumentWithAccountingTransactionFilesResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *DetermineDocumentWithAccountingTransactionFilesResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RollbackDeterminedDocumentWithAccountingTransactionFilesIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackDeterminedDocumentWithAccountingTransactionFilesIntegratedCommand) Reset() {
	*x = RollbackDeterminedDocumentWithAccountingTransactionFilesIntegratedCommand{}
	mi := &file_DetermineDocumentWithAccountingTransaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackDeterminedDocumentWithAccountingTransactionFilesIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackDeterminedDocumentWithAccountingTransactionFilesIntegratedCommand) ProtoMessage() {}

func (x *RollbackDeterminedDocumentWithAccountingTransactionFilesIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_DetermineDocumentWithAccountingTransaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackDeterminedDocumentWithAccountingTransactionFilesIntegratedCommand.ProtoReflect.Descriptor instead.
func (*RollbackDeterminedDocumentWithAccountingTransactionFilesIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_DetermineDocumentWithAccountingTransaction_proto_rawDescGZIP(), []int{2}
}

func (x *RollbackDeterminedDocumentWithAccountingTransactionFilesIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RollbackDeterminedDocumentWithAccountingTransactionFilesIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_DetermineDocumentWithAccountingTransaction_proto protoreflect.FileDescriptor

const file_DetermineDocumentWithAccountingTransaction_proto_rawDesc = "" +
	"\n" +
	"0DetermineDocumentWithAccountingTransaction.proto\x12*DetermineDocumentWithAccountingTransaction\x1a\fCommon.proto\"\xbe\x01\n" +
	"@DetermineDocumentWithAccountingTransactionFilesIntegratedCommand\x12&\n" +
	"\x05Files\x18\x01 \x03(\v2\x10.Common.FileItemR\x05Files\x12\x1c\n" +
	"\tManagerId\x18\x02 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\xb8\x01\n" +
	"HDetermineDocumentWithAccountingTransactionFilesResponseIntegratedCommand\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\bR\x06Status\x12\x1e\n" +
	"\n" +
	"NewFileIds\x18\x02 \x03(\tR\n" +
	"NewFileIds\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\x81\x01\n" +
	"IRollbackDeterminedDocumentWithAccountingTransactionFilesIntegratedCommand\x12$\n" +
	"\rCorrelationId\x18\x01 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x02 \x01(\tR\x02IdB\x96\x01ZNmoneyx.golang.framework/integration/DetermineDocumentWithAccountingTransaction\xaa\x02CAriyana.Framework.Schema.DetermineDocumentWithAccountingTransactionb\x06proto3"

var (
	file_DetermineDocumentWithAccountingTransaction_proto_rawDescOnce sync.Once
	file_DetermineDocumentWithAccountingTransaction_proto_rawDescData []byte
)

func file_DetermineDocumentWithAccountingTransaction_proto_rawDescGZIP() []byte {
	file_DetermineDocumentWithAccountingTransaction_proto_rawDescOnce.Do(func() {
		file_DetermineDocumentWithAccountingTransaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_DetermineDocumentWithAccountingTransaction_proto_rawDesc), len(file_DetermineDocumentWithAccountingTransaction_proto_rawDesc)))
	})
	return file_DetermineDocumentWithAccountingTransaction_proto_rawDescData
}

var file_DetermineDocumentWithAccountingTransaction_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_DetermineDocumentWithAccountingTransaction_proto_goTypes = []any{
	(*DetermineDocumentWithAccountingTransactionFilesIntegratedCommand)(nil),          // 0: DetermineDocumentWithAccountingTransaction.DetermineDocumentWithAccountingTransactionFilesIntegratedCommand
	(*DetermineDocumentWithAccountingTransactionFilesResponseIntegratedCommand)(nil),  // 1: DetermineDocumentWithAccountingTransaction.DetermineDocumentWithAccountingTransactionFilesResponseIntegratedCommand
	(*RollbackDeterminedDocumentWithAccountingTransactionFilesIntegratedCommand)(nil), // 2: DetermineDocumentWithAccountingTransaction.RollbackDeterminedDocumentWithAccountingTransactionFilesIntegratedCommand
	(*common.FileItem)(nil), // 3: Common.FileItem
}
var file_DetermineDocumentWithAccountingTransaction_proto_depIdxs = []int32{
	3, // 0: DetermineDocumentWithAccountingTransaction.DetermineDocumentWithAccountingTransactionFilesIntegratedCommand.Files:type_name -> Common.FileItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_DetermineDocumentWithAccountingTransaction_proto_init() }
func file_DetermineDocumentWithAccountingTransaction_proto_init() {
	if File_DetermineDocumentWithAccountingTransaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_DetermineDocumentWithAccountingTransaction_proto_rawDesc), len(file_DetermineDocumentWithAccountingTransaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_DetermineDocumentWithAccountingTransaction_proto_goTypes,
		DependencyIndexes: file_DetermineDocumentWithAccountingTransaction_proto_depIdxs,
		MessageInfos:      file_DetermineDocumentWithAccountingTransaction_proto_msgTypes,
	}.Build()
	File_DetermineDocumentWithAccountingTransaction_proto = out.File
	file_DetermineDocumentWithAccountingTransaction_proto_goTypes = nil
	file_DetermineDocumentWithAccountingTransaction_proto_depIdxs = nil
}
