// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: EditAccountingTransaction.proto

package EditAccountingTransaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "moneyx.golang.framework/integration/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RollbackEditedAccountingTransactionFilesIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackEditedAccountingTransactionFilesIntegratedCommand) Reset() {
	*x = RollbackEditedAccountingTransactionFilesIntegratedCommand{}
	mi := &file_EditAccountingTransaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackEditedAccountingTransactionFilesIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackEditedAccountingTransactionFilesIntegratedCommand) ProtoMessage() {}

func (x *RollbackEditedAccountingTransactionFilesIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_EditAccountingTransaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackEditedAccountingTransactionFilesIntegratedCommand.ProtoReflect.Descriptor instead.
func (*RollbackEditedAccountingTransactionFilesIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_EditAccountingTransaction_proto_rawDescGZIP(), []int{0}
}

func (x *RollbackEditedAccountingTransactionFilesIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RollbackEditedAccountingTransactionFilesIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EditPayOrderReceiptResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDone        bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=Failure,proto3" json:"Failure,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditPayOrderReceiptResponseIntegratedCommand) Reset() {
	*x = EditPayOrderReceiptResponseIntegratedCommand{}
	mi := &file_EditAccountingTransaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditPayOrderReceiptResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditPayOrderReceiptResponseIntegratedCommand) ProtoMessage() {}

func (x *EditPayOrderReceiptResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_EditAccountingTransaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditPayOrderReceiptResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*EditPayOrderReceiptResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_EditAccountingTransaction_proto_rawDescGZIP(), []int{1}
}

func (x *EditPayOrderReceiptResponseIntegratedCommand) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *EditPayOrderReceiptResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *EditPayOrderReceiptResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *EditPayOrderReceiptResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EditPayOrderReceiptIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiptId     string                 `protobuf:"bytes,1,opt,name=ReceiptId,proto3" json:"ReceiptId,omitempty"`
	ReceiptMoney  *common.Money          `protobuf:"bytes,2,opt,name=ReceiptMoney,proto3" json:"ReceiptMoney,omitempty"`
	ManagerId     string                 `protobuf:"bytes,3,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,5,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditPayOrderReceiptIntegratedCommand) Reset() {
	*x = EditPayOrderReceiptIntegratedCommand{}
	mi := &file_EditAccountingTransaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditPayOrderReceiptIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditPayOrderReceiptIntegratedCommand) ProtoMessage() {}

func (x *EditPayOrderReceiptIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_EditAccountingTransaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditPayOrderReceiptIntegratedCommand.ProtoReflect.Descriptor instead.
func (*EditPayOrderReceiptIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_EditAccountingTransaction_proto_rawDescGZIP(), []int{2}
}

func (x *EditPayOrderReceiptIntegratedCommand) GetReceiptId() string {
	if x != nil {
		return x.ReceiptId
	}
	return ""
}

func (x *EditPayOrderReceiptIntegratedCommand) GetReceiptMoney() *common.Money {
	if x != nil {
		return x.ReceiptMoney
	}
	return nil
}

func (x *EditPayOrderReceiptIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *EditPayOrderReceiptIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *EditPayOrderReceiptIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EditAccountingTransactionFilesResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDone        bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	NewFileIds    []string               `protobuf:"bytes,2,rep,name=NewFileIds,proto3" json:"NewFileIds,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditAccountingTransactionFilesResponseIntegratedCommand) Reset() {
	*x = EditAccountingTransactionFilesResponseIntegratedCommand{}
	mi := &file_EditAccountingTransaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditAccountingTransactionFilesResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditAccountingTransactionFilesResponseIntegratedCommand) ProtoMessage() {}

func (x *EditAccountingTransactionFilesResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_EditAccountingTransaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditAccountingTransactionFilesResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*EditAccountingTransactionFilesResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_EditAccountingTransaction_proto_rawDescGZIP(), []int{3}
}

func (x *EditAccountingTransactionFilesResponseIntegratedCommand) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *EditAccountingTransactionFilesResponseIntegratedCommand) GetNewFileIds() []string {
	if x != nil {
		return x.NewFileIds
	}
	return nil
}

func (x *EditAccountingTransactionFilesResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *EditAccountingTransactionFilesResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EditAccountingTransactionFilesIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedFiles  []string               `protobuf:"bytes,1,rep,name=DeletedFiles,proto3" json:"DeletedFiles,omitempty"`
	CreatedFiles  []*common.FileItem     `protobuf:"bytes,2,rep,name=CreatedFiles,proto3" json:"CreatedFiles,omitempty"`
	ManagerId     string                 `protobuf:"bytes,3,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,5,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditAccountingTransactionFilesIntegratedCommand) Reset() {
	*x = EditAccountingTransactionFilesIntegratedCommand{}
	mi := &file_EditAccountingTransaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditAccountingTransactionFilesIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditAccountingTransactionFilesIntegratedCommand) ProtoMessage() {}

func (x *EditAccountingTransactionFilesIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_EditAccountingTransaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditAccountingTransactionFilesIntegratedCommand.ProtoReflect.Descriptor instead.
func (*EditAccountingTransactionFilesIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_EditAccountingTransaction_proto_rawDescGZIP(), []int{4}
}

func (x *EditAccountingTransactionFilesIntegratedCommand) GetDeletedFiles() []string {
	if x != nil {
		return x.DeletedFiles
	}
	return nil
}

func (x *EditAccountingTransactionFilesIntegratedCommand) GetCreatedFiles() []*common.FileItem {
	if x != nil {
		return x.CreatedFiles
	}
	return nil
}

func (x *EditAccountingTransactionFilesIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *EditAccountingTransactionFilesIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *EditAccountingTransactionFilesIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CommitOrRollbackEditedPayOrderIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCommited    bool                   `protobuf:"varint,1,opt,name=IsCommited,proto3" json:"IsCommited,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOrRollbackEditedPayOrderIntegratedCommand) Reset() {
	*x = CommitOrRollbackEditedPayOrderIntegratedCommand{}
	mi := &file_EditAccountingTransaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOrRollbackEditedPayOrderIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOrRollbackEditedPayOrderIntegratedCommand) ProtoMessage() {}

func (x *CommitOrRollbackEditedPayOrderIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_EditAccountingTransaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOrRollbackEditedPayOrderIntegratedCommand.ProtoReflect.Descriptor instead.
func (*CommitOrRollbackEditedPayOrderIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_EditAccountingTransaction_proto_rawDescGZIP(), []int{5}
}

func (x *CommitOrRollbackEditedPayOrderIntegratedCommand) GetIsCommited() bool {
	if x != nil {
		return x.IsCommited
	}
	return false
}

func (x *CommitOrRollbackEditedPayOrderIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CommitOrRollbackEditedPayOrderIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_EditAccountingTransaction_proto protoreflect.FileDescriptor

const file_EditAccountingTransaction_proto_rawDesc = "" +
	"\n" +
	"\x1fEditAccountingTransaction.proto\x12\x19EditAccountingTransaction\x1a\fCommon.proto\"q\n" +
	"9RollbackEditedAccountingTransactionFilesIntegratedCommand\x12$\n" +
	"\rCorrelationId\x18\x01 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x02 \x01(\tR\x02Id\"\xa7\x01\n" +
	",EditPayOrderReceiptResponseIntegratedCommand\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12)\n" +
	"\aFailure\x18\x02 \x01(\v2\x0f.Common.FailureR\aFailure\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\xcb\x01\n" +
	"$EditPayOrderReceiptIntegratedCommand\x12\x1c\n" +
	"\tReceiptId\x18\x01 \x01(\tR\tReceiptId\x121\n" +
	"\fReceiptMoney\x18\x02 \x01(\v2\r.Common.MoneyR\fReceiptMoney\x12\x1c\n" +
	"\tManagerId\x18\x03 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x04 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x05 \x01(\tR\x02Id\"\xa7\x01\n" +
	"7EditAccountingTransactionFilesResponseIntegratedCommand\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12\x1e\n" +
	"\n" +
	"NewFileIds\x18\x02 \x03(\tR\n" +
	"NewFileIds\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\xdf\x01\n" +
	"/EditAccountingTransactionFilesIntegratedCommand\x12\"\n" +
	"\fDeletedFiles\x18\x01 \x03(\tR\fDeletedFiles\x124\n" +
	"\fCreatedFiles\x18\x02 \x03(\v2\x10.Common.FileItemR\fCreatedFiles\x12\x1c\n" +
	"\tManagerId\x18\x03 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x04 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x05 \x01(\tR\x02Id\"\x87\x01\n" +
	"/CommitOrRollbackEditedPayOrderIntegratedCommand\x12\x1e\n" +
	"\n" +
	"IsCommited\x18\x01 \x01(\bR\n" +
	"IsCommited\x12$\n" +
	"\rCorrelationId\x18\x02 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x03 \x01(\tR\x02IdBtZ=moneyx.golang.framework/integration/EditAccountingTransaction\xaa\x022Ariyana.Framework.Schema.EditAccountingTransactionb\x06proto3"

var (
	file_EditAccountingTransaction_proto_rawDescOnce sync.Once
	file_EditAccountingTransaction_proto_rawDescData []byte
)

func file_EditAccountingTransaction_proto_rawDescGZIP() []byte {
	file_EditAccountingTransaction_proto_rawDescOnce.Do(func() {
		file_EditAccountingTransaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_EditAccountingTransaction_proto_rawDesc), len(file_EditAccountingTransaction_proto_rawDesc)))
	})
	return file_EditAccountingTransaction_proto_rawDescData
}

var file_EditAccountingTransaction_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_EditAccountingTransaction_proto_goTypes = []any{
	(*RollbackEditedAccountingTransactionFilesIntegratedCommand)(nil), // 0: EditAccountingTransaction.RollbackEditedAccountingTransactionFilesIntegratedCommand
	(*EditPayOrderReceiptResponseIntegratedCommand)(nil),              // 1: EditAccountingTransaction.EditPayOrderReceiptResponseIntegratedCommand
	(*EditPayOrderReceiptIntegratedCommand)(nil),                      // 2: EditAccountingTransaction.EditPayOrderReceiptIntegratedCommand
	(*EditAccountingTransactionFilesResponseIntegratedCommand)(nil),   // 3: EditAccountingTransaction.EditAccountingTransactionFilesResponseIntegratedCommand
	(*EditAccountingTransactionFilesIntegratedCommand)(nil),           // 4: EditAccountingTransaction.EditAccountingTransactionFilesIntegratedCommand
	(*CommitOrRollbackEditedPayOrderIntegratedCommand)(nil),           // 5: EditAccountingTransaction.CommitOrRollbackEditedPayOrderIntegratedCommand
	(*common.Failure)(nil),  // 6: Common.Failure
	(*common.Money)(nil),    // 7: Common.Money
	(*common.FileItem)(nil), // 8: Common.FileItem
}
var file_EditAccountingTransaction_proto_depIdxs = []int32{
	6, // 0: EditAccountingTransaction.EditPayOrderReceiptResponseIntegratedCommand.Failure:type_name -> Common.Failure
	7, // 1: EditAccountingTransaction.EditPayOrderReceiptIntegratedCommand.ReceiptMoney:type_name -> Common.Money
	8, // 2: EditAccountingTransaction.EditAccountingTransactionFilesIntegratedCommand.CreatedFiles:type_name -> Common.FileItem
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_EditAccountingTransaction_proto_init() }
func file_EditAccountingTransaction_proto_init() {
	if File_EditAccountingTransaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_EditAccountingTransaction_proto_rawDesc), len(file_EditAccountingTransaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_EditAccountingTransaction_proto_goTypes,
		DependencyIndexes: file_EditAccountingTransaction_proto_depIdxs,
		MessageInfos:      file_EditAccountingTransaction_proto_msgTypes,
	}.Build()
	File_EditAccountingTransaction_proto = out.File
	file_EditAccountingTransaction_proto_goTypes = nil
	file_EditAccountingTransaction_proto_depIdxs = nil
}
