// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: ArchiveAccount.proto

package ArchiveAccount

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "moneyx.golang.framework/integration/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EditArchivedAccountCustomerIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=CustomerId,proto3" json:"CustomerId,omitempty"`
	ManagerId     string                 `protobuf:"bytes,3,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,5,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditArchivedAccountCustomerIntegratedCommand) Reset() {
	*x = EditArchivedAccountCustomerIntegratedCommand{}
	mi := &file_ArchiveAccount_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditArchivedAccountCustomerIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditArchivedAccountCustomerIntegratedCommand) ProtoMessage() {}

func (x *EditArchivedAccountCustomerIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_ArchiveAccount_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditArchivedAccountCustomerIntegratedCommand.ProtoReflect.Descriptor instead.
func (*EditArchivedAccountCustomerIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_ArchiveAccount_proto_rawDescGZIP(), []int{0}
}

func (x *EditArchivedAccountCustomerIntegratedCommand) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *EditArchivedAccountCustomerIntegratedCommand) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *EditArchivedAccountCustomerIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *EditArchivedAccountCustomerIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *EditArchivedAccountCustomerIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EditArchivedAccountCustomerResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDone        bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=Failure,proto3" json:"Failure,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditArchivedAccountCustomerResponseIntegratedCommand) Reset() {
	*x = EditArchivedAccountCustomerResponseIntegratedCommand{}
	mi := &file_ArchiveAccount_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditArchivedAccountCustomerResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditArchivedAccountCustomerResponseIntegratedCommand) ProtoMessage() {}

func (x *EditArchivedAccountCustomerResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_ArchiveAccount_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditArchivedAccountCustomerResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*EditArchivedAccountCustomerResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_ArchiveAccount_proto_rawDescGZIP(), []int{1}
}

func (x *EditArchivedAccountCustomerResponseIntegratedCommand) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *EditArchivedAccountCustomerResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *EditArchivedAccountCustomerResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *EditArchivedAccountCustomerResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CommitOrRollbackEditArchivedAccountCustomerResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCommited    bool                   `protobuf:"varint,1,opt,name=IsCommited,proto3" json:"IsCommited,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOrRollbackEditArchivedAccountCustomerResponseIntegratedCommand) Reset() {
	*x = CommitOrRollbackEditArchivedAccountCustomerResponseIntegratedCommand{}
	mi := &file_ArchiveAccount_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOrRollbackEditArchivedAccountCustomerResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOrRollbackEditArchivedAccountCustomerResponseIntegratedCommand) ProtoMessage() {}

func (x *CommitOrRollbackEditArchivedAccountCustomerResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_ArchiveAccount_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOrRollbackEditArchivedAccountCustomerResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*CommitOrRollbackEditArchivedAccountCustomerResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_ArchiveAccount_proto_rawDescGZIP(), []int{2}
}

func (x *CommitOrRollbackEditArchivedAccountCustomerResponseIntegratedCommand) GetIsCommited() bool {
	if x != nil {
		return x.IsCommited
	}
	return false
}

func (x *CommitOrRollbackEditArchivedAccountCustomerResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CommitOrRollbackEditArchivedAccountCustomerResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_ArchiveAccount_proto protoreflect.FileDescriptor

const file_ArchiveAccount_proto_rawDesc = "" +
	"\n" +
	"\x14ArchiveAccount.proto\x12\x0eArchiveAccount\x1a\fCommon.proto\"\xc0\x01\n" +
	",EditArchivedAccountCustomerIntegratedCommand\x12\x1c\n" +
	"\tAccountId\x18\x01 \x01(\tR\tAccountId\x12\x1e\n" +
	"\n" +
	"CustomerId\x18\x02 \x01(\tR\n" +
	"CustomerId\x12\x1c\n" +
	"\tManagerId\x18\x03 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x04 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x05 \x01(\tR\x02Id\"\xaf\x01\n" +
	"4EditArchivedAccountCustomerResponseIntegratedCommand\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12)\n" +
	"\aFailure\x18\x02 \x01(\v2\x0f.Common.FailureR\aFailure\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\x9c\x01\n" +
	"DCommitOrRollbackEditArchivedAccountCustomerResponseIntegratedCommand\x12\x1e\n" +
	"\n" +
	"IsCommited\x18\x01 \x01(\bR\n" +
	"IsCommited\x12$\n" +
	"\rCorrelationId\x18\x02 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x03 \x01(\tR\x02IdB^Z2moneyx.golang.framework/integration/ArchiveAccount\xaa\x02'Ariyana.Framework.Schema.ArchiveAccountb\x06proto3"

var (
	file_ArchiveAccount_proto_rawDescOnce sync.Once
	file_ArchiveAccount_proto_rawDescData []byte
)

func file_ArchiveAccount_proto_rawDescGZIP() []byte {
	file_ArchiveAccount_proto_rawDescOnce.Do(func() {
		file_ArchiveAccount_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ArchiveAccount_proto_rawDesc), len(file_ArchiveAccount_proto_rawDesc)))
	})
	return file_ArchiveAccount_proto_rawDescData
}

var file_ArchiveAccount_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ArchiveAccount_proto_goTypes = []any{
	(*EditArchivedAccountCustomerIntegratedCommand)(nil),                         // 0: ArchiveAccount.EditArchivedAccountCustomerIntegratedCommand
	(*EditArchivedAccountCustomerResponseIntegratedCommand)(nil),                 // 1: ArchiveAccount.EditArchivedAccountCustomerResponseIntegratedCommand
	(*CommitOrRollbackEditArchivedAccountCustomerResponseIntegratedCommand)(nil), // 2: ArchiveAccount.CommitOrRollbackEditArchivedAccountCustomerResponseIntegratedCommand
	(*common.Failure)(nil), // 3: Common.Failure
}
var file_ArchiveAccount_proto_depIdxs = []int32{
	3, // 0: ArchiveAccount.EditArchivedAccountCustomerResponseIntegratedCommand.Failure:type_name -> Common.Failure
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ArchiveAccount_proto_init() }
func file_ArchiveAccount_proto_init() {
	if File_ArchiveAccount_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ArchiveAccount_proto_rawDesc), len(file_ArchiveAccount_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ArchiveAccount_proto_goTypes,
		DependencyIndexes: file_ArchiveAccount_proto_depIdxs,
		MessageInfos:      file_ArchiveAccount_proto_msgTypes,
	}.Build()
	File_ArchiveAccount_proto = out.File
	file_ArchiveAccount_proto_goTypes = nil
	file_ArchiveAccount_proto_depIdxs = nil
}
