// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: JiraAnalyzer.proto

package JiraAnalyzer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssueItem int32

const (
	IssueItem_Invalid           IssueItem = 0
	IssueItem_FakeReport        IssueItem = 1
	IssueItem_FutureDevelopment IssueItem = 2
	IssueItem_ReadyToDeploy     IssueItem = 3
)

// Enum value maps for IssueItem.
var (
	IssueItem_name = map[int32]string{
		0: "Invalid",
		1: "FakeReport",
		2: "FutureDevelopment",
		3: "ReadyToDeploy",
	}
	IssueItem_value = map[string]int32{
		"Invalid":           0,
		"FakeReport":        1,
		"FutureDevelopment": 2,
		"ReadyToDeploy":     3,
	}
)

func (x IssueItem) Enum() *IssueItem {
	p := new(IssueItem)
	*p = x
	return p
}

func (x IssueItem) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IssueItem) Descriptor() protoreflect.EnumDescriptor {
	return file_JiraAnalyzer_proto_enumTypes[0].Descriptor()
}

func (IssueItem) Type() protoreflect.EnumType {
	return &file_JiraAnalyzer_proto_enumTypes[0]
}

func (x IssueItem) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IssueItem.Descriptor instead.
func (IssueItem) EnumDescriptor() ([]byte, []int) {
	return file_JiraAnalyzer_proto_rawDescGZIP(), []int{0}
}

type JiraAnalyzerStatusIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssueId       string                 `protobuf:"bytes,1,opt,name=IssueId,proto3" json:"IssueId,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	IssueType     IssueItem              `protobuf:"varint,3,opt,name=IssueType,proto3,enum=JiraAnalyzer.IssueItem" json:"IssueType,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,5,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JiraAnalyzerStatusIntegratedCommand) Reset() {
	*x = JiraAnalyzerStatusIntegratedCommand{}
	mi := &file_JiraAnalyzer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JiraAnalyzerStatusIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JiraAnalyzerStatusIntegratedCommand) ProtoMessage() {}

func (x *JiraAnalyzerStatusIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_JiraAnalyzer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JiraAnalyzerStatusIntegratedCommand.ProtoReflect.Descriptor instead.
func (*JiraAnalyzerStatusIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_JiraAnalyzer_proto_rawDescGZIP(), []int{0}
}

func (x *JiraAnalyzerStatusIntegratedCommand) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *JiraAnalyzerStatusIntegratedCommand) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *JiraAnalyzerStatusIntegratedCommand) GetIssueType() IssueItem {
	if x != nil {
		return x.IssueType
	}
	return IssueItem_Invalid
}

func (x *JiraAnalyzerStatusIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *JiraAnalyzerStatusIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_JiraAnalyzer_proto protoreflect.FileDescriptor

const file_JiraAnalyzer_proto_rawDesc = "" +
	"\n" +
	"\x12JiraAnalyzer.proto\x12\fJiraAnalyzer\"\xc6\x01\n" +
	"#JiraAnalyzerStatusIntegratedCommand\x12\x18\n" +
	"\aIssueId\x18\x01 \x01(\tR\aIssueId\x12\x18\n" +
	"\aContent\x18\x02 \x01(\tR\aContent\x125\n" +
	"\tIssueType\x18\x03 \x01(\x0e2\x17.JiraAnalyzer.IssueItemR\tIssueType\x12$\n" +
	"\rCorrelationId\x18\x04 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x05 \x01(\tR\x02Id*R\n" +
	"\tIssueItem\x12\v\n" +
	"\aInvalid\x10\x00\x12\x0e\n" +
	"\n" +
	"FakeReport\x10\x01\x12\x15\n" +
	"\x11FutureDevelopment\x10\x02\x12\x11\n" +
	"\rReadyToDeploy\x10\x03BZZ0moneyx.golang.framework/integration/JiraAnalyzer\xaa\x02%Ariyana.Framework.Schema.JiraAnalyzerb\x06proto3"

var (
	file_JiraAnalyzer_proto_rawDescOnce sync.Once
	file_JiraAnalyzer_proto_rawDescData []byte
)

func file_JiraAnalyzer_proto_rawDescGZIP() []byte {
	file_JiraAnalyzer_proto_rawDescOnce.Do(func() {
		file_JiraAnalyzer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_JiraAnalyzer_proto_rawDesc), len(file_JiraAnalyzer_proto_rawDesc)))
	})
	return file_JiraAnalyzer_proto_rawDescData
}

var file_JiraAnalyzer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_JiraAnalyzer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_JiraAnalyzer_proto_goTypes = []any{
	(IssueItem)(0), // 0: JiraAnalyzer.IssueItem
	(*JiraAnalyzerStatusIntegratedCommand)(nil), // 1: JiraAnalyzer.JiraAnalyzerStatusIntegratedCommand
}
var file_JiraAnalyzer_proto_depIdxs = []int32{
	0, // 0: JiraAnalyzer.JiraAnalyzerStatusIntegratedCommand.IssueType:type_name -> JiraAnalyzer.IssueItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_JiraAnalyzer_proto_init() }
func file_JiraAnalyzer_proto_init() {
	if File_JiraAnalyzer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_JiraAnalyzer_proto_rawDesc), len(file_JiraAnalyzer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_JiraAnalyzer_proto_goTypes,
		DependencyIndexes: file_JiraAnalyzer_proto_depIdxs,
		EnumInfos:         file_JiraAnalyzer_proto_enumTypes,
		MessageInfos:      file_JiraAnalyzer_proto_msgTypes,
	}.Build()
	File_JiraAnalyzer_proto = out.File
	file_JiraAnalyzer_proto_goTypes = nil
	file_JiraAnalyzer_proto_depIdxs = nil
}
