// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: BuyHamrahavalCharge.proto

package BuyHamrahavalCharge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "moneyx.golang.framework/integration/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuyHamrahavalChargeByMobtakeranIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AmountPackage float64                `protobuf:"fixed64,1,opt,name=AmountPackage,proto3" json:"AmountPackage,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=TransactionId,proto3" json:"TransactionId,omitempty"`
	ChargeNumber  string                 `protobuf:"bytes,3,opt,name=ChargeNumber,proto3" json:"ChargeNumber,omitempty"`
	PackageCode   string                 `protobuf:"bytes,4,opt,name=PackageCode,proto3" json:"PackageCode,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyHamrahavalChargeByMobtakeranIntegratedCommand) Reset() {
	*x = BuyHamrahavalChargeByMobtakeranIntegratedCommand{}
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyHamrahavalChargeByMobtakeranIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyHamrahavalChargeByMobtakeranIntegratedCommand) ProtoMessage() {}

func (x *BuyHamrahavalChargeByMobtakeranIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyHamrahavalChargeByMobtakeranIntegratedCommand.ProtoReflect.Descriptor instead.
func (*BuyHamrahavalChargeByMobtakeranIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyHamrahavalCharge_proto_rawDescGZIP(), []int{0}
}

func (x *BuyHamrahavalChargeByMobtakeranIntegratedCommand) GetAmountPackage() float64 {
	if x != nil {
		return x.AmountPackage
	}
	return 0
}

func (x *BuyHamrahavalChargeByMobtakeranIntegratedCommand) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *BuyHamrahavalChargeByMobtakeranIntegratedCommand) GetChargeNumber() string {
	if x != nil {
		return x.ChargeNumber
	}
	return ""
}

func (x *BuyHamrahavalChargeByMobtakeranIntegratedCommand) GetPackageCode() string {
	if x != nil {
		return x.PackageCode
	}
	return ""
}

func (x *BuyHamrahavalChargeByMobtakeranIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BuyHamrahavalChargeByMobtakeranIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BuyHamrahavalChargeByMobtakeranResponseIntegratedCommand struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	IsDone                   bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	Failure                  *common.Failure        `protobuf:"bytes,2,opt,name=Failure,proto3" json:"Failure,omitempty"`
	ServiceProviderRefNumber string                 `protobuf:"bytes,3,opt,name=ServiceProviderRefNumber,proto3" json:"ServiceProviderRefNumber,omitempty"`
	CorrelationId            string                 `protobuf:"bytes,4,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id                       string                 `protobuf:"bytes,5,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *BuyHamrahavalChargeByMobtakeranResponseIntegratedCommand) Reset() {
	*x = BuyHamrahavalChargeByMobtakeranResponseIntegratedCommand{}
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyHamrahavalChargeByMobtakeranResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyHamrahavalChargeByMobtakeranResponseIntegratedCommand) ProtoMessage() {}

func (x *BuyHamrahavalChargeByMobtakeranResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyHamrahavalChargeByMobtakeranResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*BuyHamrahavalChargeByMobtakeranResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyHamrahavalCharge_proto_rawDescGZIP(), []int{1}
}

func (x *BuyHamrahavalChargeByMobtakeranResponseIntegratedCommand) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *BuyHamrahavalChargeByMobtakeranResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *BuyHamrahavalChargeByMobtakeranResponseIntegratedCommand) GetServiceProviderRefNumber() string {
	if x != nil {
		return x.ServiceProviderRefNumber
	}
	return ""
}

func (x *BuyHamrahavalChargeByMobtakeranResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BuyHamrahavalChargeByMobtakeranResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BuyHamrahavalChargeByGhasedakIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AmountPackage float64                `protobuf:"fixed64,1,opt,name=AmountPackage,proto3" json:"AmountPackage,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=TransactionId,proto3" json:"TransactionId,omitempty"`
	ChargeNumber  string                 `protobuf:"bytes,3,opt,name=ChargeNumber,proto3" json:"ChargeNumber,omitempty"`
	PackageCode   string                 `protobuf:"bytes,4,opt,name=PackageCode,proto3" json:"PackageCode,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyHamrahavalChargeByGhasedakIntegratedCommand) Reset() {
	*x = BuyHamrahavalChargeByGhasedakIntegratedCommand{}
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyHamrahavalChargeByGhasedakIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyHamrahavalChargeByGhasedakIntegratedCommand) ProtoMessage() {}

func (x *BuyHamrahavalChargeByGhasedakIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyHamrahavalChargeByGhasedakIntegratedCommand.ProtoReflect.Descriptor instead.
func (*BuyHamrahavalChargeByGhasedakIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyHamrahavalCharge_proto_rawDescGZIP(), []int{2}
}

func (x *BuyHamrahavalChargeByGhasedakIntegratedCommand) GetAmountPackage() float64 {
	if x != nil {
		return x.AmountPackage
	}
	return 0
}

func (x *BuyHamrahavalChargeByGhasedakIntegratedCommand) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *BuyHamrahavalChargeByGhasedakIntegratedCommand) GetChargeNumber() string {
	if x != nil {
		return x.ChargeNumber
	}
	return ""
}

func (x *BuyHamrahavalChargeByGhasedakIntegratedCommand) GetPackageCode() string {
	if x != nil {
		return x.PackageCode
	}
	return ""
}

func (x *BuyHamrahavalChargeByGhasedakIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BuyHamrahavalChargeByGhasedakIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BuyHamrahavalChargeByGhasedakResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDone        bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=Failure,proto3" json:"Failure,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyHamrahavalChargeByGhasedakResponseIntegratedCommand) Reset() {
	*x = BuyHamrahavalChargeByGhasedakResponseIntegratedCommand{}
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyHamrahavalChargeByGhasedakResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyHamrahavalChargeByGhasedakResponseIntegratedCommand) ProtoMessage() {}

func (x *BuyHamrahavalChargeByGhasedakResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyHamrahavalChargeByGhasedakResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*BuyHamrahavalChargeByGhasedakResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyHamrahavalCharge_proto_rawDescGZIP(), []int{3}
}

func (x *BuyHamrahavalChargeByGhasedakResponseIntegratedCommand) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *BuyHamrahavalChargeByGhasedakResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *BuyHamrahavalChargeByGhasedakResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BuyHamrahavalChargeByGhasedakResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BuyHamrahavalChargeByEbtekarIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AmountPackage float64                `protobuf:"fixed64,1,opt,name=AmountPackage,proto3" json:"AmountPackage,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=TransactionId,proto3" json:"TransactionId,omitempty"`
	ChargeNumber  string                 `protobuf:"bytes,3,opt,name=ChargeNumber,proto3" json:"ChargeNumber,omitempty"`
	PackageCode   string                 `protobuf:"bytes,4,opt,name=PackageCode,proto3" json:"PackageCode,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyHamrahavalChargeByEbtekarIntegratedCommand) Reset() {
	*x = BuyHamrahavalChargeByEbtekarIntegratedCommand{}
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyHamrahavalChargeByEbtekarIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyHamrahavalChargeByEbtekarIntegratedCommand) ProtoMessage() {}

func (x *BuyHamrahavalChargeByEbtekarIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyHamrahavalChargeByEbtekarIntegratedCommand.ProtoReflect.Descriptor instead.
func (*BuyHamrahavalChargeByEbtekarIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyHamrahavalCharge_proto_rawDescGZIP(), []int{4}
}

func (x *BuyHamrahavalChargeByEbtekarIntegratedCommand) GetAmountPackage() float64 {
	if x != nil {
		return x.AmountPackage
	}
	return 0
}

func (x *BuyHamrahavalChargeByEbtekarIntegratedCommand) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *BuyHamrahavalChargeByEbtekarIntegratedCommand) GetChargeNumber() string {
	if x != nil {
		return x.ChargeNumber
	}
	return ""
}

func (x *BuyHamrahavalChargeByEbtekarIntegratedCommand) GetPackageCode() string {
	if x != nil {
		return x.PackageCode
	}
	return ""
}

func (x *BuyHamrahavalChargeByEbtekarIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BuyHamrahavalChargeByEbtekarIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BuyHamrahavalChargeByEbtekarResponseIntegratedCommand struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	IsDone                   bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	Failure                  *common.Failure        `protobuf:"bytes,2,opt,name=Failure,proto3" json:"Failure,omitempty"`
	ServiceProviderRefNumber string                 `protobuf:"bytes,3,opt,name=ServiceProviderRefNumber,proto3" json:"ServiceProviderRefNumber,omitempty"`
	CorrelationId            string                 `protobuf:"bytes,4,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id                       string                 `protobuf:"bytes,5,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *BuyHamrahavalChargeByEbtekarResponseIntegratedCommand) Reset() {
	*x = BuyHamrahavalChargeByEbtekarResponseIntegratedCommand{}
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyHamrahavalChargeByEbtekarResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyHamrahavalChargeByEbtekarResponseIntegratedCommand) ProtoMessage() {}

func (x *BuyHamrahavalChargeByEbtekarResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyHamrahavalChargeByEbtekarResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*BuyHamrahavalChargeByEbtekarResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyHamrahavalCharge_proto_rawDescGZIP(), []int{5}
}

func (x *BuyHamrahavalChargeByEbtekarResponseIntegratedCommand) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *BuyHamrahavalChargeByEbtekarResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *BuyHamrahavalChargeByEbtekarResponseIntegratedCommand) GetServiceProviderRefNumber() string {
	if x != nil {
		return x.ServiceProviderRefNumber
	}
	return ""
}

func (x *BuyHamrahavalChargeByEbtekarResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BuyHamrahavalChargeByEbtekarResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BuyHamrahavalChargeCreditReductionIntegratedCommand struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	AccountId              string                 `protobuf:"bytes,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	PackageTitle           string                 `protobuf:"bytes,2,opt,name=PackageTitle,proto3" json:"PackageTitle,omitempty"`
	ChargeTransactionId    string                 `protobuf:"bytes,3,opt,name=ChargeTransactionId,proto3" json:"ChargeTransactionId,omitempty"`
	Commission             *common.Money          `protobuf:"bytes,4,opt,name=Commission,proto3" json:"Commission,omitempty"`
	ExchangerDeductedMoney *common.Money          `protobuf:"bytes,5,opt,name=ExchangerDeductedMoney,proto3" json:"ExchangerDeductedMoney,omitempty"`
	OperatorName           string                 `protobuf:"bytes,6,opt,name=OperatorName,proto3" json:"OperatorName,omitempty"`
	PhoneNumber            string                 `protobuf:"bytes,7,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	ManagerId              string                 `protobuf:"bytes,8,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId          string                 `protobuf:"bytes,9,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id                     string                 `protobuf:"bytes,10,opt,name=Id,proto3" json:"Id,omitempty"`
	PackageConvertedPrice  *common.Money          `protobuf:"bytes,11,opt,name=PackageConvertedPrice,proto3" json:"PackageConvertedPrice,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BuyHamrahavalChargeCreditReductionIntegratedCommand) Reset() {
	*x = BuyHamrahavalChargeCreditReductionIntegratedCommand{}
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyHamrahavalChargeCreditReductionIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyHamrahavalChargeCreditReductionIntegratedCommand) ProtoMessage() {}

func (x *BuyHamrahavalChargeCreditReductionIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyHamrahavalChargeCreditReductionIntegratedCommand.ProtoReflect.Descriptor instead.
func (*BuyHamrahavalChargeCreditReductionIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyHamrahavalCharge_proto_rawDescGZIP(), []int{6}
}

func (x *BuyHamrahavalChargeCreditReductionIntegratedCommand) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *BuyHamrahavalChargeCreditReductionIntegratedCommand) GetPackageTitle() string {
	if x != nil {
		return x.PackageTitle
	}
	return ""
}

func (x *BuyHamrahavalChargeCreditReductionIntegratedCommand) GetChargeTransactionId() string {
	if x != nil {
		return x.ChargeTransactionId
	}
	return ""
}

func (x *BuyHamrahavalChargeCreditReductionIntegratedCommand) GetCommission() *common.Money {
	if x != nil {
		return x.Commission
	}
	return nil
}

func (x *BuyHamrahavalChargeCreditReductionIntegratedCommand) GetExchangerDeductedMoney() *common.Money {
	if x != nil {
		return x.ExchangerDeductedMoney
	}
	return nil
}

func (x *BuyHamrahavalChargeCreditReductionIntegratedCommand) GetOperatorName() string {
	if x != nil {
		return x.OperatorName
	}
	return ""
}

func (x *BuyHamrahavalChargeCreditReductionIntegratedCommand) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *BuyHamrahavalChargeCreditReductionIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *BuyHamrahavalChargeCreditReductionIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BuyHamrahavalChargeCreditReductionIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BuyHamrahavalChargeCreditReductionIntegratedCommand) GetPackageConvertedPrice() *common.Money {
	if x != nil {
		return x.PackageConvertedPrice
	}
	return nil
}

type BuyHamrahavalChargeCreditReductionResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDone        bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=Failure,proto3" json:"Failure,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyHamrahavalChargeCreditReductionResponseIntegratedCommand) Reset() {
	*x = BuyHamrahavalChargeCreditReductionResponseIntegratedCommand{}
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyHamrahavalChargeCreditReductionResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyHamrahavalChargeCreditReductionResponseIntegratedCommand) ProtoMessage() {}

func (x *BuyHamrahavalChargeCreditReductionResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyHamrahavalChargeCreditReductionResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*BuyHamrahavalChargeCreditReductionResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyHamrahavalCharge_proto_rawDescGZIP(), []int{7}
}

func (x *BuyHamrahavalChargeCreditReductionResponseIntegratedCommand) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *BuyHamrahavalChargeCreditReductionResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *BuyHamrahavalChargeCreditReductionResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BuyHamrahavalChargeCreditReductionResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CommitOrRollbackBuyHamrahavalChargeCreditReductionIntegratedCommand struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	IsCommitted   bool                               `protobuf:"varint,1,opt,name=IsCommitted,proto3" json:"IsCommitted,omitempty"`
	Context       *common.CreditReductionMetaContext `protobuf:"bytes,2,opt,name=Context,proto3" json:"Context,omitempty"`
	CorrelationId string                             `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                             `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOrRollbackBuyHamrahavalChargeCreditReductionIntegratedCommand) Reset() {
	*x = CommitOrRollbackBuyHamrahavalChargeCreditReductionIntegratedCommand{}
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOrRollbackBuyHamrahavalChargeCreditReductionIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOrRollbackBuyHamrahavalChargeCreditReductionIntegratedCommand) ProtoMessage() {}

func (x *CommitOrRollbackBuyHamrahavalChargeCreditReductionIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOrRollbackBuyHamrahavalChargeCreditReductionIntegratedCommand.ProtoReflect.Descriptor instead.
func (*CommitOrRollbackBuyHamrahavalChargeCreditReductionIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyHamrahavalCharge_proto_rawDescGZIP(), []int{8}
}

func (x *CommitOrRollbackBuyHamrahavalChargeCreditReductionIntegratedCommand) GetIsCommitted() bool {
	if x != nil {
		return x.IsCommitted
	}
	return false
}

func (x *CommitOrRollbackBuyHamrahavalChargeCreditReductionIntegratedCommand) GetContext() *common.CreditReductionMetaContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CommitOrRollbackBuyHamrahavalChargeCreditReductionIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CommitOrRollbackBuyHamrahavalChargeCreditReductionIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddAccountingBuyHamrahavalChargeDocumentsIntegratedCommand struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	BuyChargeInfo *common.BuyChargeAccountingInfo `protobuf:"bytes,1,opt,name=BuyChargeInfo,proto3" json:"BuyChargeInfo,omitempty"`
	CustomerId    string                          `protobuf:"bytes,2,opt,name=CustomerId,proto3" json:"CustomerId,omitempty"`
	ManagerId     string                          `protobuf:"bytes,3,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId string                          `protobuf:"bytes,4,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                          `protobuf:"bytes,5,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAccountingBuyHamrahavalChargeDocumentsIntegratedCommand) Reset() {
	*x = AddAccountingBuyHamrahavalChargeDocumentsIntegratedCommand{}
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAccountingBuyHamrahavalChargeDocumentsIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAccountingBuyHamrahavalChargeDocumentsIntegratedCommand) ProtoMessage() {}

func (x *AddAccountingBuyHamrahavalChargeDocumentsIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAccountingBuyHamrahavalChargeDocumentsIntegratedCommand.ProtoReflect.Descriptor instead.
func (*AddAccountingBuyHamrahavalChargeDocumentsIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyHamrahavalCharge_proto_rawDescGZIP(), []int{9}
}

func (x *AddAccountingBuyHamrahavalChargeDocumentsIntegratedCommand) GetBuyChargeInfo() *common.BuyChargeAccountingInfo {
	if x != nil {
		return x.BuyChargeInfo
	}
	return nil
}

func (x *AddAccountingBuyHamrahavalChargeDocumentsIntegratedCommand) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *AddAccountingBuyHamrahavalChargeDocumentsIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *AddAccountingBuyHamrahavalChargeDocumentsIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AddAccountingBuyHamrahavalChargeDocumentsIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddAccountingBuyHamrahavalChargeDocumentsResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDone        bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=Failure,proto3" json:"Failure,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAccountingBuyHamrahavalChargeDocumentsResponseIntegratedCommand) Reset() {
	*x = AddAccountingBuyHamrahavalChargeDocumentsResponseIntegratedCommand{}
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAccountingBuyHamrahavalChargeDocumentsResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAccountingBuyHamrahavalChargeDocumentsResponseIntegratedCommand) ProtoMessage() {}

func (x *AddAccountingBuyHamrahavalChargeDocumentsResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAccountingBuyHamrahavalChargeDocumentsResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*AddAccountingBuyHamrahavalChargeDocumentsResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyHamrahavalCharge_proto_rawDescGZIP(), []int{10}
}

func (x *AddAccountingBuyHamrahavalChargeDocumentsResponseIntegratedCommand) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *AddAccountingBuyHamrahavalChargeDocumentsResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *AddAccountingBuyHamrahavalChargeDocumentsResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AddAccountingBuyHamrahavalChargeDocumentsResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CommitOrRollbackAddedBuyHamrahavalChargeAccountingDocumentIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCommitted   bool                   `protobuf:"varint,1,opt,name=IsCommitted,proto3" json:"IsCommitted,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOrRollbackAddedBuyHamrahavalChargeAccountingDocumentIntegratedCommand) Reset() {
	*x = CommitOrRollbackAddedBuyHamrahavalChargeAccountingDocumentIntegratedCommand{}
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOrRollbackAddedBuyHamrahavalChargeAccountingDocumentIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOrRollbackAddedBuyHamrahavalChargeAccountingDocumentIntegratedCommand) ProtoMessage() {}

func (x *CommitOrRollbackAddedBuyHamrahavalChargeAccountingDocumentIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOrRollbackAddedBuyHamrahavalChargeAccountingDocumentIntegratedCommand.ProtoReflect.Descriptor instead.
func (*CommitOrRollbackAddedBuyHamrahavalChargeAccountingDocumentIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyHamrahavalCharge_proto_rawDescGZIP(), []int{11}
}

func (x *CommitOrRollbackAddedBuyHamrahavalChargeAccountingDocumentIntegratedCommand) GetIsCommitted() bool {
	if x != nil {
		return x.IsCommitted
	}
	return false
}

func (x *CommitOrRollbackAddedBuyHamrahavalChargeAccountingDocumentIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CommitOrRollbackAddedBuyHamrahavalChargeAccountingDocumentIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RollbackBuyHamrahavalChargeDocumentsIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackBuyHamrahavalChargeDocumentsIntegratedCommand) Reset() {
	*x = RollbackBuyHamrahavalChargeDocumentsIntegratedCommand{}
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackBuyHamrahavalChargeDocumentsIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackBuyHamrahavalChargeDocumentsIntegratedCommand) ProtoMessage() {}

func (x *RollbackBuyHamrahavalChargeDocumentsIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackBuyHamrahavalChargeDocumentsIntegratedCommand.ProtoReflect.Descriptor instead.
func (*RollbackBuyHamrahavalChargeDocumentsIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyHamrahavalCharge_proto_rawDescGZIP(), []int{12}
}

func (x *RollbackBuyHamrahavalChargeDocumentsIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RollbackBuyHamrahavalChargeDocumentsIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type HamrahavalCheckManagerChargeActivationIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManagerId     string                 `protobuf:"bytes,1,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HamrahavalCheckManagerChargeActivationIntegratedCommand) Reset() {
	*x = HamrahavalCheckManagerChargeActivationIntegratedCommand{}
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HamrahavalCheckManagerChargeActivationIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HamrahavalCheckManagerChargeActivationIntegratedCommand) ProtoMessage() {}

func (x *HamrahavalCheckManagerChargeActivationIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HamrahavalCheckManagerChargeActivationIntegratedCommand.ProtoReflect.Descriptor instead.
func (*HamrahavalCheckManagerChargeActivationIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyHamrahavalCharge_proto_rawDescGZIP(), []int{13}
}

func (x *HamrahavalCheckManagerChargeActivationIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *HamrahavalCheckManagerChargeActivationIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *HamrahavalCheckManagerChargeActivationIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type HamrahavalCheckManagerChargeActivationResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsEnable      bool                   `protobuf:"varint,1,opt,name=IsEnable,proto3" json:"IsEnable,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=Failure,proto3" json:"Failure,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HamrahavalCheckManagerChargeActivationResponseIntegratedCommand) Reset() {
	*x = HamrahavalCheckManagerChargeActivationResponseIntegratedCommand{}
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HamrahavalCheckManagerChargeActivationResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HamrahavalCheckManagerChargeActivationResponseIntegratedCommand) ProtoMessage() {}

func (x *HamrahavalCheckManagerChargeActivationResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HamrahavalCheckManagerChargeActivationResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*HamrahavalCheckManagerChargeActivationResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyHamrahavalCharge_proto_rawDescGZIP(), []int{14}
}

func (x *HamrahavalCheckManagerChargeActivationResponseIntegratedCommand) GetIsEnable() bool {
	if x != nil {
		return x.IsEnable
	}
	return false
}

func (x *HamrahavalCheckManagerChargeActivationResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *HamrahavalCheckManagerChargeActivationResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *HamrahavalCheckManagerChargeActivationResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type HamrahavalCheckCustomerActivationIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	ManagerId     string                 `protobuf:"bytes,3,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,5,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HamrahavalCheckCustomerActivationIntegratedCommand) Reset() {
	*x = HamrahavalCheckCustomerActivationIntegratedCommand{}
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HamrahavalCheckCustomerActivationIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HamrahavalCheckCustomerActivationIntegratedCommand) ProtoMessage() {}

func (x *HamrahavalCheckCustomerActivationIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HamrahavalCheckCustomerActivationIntegratedCommand.ProtoReflect.Descriptor instead.
func (*HamrahavalCheckCustomerActivationIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyHamrahavalCharge_proto_rawDescGZIP(), []int{15}
}

func (x *HamrahavalCheckCustomerActivationIntegratedCommand) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *HamrahavalCheckCustomerActivationIntegratedCommand) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *HamrahavalCheckCustomerActivationIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *HamrahavalCheckCustomerActivationIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *HamrahavalCheckCustomerActivationIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type HamrahavalCheckCustomerActivationResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsEnable      bool                   `protobuf:"varint,1,opt,name=IsEnable,proto3" json:"IsEnable,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=CustomerId,proto3" json:"CustomerId,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,3,opt,name=Failure,proto3" json:"Failure,omitempty"`
	ManagerId     string                 `protobuf:"bytes,4,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HamrahavalCheckCustomerActivationResponseIntegratedCommand) Reset() {
	*x = HamrahavalCheckCustomerActivationResponseIntegratedCommand{}
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HamrahavalCheckCustomerActivationResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HamrahavalCheckCustomerActivationResponseIntegratedCommand) ProtoMessage() {}

func (x *HamrahavalCheckCustomerActivationResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyHamrahavalCharge_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HamrahavalCheckCustomerActivationResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*HamrahavalCheckCustomerActivationResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyHamrahavalCharge_proto_rawDescGZIP(), []int{16}
}

func (x *HamrahavalCheckCustomerActivationResponseIntegratedCommand) GetIsEnable() bool {
	if x != nil {
		return x.IsEnable
	}
	return false
}

func (x *HamrahavalCheckCustomerActivationResponseIntegratedCommand) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *HamrahavalCheckCustomerActivationResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *HamrahavalCheckCustomerActivationResponseIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *HamrahavalCheckCustomerActivationResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *HamrahavalCheckCustomerActivationResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_BuyHamrahavalCharge_proto protoreflect.FileDescriptor

const file_BuyHamrahavalCharge_proto_rawDesc = "" +
	"\n" +
	"\x19BuyHamrahavalCharge.proto\x12\x13BuyHamrahavalCharge\x1a\fCommon.proto\"\xfa\x01\n" +
	"0BuyHamrahavalChargeByMobtakeranIntegratedCommand\x12$\n" +
	"\rAmountPackage\x18\x01 \x01(\x01R\rAmountPackage\x12$\n" +
	"\rTransactionId\x18\x02 \x01(\tR\rTransactionId\x12\"\n" +
	"\fChargeNumber\x18\x03 \x01(\tR\fChargeNumber\x12 \n" +
	"\vPackageCode\x18\x04 \x01(\tR\vPackageCode\x12$\n" +
	"\rCorrelationId\x18\x05 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x06 \x01(\tR\x02Id\"\xef\x01\n" +
	"8BuyHamrahavalChargeByMobtakeranResponseIntegratedCommand\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12)\n" +
	"\aFailure\x18\x02 \x01(\v2\x0f.Common.FailureR\aFailure\x12:\n" +
	"\x18ServiceProviderRefNumber\x18\x03 \x01(\tR\x18ServiceProviderRefNumber\x12$\n" +
	"\rCorrelationId\x18\x04 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x05 \x01(\tR\x02Id\"\xf8\x01\n" +
	".BuyHamrahavalChargeByGhasedakIntegratedCommand\x12$\n" +
	"\rAmountPackage\x18\x01 \x01(\x01R\rAmountPackage\x12$\n" +
	"\rTransactionId\x18\x02 \x01(\tR\rTransactionId\x12\"\n" +
	"\fChargeNumber\x18\x03 \x01(\tR\fChargeNumber\x12 \n" +
	"\vPackageCode\x18\x04 \x01(\tR\vPackageCode\x12$\n" +
	"\rCorrelationId\x18\x05 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x06 \x01(\tR\x02Id\"\xb1\x01\n" +
	"6BuyHamrahavalChargeByGhasedakResponseIntegratedCommand\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12)\n" +
	"\aFailure\x18\x02 \x01(\v2\x0f.Common.FailureR\aFailure\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\xf7\x01\n" +
	"-BuyHamrahavalChargeByEbtekarIntegratedCommand\x12$\n" +
	"\rAmountPackage\x18\x01 \x01(\x01R\rAmountPackage\x12$\n" +
	"\rTransactionId\x18\x02 \x01(\tR\rTransactionId\x12\"\n" +
	"\fChargeNumber\x18\x03 \x01(\tR\fChargeNumber\x12 \n" +
	"\vPackageCode\x18\x04 \x01(\tR\vPackageCode\x12$\n" +
	"\rCorrelationId\x18\x05 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x06 \x01(\tR\x02Id\"\xec\x01\n" +
	"5BuyHamrahavalChargeByEbtekarResponseIntegratedCommand\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12)\n" +
	"\aFailure\x18\x02 \x01(\v2\x0f.Common.FailureR\aFailure\x12:\n" +
	"\x18ServiceProviderRefNumber\x18\x03 \x01(\tR\x18ServiceProviderRefNumber\x12$\n" +
	"\rCorrelationId\x18\x04 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x05 \x01(\tR\x02Id\"\xfe\x03\n" +
	"3BuyHamrahavalChargeCreditReductionIntegratedCommand\x12\x1c\n" +
	"\tAccountId\x18\x01 \x01(\tR\tAccountId\x12\"\n" +
	"\fPackageTitle\x18\x02 \x01(\tR\fPackageTitle\x120\n" +
	"\x13ChargeTransactionId\x18\x03 \x01(\tR\x13ChargeTransactionId\x12-\n" +
	"\n" +
	"Commission\x18\x04 \x01(\v2\r.Common.MoneyR\n" +
	"Commission\x12E\n" +
	"\x16ExchangerDeductedMoney\x18\x05 \x01(\v2\r.Common.MoneyR\x16ExchangerDeductedMoney\x12\"\n" +
	"\fOperatorName\x18\x06 \x01(\tR\fOperatorName\x12 \n" +
	"\vPhoneNumber\x18\a \x01(\tR\vPhoneNumber\x12\x1c\n" +
	"\tManagerId\x18\b \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\t \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\n" +
	" \x01(\tR\x02Id\x12C\n" +
	"\x15PackageConvertedPrice\x18\v \x01(\v2\r.Common.MoneyR\x15PackageConvertedPrice\"\xb6\x01\n" +
	";BuyHamrahavalChargeCreditReductionResponseIntegratedCommand\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12)\n" +
	"\aFailure\x18\x02 \x01(\v2\x0f.Common.FailureR\aFailure\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\xdb\x01\n" +
	"CCommitOrRollbackBuyHamrahavalChargeCreditReductionIntegratedCommand\x12 \n" +
	"\vIsCommitted\x18\x01 \x01(\bR\vIsCommitted\x12<\n" +
	"\aContext\x18\x02 \x01(\v2\".Common.CreditReductionMetaContextR\aContext\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\xf7\x01\n" +
	":AddAccountingBuyHamrahavalChargeDocumentsIntegratedCommand\x12E\n" +
	"\rBuyChargeInfo\x18\x01 \x01(\v2\x1f.Common.BuyChargeAccountingInfoR\rBuyChargeInfo\x12\x1e\n" +
	"\n" +
	"CustomerId\x18\x02 \x01(\tR\n" +
	"CustomerId\x12\x1c\n" +
	"\tManagerId\x18\x03 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x04 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x05 \x01(\tR\x02Id\"\xbd\x01\n" +
	"BAddAccountingBuyHamrahavalChargeDocumentsResponseIntegratedCommand\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12)\n" +
	"\aFailure\x18\x02 \x01(\v2\x0f.Common.FailureR\aFailure\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\xa5\x01\n" +
	"KCommitOrRollbackAddedBuyHamrahavalChargeAccountingDocumentIntegratedCommand\x12 \n" +
	"\vIsCommitted\x18\x01 \x01(\bR\vIsCommitted\x12$\n" +
	"\rCorrelationId\x18\x02 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x03 \x01(\tR\x02Id\"m\n" +
	"5RollbackBuyHamrahavalChargeDocumentsIntegratedCommand\x12$\n" +
	"\rCorrelationId\x18\x01 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x02 \x01(\tR\x02Id\"\x8d\x01\n" +
	"7HamrahavalCheckManagerChargeActivationIntegratedCommand\x12\x1c\n" +
	"\tManagerId\x18\x01 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x02 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x03 \x01(\tR\x02Id\"\xbe\x01\n" +
	"?HamrahavalCheckManagerChargeActivationResponseIntegratedCommand\x12\x1a\n" +
	"\bIsEnable\x18\x01 \x01(\bR\bIsEnable\x12)\n" +
	"\aFailure\x18\x02 \x01(\v2\x0f.Common.FailureR\aFailure\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\xc2\x01\n" +
	"2HamrahavalCheckCustomerActivationIntegratedCommand\x12\x1a\n" +
	"\bUserName\x18\x01 \x01(\tR\bUserName\x12\x1c\n" +
	"\tAccountId\x18\x02 \x01(\tR\tAccountId\x12\x1c\n" +
	"\tManagerId\x18\x03 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x04 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x05 \x01(\tR\x02Id\"\xf7\x01\n" +
	":HamrahavalCheckCustomerActivationResponseIntegratedCommand\x12\x1a\n" +
	"\bIsEnable\x18\x01 \x01(\bR\bIsEnable\x12\x1e\n" +
	"\n" +
	"CustomerId\x18\x02 \x01(\tR\n" +
	"CustomerId\x12)\n" +
	"\aFailure\x18\x03 \x01(\v2\x0f.Common.FailureR\aFailure\x12\x1c\n" +
	"\tManagerId\x18\x04 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x05 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x06 \x01(\tR\x02IdBhZ7moneyx.golang.framework/integration/BuyHamrahavalCharge\xaa\x02,Ariyana.Framework.Schema.BuyHamrahavalChargeb\x06proto3"

var (
	file_BuyHamrahavalCharge_proto_rawDescOnce sync.Once
	file_BuyHamrahavalCharge_proto_rawDescData []byte
)

func file_BuyHamrahavalCharge_proto_rawDescGZIP() []byte {
	file_BuyHamrahavalCharge_proto_rawDescOnce.Do(func() {
		file_BuyHamrahavalCharge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_BuyHamrahavalCharge_proto_rawDesc), len(file_BuyHamrahavalCharge_proto_rawDesc)))
	})
	return file_BuyHamrahavalCharge_proto_rawDescData
}

var file_BuyHamrahavalCharge_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_BuyHamrahavalCharge_proto_goTypes = []any{
	(*BuyHamrahavalChargeByMobtakeranIntegratedCommand)(nil),                            // 0: BuyHamrahavalCharge.BuyHamrahavalChargeByMobtakeranIntegratedCommand
	(*BuyHamrahavalChargeByMobtakeranResponseIntegratedCommand)(nil),                    // 1: BuyHamrahavalCharge.BuyHamrahavalChargeByMobtakeranResponseIntegratedCommand
	(*BuyHamrahavalChargeByGhasedakIntegratedCommand)(nil),                              // 2: BuyHamrahavalCharge.BuyHamrahavalChargeByGhasedakIntegratedCommand
	(*BuyHamrahavalChargeByGhasedakResponseIntegratedCommand)(nil),                      // 3: BuyHamrahavalCharge.BuyHamrahavalChargeByGhasedakResponseIntegratedCommand
	(*BuyHamrahavalChargeByEbtekarIntegratedCommand)(nil),                               // 4: BuyHamrahavalCharge.BuyHamrahavalChargeByEbtekarIntegratedCommand
	(*BuyHamrahavalChargeByEbtekarResponseIntegratedCommand)(nil),                       // 5: BuyHamrahavalCharge.BuyHamrahavalChargeByEbtekarResponseIntegratedCommand
	(*BuyHamrahavalChargeCreditReductionIntegratedCommand)(nil),                         // 6: BuyHamrahavalCharge.BuyHamrahavalChargeCreditReductionIntegratedCommand
	(*BuyHamrahavalChargeCreditReductionResponseIntegratedCommand)(nil),                 // 7: BuyHamrahavalCharge.BuyHamrahavalChargeCreditReductionResponseIntegratedCommand
	(*CommitOrRollbackBuyHamrahavalChargeCreditReductionIntegratedCommand)(nil),         // 8: BuyHamrahavalCharge.CommitOrRollbackBuyHamrahavalChargeCreditReductionIntegratedCommand
	(*AddAccountingBuyHamrahavalChargeDocumentsIntegratedCommand)(nil),                  // 9: BuyHamrahavalCharge.AddAccountingBuyHamrahavalChargeDocumentsIntegratedCommand
	(*AddAccountingBuyHamrahavalChargeDocumentsResponseIntegratedCommand)(nil),          // 10: BuyHamrahavalCharge.AddAccountingBuyHamrahavalChargeDocumentsResponseIntegratedCommand
	(*CommitOrRollbackAddedBuyHamrahavalChargeAccountingDocumentIntegratedCommand)(nil), // 11: BuyHamrahavalCharge.CommitOrRollbackAddedBuyHamrahavalChargeAccountingDocumentIntegratedCommand
	(*RollbackBuyHamrahavalChargeDocumentsIntegratedCommand)(nil),                       // 12: BuyHamrahavalCharge.RollbackBuyHamrahavalChargeDocumentsIntegratedCommand
	(*HamrahavalCheckManagerChargeActivationIntegratedCommand)(nil),                     // 13: BuyHamrahavalCharge.HamrahavalCheckManagerChargeActivationIntegratedCommand
	(*HamrahavalCheckManagerChargeActivationResponseIntegratedCommand)(nil),             // 14: BuyHamrahavalCharge.HamrahavalCheckManagerChargeActivationResponseIntegratedCommand
	(*HamrahavalCheckCustomerActivationIntegratedCommand)(nil),                          // 15: BuyHamrahavalCharge.HamrahavalCheckCustomerActivationIntegratedCommand
	(*HamrahavalCheckCustomerActivationResponseIntegratedCommand)(nil),                  // 16: BuyHamrahavalCharge.HamrahavalCheckCustomerActivationResponseIntegratedCommand
	(*common.Failure)(nil),                    // 17: Common.Failure
	(*common.Money)(nil),                      // 18: Common.Money
	(*common.CreditReductionMetaContext)(nil), // 19: Common.CreditReductionMetaContext
	(*common.BuyChargeAccountingInfo)(nil),    // 20: Common.BuyChargeAccountingInfo
}
var file_BuyHamrahavalCharge_proto_depIdxs = []int32{
	17, // 0: BuyHamrahavalCharge.BuyHamrahavalChargeByMobtakeranResponseIntegratedCommand.Failure:type_name -> Common.Failure
	17, // 1: BuyHamrahavalCharge.BuyHamrahavalChargeByGhasedakResponseIntegratedCommand.Failure:type_name -> Common.Failure
	17, // 2: BuyHamrahavalCharge.BuyHamrahavalChargeByEbtekarResponseIntegratedCommand.Failure:type_name -> Common.Failure
	18, // 3: BuyHamrahavalCharge.BuyHamrahavalChargeCreditReductionIntegratedCommand.Commission:type_name -> Common.Money
	18, // 4: BuyHamrahavalCharge.BuyHamrahavalChargeCreditReductionIntegratedCommand.ExchangerDeductedMoney:type_name -> Common.Money
	18, // 5: BuyHamrahavalCharge.BuyHamrahavalChargeCreditReductionIntegratedCommand.PackageConvertedPrice:type_name -> Common.Money
	17, // 6: BuyHamrahavalCharge.BuyHamrahavalChargeCreditReductionResponseIntegratedCommand.Failure:type_name -> Common.Failure
	19, // 7: BuyHamrahavalCharge.CommitOrRollbackBuyHamrahavalChargeCreditReductionIntegratedCommand.Context:type_name -> Common.CreditReductionMetaContext
	20, // 8: BuyHamrahavalCharge.AddAccountingBuyHamrahavalChargeDocumentsIntegratedCommand.BuyChargeInfo:type_name -> Common.BuyChargeAccountingInfo
	17, // 9: BuyHamrahavalCharge.AddAccountingBuyHamrahavalChargeDocumentsResponseIntegratedCommand.Failure:type_name -> Common.Failure
	17, // 10: BuyHamrahavalCharge.HamrahavalCheckManagerChargeActivationResponseIntegratedCommand.Failure:type_name -> Common.Failure
	17, // 11: BuyHamrahavalCharge.HamrahavalCheckCustomerActivationResponseIntegratedCommand.Failure:type_name -> Common.Failure
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_BuyHamrahavalCharge_proto_init() }
func file_BuyHamrahavalCharge_proto_init() {
	if File_BuyHamrahavalCharge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_BuyHamrahavalCharge_proto_rawDesc), len(file_BuyHamrahavalCharge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_BuyHamrahavalCharge_proto_goTypes,
		DependencyIndexes: file_BuyHamrahavalCharge_proto_depIdxs,
		MessageInfos:      file_BuyHamrahavalCharge_proto_msgTypes,
	}.Build()
	File_BuyHamrahavalCharge_proto = out.File
	file_BuyHamrahavalCharge_proto_goTypes = nil
	file_BuyHamrahavalCharge_proto_depIdxs = nil
}
