// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: ContinueConversationForSupportTeam.proto

package ContinueConversationForSupportTeam

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "moneyx.golang.framework/integration/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RollbackContinuedConversationForSupportTeamFilesIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackContinuedConversationForSupportTeamFilesIntegratedCommand) Reset() {
	*x = RollbackContinuedConversationForSupportTeamFilesIntegratedCommand{}
	mi := &file_ContinueConversationForSupportTeam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackContinuedConversationForSupportTeamFilesIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackContinuedConversationForSupportTeamFilesIntegratedCommand) ProtoMessage() {}

func (x *RollbackContinuedConversationForSupportTeamFilesIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_ContinueConversationForSupportTeam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackContinuedConversationForSupportTeamFilesIntegratedCommand.ProtoReflect.Descriptor instead.
func (*RollbackContinuedConversationForSupportTeamFilesIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_ContinueConversationForSupportTeam_proto_rawDescGZIP(), []int{0}
}

func (x *RollbackContinuedConversationForSupportTeamFilesIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RollbackContinuedConversationForSupportTeamFilesIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ContinueConversationForSupportTeamFilesResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDone        bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	FileIds       []string               `protobuf:"bytes,2,rep,name=FileIds,proto3" json:"FileIds,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContinueConversationForSupportTeamFilesResponseIntegratedCommand) Reset() {
	*x = ContinueConversationForSupportTeamFilesResponseIntegratedCommand{}
	mi := &file_ContinueConversationForSupportTeam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinueConversationForSupportTeamFilesResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueConversationForSupportTeamFilesResponseIntegratedCommand) ProtoMessage() {}

func (x *ContinueConversationForSupportTeamFilesResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_ContinueConversationForSupportTeam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinueConversationForSupportTeamFilesResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*ContinueConversationForSupportTeamFilesResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_ContinueConversationForSupportTeam_proto_rawDescGZIP(), []int{1}
}

func (x *ContinueConversationForSupportTeamFilesResponseIntegratedCommand) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *ContinueConversationForSupportTeamFilesResponseIntegratedCommand) GetFileIds() []string {
	if x != nil {
		return x.FileIds
	}
	return nil
}

func (x *ContinueConversationForSupportTeamFilesResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ContinueConversationForSupportTeamFilesResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ContinueConversationForSupportTeamFilesIntegratedCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Files          []*common.FileItem     `protobuf:"bytes,1,rep,name=Files,proto3" json:"Files,omitempty"`
	ConversationId int32                  `protobuf:"varint,2,opt,name=ConversationId,proto3" json:"ConversationId,omitempty"`
	ManagerId      string                 `protobuf:"bytes,3,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId  string                 `protobuf:"bytes,4,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id             string                 `protobuf:"bytes,5,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContinueConversationForSupportTeamFilesIntegratedCommand) Reset() {
	*x = ContinueConversationForSupportTeamFilesIntegratedCommand{}
	mi := &file_ContinueConversationForSupportTeam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinueConversationForSupportTeamFilesIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueConversationForSupportTeamFilesIntegratedCommand) ProtoMessage() {}

func (x *ContinueConversationForSupportTeamFilesIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_ContinueConversationForSupportTeam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinueConversationForSupportTeamFilesIntegratedCommand.ProtoReflect.Descriptor instead.
func (*ContinueConversationForSupportTeamFilesIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_ContinueConversationForSupportTeam_proto_rawDescGZIP(), []int{2}
}

func (x *ContinueConversationForSupportTeamFilesIntegratedCommand) GetFiles() []*common.FileItem {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ContinueConversationForSupportTeamFilesIntegratedCommand) GetConversationId() int32 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *ContinueConversationForSupportTeamFilesIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *ContinueConversationForSupportTeamFilesIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ContinueConversationForSupportTeamFilesIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_ContinueConversationForSupportTeam_proto protoreflect.FileDescriptor

const file_ContinueConversationForSupportTeam_proto_rawDesc = "" +
	"\n" +
	"(ContinueConversationForSupportTeam.proto\x12\"ContinueConversationForSupportTeam\x1a\fCommon.proto\"y\n" +
	"ARollbackContinuedConversationForSupportTeamFilesIntegratedCommand\x12$\n" +
	"\rCorrelationId\x18\x01 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x02 \x01(\tR\x02Id\"\xaa\x01\n" +
	"@ContinueConversationForSupportTeamFilesResponseIntegratedCommand\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12\x18\n" +
	"\aFileIds\x18\x02 \x03(\tR\aFileIds\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\xde\x01\n" +
	"8ContinueConversationForSupportTeamFilesIntegratedCommand\x12&\n" +
	"\x05Files\x18\x01 \x03(\v2\x10.Common.FileItemR\x05Files\x12&\n" +
	"\x0eConversationId\x18\x02 \x01(\x05R\x0eConversationId\x12\x1c\n" +
	"\tManagerId\x18\x03 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x04 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x05 \x01(\tR\x02IdB\x86\x01ZFmoneyx.golang.framework/integration/ContinueConversationForSupportTeam\xaa\x02;Ariyana.Framework.Schema.ContinueConversationForSupportTeamb\x06proto3"

var (
	file_ContinueConversationForSupportTeam_proto_rawDescOnce sync.Once
	file_ContinueConversationForSupportTeam_proto_rawDescData []byte
)

func file_ContinueConversationForSupportTeam_proto_rawDescGZIP() []byte {
	file_ContinueConversationForSupportTeam_proto_rawDescOnce.Do(func() {
		file_ContinueConversationForSupportTeam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ContinueConversationForSupportTeam_proto_rawDesc), len(file_ContinueConversationForSupportTeam_proto_rawDesc)))
	})
	return file_ContinueConversationForSupportTeam_proto_rawDescData
}

var file_ContinueConversationForSupportTeam_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ContinueConversationForSupportTeam_proto_goTypes = []any{
	(*RollbackContinuedConversationForSupportTeamFilesIntegratedCommand)(nil), // 0: ContinueConversationForSupportTeam.RollbackContinuedConversationForSupportTeamFilesIntegratedCommand
	(*ContinueConversationForSupportTeamFilesResponseIntegratedCommand)(nil),  // 1: ContinueConversationForSupportTeam.ContinueConversationForSupportTeamFilesResponseIntegratedCommand
	(*ContinueConversationForSupportTeamFilesIntegratedCommand)(nil),          // 2: ContinueConversationForSupportTeam.ContinueConversationForSupportTeamFilesIntegratedCommand
	(*common.FileItem)(nil), // 3: Common.FileItem
}
var file_ContinueConversationForSupportTeam_proto_depIdxs = []int32{
	3, // 0: ContinueConversationForSupportTeam.ContinueConversationForSupportTeamFilesIntegratedCommand.Files:type_name -> Common.FileItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ContinueConversationForSupportTeam_proto_init() }
func file_ContinueConversationForSupportTeam_proto_init() {
	if File_ContinueConversationForSupportTeam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ContinueConversationForSupportTeam_proto_rawDesc), len(file_ContinueConversationForSupportTeam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ContinueConversationForSupportTeam_proto_goTypes,
		DependencyIndexes: file_ContinueConversationForSupportTeam_proto_depIdxs,
		MessageInfos:      file_ContinueConversationForSupportTeam_proto_msgTypes,
	}.Build()
	File_ContinueConversationForSupportTeam_proto = out.File
	file_ContinueConversationForSupportTeam_proto_goTypes = nil
	file_ContinueConversationForSupportTeam_proto_depIdxs = nil
}
