// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: AddOutsideIncomingDraftOrder.proto

package AddOutsideIncomingDraftOrder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "moneyx.golang.framework/integration/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddOutsideIncomingDraftOrderAccountingDocumentsIntegratedCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaymentPlace   string                 `protobuf:"bytes,1,opt,name=PaymentPlace,proto3" json:"PaymentPlace,omitempty"`
	PaymentPlaceId string                 `protobuf:"bytes,2,opt,name=PaymentPlaceId,proto3" json:"PaymentPlaceId,omitempty"`
	Money          *common.MoneyDocument  `protobuf:"bytes,3,opt,name=Money,proto3" json:"Money,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	SenderName     string                 `protobuf:"bytes,5,opt,name=SenderName,proto3" json:"SenderName,omitempty"`
	ReceiverName   string                 `protobuf:"bytes,6,opt,name=ReceiverName,proto3" json:"ReceiverName,omitempty"`
	DraftNumber    string                 `protobuf:"bytes,7,opt,name=DraftNumber,proto3" json:"DraftNumber,omitempty"`
	Date           int64                  `protobuf:"varint,8,opt,name=Date,proto3" json:"Date,omitempty"`
	BranchId       string                 `protobuf:"bytes,9,opt,name=BranchId,proto3" json:"BranchId,omitempty"`
	DraftOrderId   string                 `protobuf:"bytes,10,opt,name=DraftOrderId,proto3" json:"DraftOrderId,omitempty"`
	ManagerId      string                 `protobuf:"bytes,11,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId  string                 `protobuf:"bytes,12,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id             string                 `protobuf:"bytes,13,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddOutsideIncomingDraftOrderAccountingDocumentsIntegratedCommand) Reset() {
	*x = AddOutsideIncomingDraftOrderAccountingDocumentsIntegratedCommand{}
	mi := &file_AddOutsideIncomingDraftOrder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOutsideIncomingDraftOrderAccountingDocumentsIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOutsideIncomingDraftOrderAccountingDocumentsIntegratedCommand) ProtoMessage() {}

func (x *AddOutsideIncomingDraftOrderAccountingDocumentsIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_AddOutsideIncomingDraftOrder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOutsideIncomingDraftOrderAccountingDocumentsIntegratedCommand.ProtoReflect.Descriptor instead.
func (*AddOutsideIncomingDraftOrderAccountingDocumentsIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_AddOutsideIncomingDraftOrder_proto_rawDescGZIP(), []int{0}
}

func (x *AddOutsideIncomingDraftOrderAccountingDocumentsIntegratedCommand) GetPaymentPlace() string {
	if x != nil {
		return x.PaymentPlace
	}
	return ""
}

func (x *AddOutsideIncomingDraftOrderAccountingDocumentsIntegratedCommand) GetPaymentPlaceId() string {
	if x != nil {
		return x.PaymentPlaceId
	}
	return ""
}

func (x *AddOutsideIncomingDraftOrderAccountingDocumentsIntegratedCommand) GetMoney() *common.MoneyDocument {
	if x != nil {
		return x.Money
	}
	return nil
}

func (x *AddOutsideIncomingDraftOrderAccountingDocumentsIntegratedCommand) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddOutsideIncomingDraftOrderAccountingDocumentsIntegratedCommand) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *AddOutsideIncomingDraftOrderAccountingDocumentsIntegratedCommand) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *AddOutsideIncomingDraftOrderAccountingDocumentsIntegratedCommand) GetDraftNumber() string {
	if x != nil {
		return x.DraftNumber
	}
	return ""
}

func (x *AddOutsideIncomingDraftOrderAccountingDocumentsIntegratedCommand) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *AddOutsideIncomingDraftOrderAccountingDocumentsIntegratedCommand) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *AddOutsideIncomingDraftOrderAccountingDocumentsIntegratedCommand) GetDraftOrderId() string {
	if x != nil {
		return x.DraftOrderId
	}
	return ""
}

func (x *AddOutsideIncomingDraftOrderAccountingDocumentsIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *AddOutsideIncomingDraftOrderAccountingDocumentsIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AddOutsideIncomingDraftOrderAccountingDocumentsIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddOutsideIncomingDraftOrderAccountingDocumentsResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDone        bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=Failure,proto3" json:"Failure,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOutsideIncomingDraftOrderAccountingDocumentsResponseIntegratedCommand) Reset() {
	*x = AddOutsideIncomingDraftOrderAccountingDocumentsResponseIntegratedCommand{}
	mi := &file_AddOutsideIncomingDraftOrder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOutsideIncomingDraftOrderAccountingDocumentsResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOutsideIncomingDraftOrderAccountingDocumentsResponseIntegratedCommand) ProtoMessage() {}

func (x *AddOutsideIncomingDraftOrderAccountingDocumentsResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_AddOutsideIncomingDraftOrder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOutsideIncomingDraftOrderAccountingDocumentsResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*AddOutsideIncomingDraftOrderAccountingDocumentsResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_AddOutsideIncomingDraftOrder_proto_rawDescGZIP(), []int{1}
}

func (x *AddOutsideIncomingDraftOrderAccountingDocumentsResponseIntegratedCommand) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *AddOutsideIncomingDraftOrderAccountingDocumentsResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *AddOutsideIncomingDraftOrderAccountingDocumentsResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AddOutsideIncomingDraftOrderAccountingDocumentsResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CommitOrRollbackAddedOutsideIncomingDraftOrderIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCompleted   bool                   `protobuf:"varint,1,opt,name=IsCompleted,proto3" json:"IsCompleted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOrRollbackAddedOutsideIncomingDraftOrderIntegratedCommand) Reset() {
	*x = CommitOrRollbackAddedOutsideIncomingDraftOrderIntegratedCommand{}
	mi := &file_AddOutsideIncomingDraftOrder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOrRollbackAddedOutsideIncomingDraftOrderIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOrRollbackAddedOutsideIncomingDraftOrderIntegratedCommand) ProtoMessage() {}

func (x *CommitOrRollbackAddedOutsideIncomingDraftOrderIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_AddOutsideIncomingDraftOrder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOrRollbackAddedOutsideIncomingDraftOrderIntegratedCommand.ProtoReflect.Descriptor instead.
func (*CommitOrRollbackAddedOutsideIncomingDraftOrderIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_AddOutsideIncomingDraftOrder_proto_rawDescGZIP(), []int{2}
}

func (x *CommitOrRollbackAddedOutsideIncomingDraftOrderIntegratedCommand) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

func (x *CommitOrRollbackAddedOutsideIncomingDraftOrderIntegratedCommand) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommitOrRollbackAddedOutsideIncomingDraftOrderIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CommitOrRollbackAddedOutsideIncomingDraftOrderIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_AddOutsideIncomingDraftOrder_proto protoreflect.FileDescriptor

const file_AddOutsideIncomingDraftOrder_proto_rawDesc = "" +
	"\n" +
	"\"AddOutsideIncomingDraftOrder.proto\x12\x1cAddOutsideIncomingDraftOrder\x1a\fCommon.proto\"\xeb\x03\n" +
	"@AddOutsideIncomingDraftOrderAccountingDocumentsIntegratedCommand\x12\"\n" +
	"\fPaymentPlace\x18\x01 \x01(\tR\fPaymentPlace\x12&\n" +
	"\x0ePaymentPlaceId\x18\x02 \x01(\tR\x0ePaymentPlaceId\x12+\n" +
	"\x05Money\x18\x03 \x01(\v2\x15.Common.MoneyDocumentR\x05Money\x12 \n" +
	"\vDescription\x18\x04 \x01(\tR\vDescription\x12\x1e\n" +
	"\n" +
	"SenderName\x18\x05 \x01(\tR\n" +
	"SenderName\x12\"\n" +
	"\fReceiverName\x18\x06 \x01(\tR\fReceiverName\x12 \n" +
	"\vDraftNumber\x18\a \x01(\tR\vDraftNumber\x12\x12\n" +
	"\x04Date\x18\b \x01(\x03R\x04Date\x12\x1a\n" +
	"\bBranchId\x18\t \x01(\tR\bBranchId\x12\"\n" +
	"\fDraftOrderId\x18\n" +
	" \x01(\tR\fDraftOrderId\x12\x1c\n" +
	"\tManagerId\x18\v \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\f \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\r \x01(\tR\x02Id\"\xc3\x01\n" +
	"HAddOutsideIncomingDraftOrderAccountingDocumentsResponseIntegratedCommand\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12)\n" +
	"\aFailure\x18\x02 \x01(\v2\x0f.Common.FailureR\aFailure\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\xb3\x01\n" +
	"?CommitOrRollbackAddedOutsideIncomingDraftOrderIntegratedCommand\x12 \n" +
	"\vIsCompleted\x18\x01 \x01(\bR\vIsCompleted\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02IdBzZ@moneyx.golang.framework/integration/AddOutsideIncomingDraftOrder\xaa\x025Ariyana.Framework.Schema.AddOutsideIncomingDraftOrderb\x06proto3"

var (
	file_AddOutsideIncomingDraftOrder_proto_rawDescOnce sync.Once
	file_AddOutsideIncomingDraftOrder_proto_rawDescData []byte
)

func file_AddOutsideIncomingDraftOrder_proto_rawDescGZIP() []byte {
	file_AddOutsideIncomingDraftOrder_proto_rawDescOnce.Do(func() {
		file_AddOutsideIncomingDraftOrder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AddOutsideIncomingDraftOrder_proto_rawDesc), len(file_AddOutsideIncomingDraftOrder_proto_rawDesc)))
	})
	return file_AddOutsideIncomingDraftOrder_proto_rawDescData
}

var file_AddOutsideIncomingDraftOrder_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_AddOutsideIncomingDraftOrder_proto_goTypes = []any{
	(*AddOutsideIncomingDraftOrderAccountingDocumentsIntegratedCommand)(nil),         // 0: AddOutsideIncomingDraftOrder.AddOutsideIncomingDraftOrderAccountingDocumentsIntegratedCommand
	(*AddOutsideIncomingDraftOrderAccountingDocumentsResponseIntegratedCommand)(nil), // 1: AddOutsideIncomingDraftOrder.AddOutsideIncomingDraftOrderAccountingDocumentsResponseIntegratedCommand
	(*CommitOrRollbackAddedOutsideIncomingDraftOrderIntegratedCommand)(nil),          // 2: AddOutsideIncomingDraftOrder.CommitOrRollbackAddedOutsideIncomingDraftOrderIntegratedCommand
	(*common.MoneyDocument)(nil), // 3: Common.MoneyDocument
	(*common.Failure)(nil),       // 4: Common.Failure
}
var file_AddOutsideIncomingDraftOrder_proto_depIdxs = []int32{
	3, // 0: AddOutsideIncomingDraftOrder.AddOutsideIncomingDraftOrderAccountingDocumentsIntegratedCommand.Money:type_name -> Common.MoneyDocument
	4, // 1: AddOutsideIncomingDraftOrder.AddOutsideIncomingDraftOrderAccountingDocumentsResponseIntegratedCommand.Failure:type_name -> Common.Failure
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_AddOutsideIncomingDraftOrder_proto_init() }
func file_AddOutsideIncomingDraftOrder_proto_init() {
	if File_AddOutsideIncomingDraftOrder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AddOutsideIncomingDraftOrder_proto_rawDesc), len(file_AddOutsideIncomingDraftOrder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AddOutsideIncomingDraftOrder_proto_goTypes,
		DependencyIndexes: file_AddOutsideIncomingDraftOrder_proto_depIdxs,
		MessageInfos:      file_AddOutsideIncomingDraftOrder_proto_msgTypes,
	}.Build()
	File_AddOutsideIncomingDraftOrder_proto = out.File
	file_AddOutsideIncomingDraftOrder_proto_goTypes = nil
	file_AddOutsideIncomingDraftOrder_proto_depIdxs = nil
}
