// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: AddBannerAdvertisement.proto

package AddBannerAdvertisement

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "moneyx.golang.framework/integration/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddPublicBannerAdvertisementFileIntegratedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*common.FileItem     `protobuf:"bytes,1,rep,name=Files,proto3" json:"Files,omitempty"`
	ManagerId     string                 `protobuf:"bytes,2,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPublicBannerAdvertisementFileIntegratedMessage) Reset() {
	*x = AddPublicBannerAdvertisementFileIntegratedMessage{}
	mi := &file_AddBannerAdvertisement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPublicBannerAdvertisementFileIntegratedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPublicBannerAdvertisementFileIntegratedMessage) ProtoMessage() {}

func (x *AddPublicBannerAdvertisementFileIntegratedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_AddBannerAdvertisement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPublicBannerAdvertisementFileIntegratedMessage.ProtoReflect.Descriptor instead.
func (*AddPublicBannerAdvertisementFileIntegratedMessage) Descriptor() ([]byte, []int) {
	return file_AddBannerAdvertisement_proto_rawDescGZIP(), []int{0}
}

func (x *AddPublicBannerAdvertisementFileIntegratedMessage) GetFiles() []*common.FileItem {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *AddPublicBannerAdvertisementFileIntegratedMessage) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *AddPublicBannerAdvertisementFileIntegratedMessage) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AddPublicBannerAdvertisementFileIntegratedMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddPublicBannerAdvertisementFileResponseIntegratedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDone        bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	FileIds       []string               `protobuf:"bytes,2,rep,name=FileIds,proto3" json:"FileIds,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,3,opt,name=Failure,proto3" json:"Failure,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,5,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPublicBannerAdvertisementFileResponseIntegratedMessage) Reset() {
	*x = AddPublicBannerAdvertisementFileResponseIntegratedMessage{}
	mi := &file_AddBannerAdvertisement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPublicBannerAdvertisementFileResponseIntegratedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPublicBannerAdvertisementFileResponseIntegratedMessage) ProtoMessage() {}

func (x *AddPublicBannerAdvertisementFileResponseIntegratedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_AddBannerAdvertisement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPublicBannerAdvertisementFileResponseIntegratedMessage.ProtoReflect.Descriptor instead.
func (*AddPublicBannerAdvertisementFileResponseIntegratedMessage) Descriptor() ([]byte, []int) {
	return file_AddBannerAdvertisement_proto_rawDescGZIP(), []int{1}
}

func (x *AddPublicBannerAdvertisementFileResponseIntegratedMessage) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *AddPublicBannerAdvertisementFileResponseIntegratedMessage) GetFileIds() []string {
	if x != nil {
		return x.FileIds
	}
	return nil
}

func (x *AddPublicBannerAdvertisementFileResponseIntegratedMessage) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *AddPublicBannerAdvertisementFileResponseIntegratedMessage) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AddPublicBannerAdvertisementFileResponseIntegratedMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CommitOrRollbackAddPublicBannerAdvertisementFileIntegratedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCommitted   bool                   `protobuf:"varint,1,opt,name=IsCommitted,proto3" json:"IsCommitted,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOrRollbackAddPublicBannerAdvertisementFileIntegratedMessage) Reset() {
	*x = CommitOrRollbackAddPublicBannerAdvertisementFileIntegratedMessage{}
	mi := &file_AddBannerAdvertisement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOrRollbackAddPublicBannerAdvertisementFileIntegratedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOrRollbackAddPublicBannerAdvertisementFileIntegratedMessage) ProtoMessage() {}

func (x *CommitOrRollbackAddPublicBannerAdvertisementFileIntegratedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_AddBannerAdvertisement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOrRollbackAddPublicBannerAdvertisementFileIntegratedMessage.ProtoReflect.Descriptor instead.
func (*CommitOrRollbackAddPublicBannerAdvertisementFileIntegratedMessage) Descriptor() ([]byte, []int) {
	return file_AddBannerAdvertisement_proto_rawDescGZIP(), []int{2}
}

func (x *CommitOrRollbackAddPublicBannerAdvertisementFileIntegratedMessage) GetIsCommitted() bool {
	if x != nil {
		return x.IsCommitted
	}
	return false
}

func (x *CommitOrRollbackAddPublicBannerAdvertisementFileIntegratedMessage) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CommitOrRollbackAddPublicBannerAdvertisementFileIntegratedMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_AddBannerAdvertisement_proto protoreflect.FileDescriptor

const file_AddBannerAdvertisement_proto_rawDesc = "" +
	"\n" +
	"\x1cAddBannerAdvertisement.proto\x12\x16AddBannerAdvertisement\x1a\fCommon.proto\"\xaf\x01\n" +
	"1AddPublicBannerAdvertisementFileIntegratedMessage\x12&\n" +
	"\x05Files\x18\x01 \x03(\v2\x10.Common.FileItemR\x05Files\x12\x1c\n" +
	"\tManagerId\x18\x02 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\xce\x01\n" +
	"9AddPublicBannerAdvertisementFileResponseIntegratedMessage\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12\x18\n" +
	"\aFileIds\x18\x02 \x03(\tR\aFileIds\x12)\n" +
	"\aFailure\x18\x03 \x01(\v2\x0f.Common.FailureR\aFailure\x12$\n" +
	"\rCorrelationId\x18\x04 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x05 \x01(\tR\x02Id\"\x9b\x01\n" +
	"ACommitOrRollbackAddPublicBannerAdvertisementFileIntegratedMessage\x12 \n" +
	"\vIsCommitted\x18\x01 \x01(\bR\vIsCommitted\x12$\n" +
	"\rCorrelationId\x18\x02 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x03 \x01(\tR\x02IdBnZ:moneyx.golang.framework/integration/AddBannerAdvertisement\xaa\x02/Ariyana.Framework.Schema.AddBannerAdvertisementb\x06proto3"

var (
	file_AddBannerAdvertisement_proto_rawDescOnce sync.Once
	file_AddBannerAdvertisement_proto_rawDescData []byte
)

func file_AddBannerAdvertisement_proto_rawDescGZIP() []byte {
	file_AddBannerAdvertisement_proto_rawDescOnce.Do(func() {
		file_AddBannerAdvertisement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AddBannerAdvertisement_proto_rawDesc), len(file_AddBannerAdvertisement_proto_rawDesc)))
	})
	return file_AddBannerAdvertisement_proto_rawDescData
}

var file_AddBannerAdvertisement_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_AddBannerAdvertisement_proto_goTypes = []any{
	(*AddPublicBannerAdvertisementFileIntegratedMessage)(nil),                 // 0: AddBannerAdvertisement.AddPublicBannerAdvertisementFileIntegratedMessage
	(*AddPublicBannerAdvertisementFileResponseIntegratedMessage)(nil),         // 1: AddBannerAdvertisement.AddPublicBannerAdvertisementFileResponseIntegratedMessage
	(*CommitOrRollbackAddPublicBannerAdvertisementFileIntegratedMessage)(nil), // 2: AddBannerAdvertisement.CommitOrRollbackAddPublicBannerAdvertisementFileIntegratedMessage
	(*common.FileItem)(nil), // 3: Common.FileItem
	(*common.Failure)(nil),  // 4: Common.Failure
}
var file_AddBannerAdvertisement_proto_depIdxs = []int32{
	3, // 0: AddBannerAdvertisement.AddPublicBannerAdvertisementFileIntegratedMessage.Files:type_name -> Common.FileItem
	4, // 1: AddBannerAdvertisement.AddPublicBannerAdvertisementFileResponseIntegratedMessage.Failure:type_name -> Common.Failure
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_AddBannerAdvertisement_proto_init() }
func file_AddBannerAdvertisement_proto_init() {
	if File_AddBannerAdvertisement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AddBannerAdvertisement_proto_rawDesc), len(file_AddBannerAdvertisement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AddBannerAdvertisement_proto_goTypes,
		DependencyIndexes: file_AddBannerAdvertisement_proto_depIdxs,
		MessageInfos:      file_AddBannerAdvertisement_proto_msgTypes,
	}.Build()
	File_AddBannerAdvertisement_proto = out.File
	file_AddBannerAdvertisement_proto_goTypes = nil
	file_AddBannerAdvertisement_proto_depIdxs = nil
}
