// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: AddPersonDocumentAttachments.proto

package AddPersonDocumentAttachments

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "moneyx.golang.framework/integration/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddPersonDocumentAttachmentsResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDone        bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	StoredFileId  []string               `protobuf:"bytes,2,rep,name=StoredFileId,proto3" json:"StoredFileId,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPersonDocumentAttachmentsResponseIntegratedCommand) Reset() {
	*x = AddPersonDocumentAttachmentsResponseIntegratedCommand{}
	mi := &file_AddPersonDocumentAttachments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPersonDocumentAttachmentsResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPersonDocumentAttachmentsResponseIntegratedCommand) ProtoMessage() {}

func (x *AddPersonDocumentAttachmentsResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_AddPersonDocumentAttachments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPersonDocumentAttachmentsResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*AddPersonDocumentAttachmentsResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_AddPersonDocumentAttachments_proto_rawDescGZIP(), []int{0}
}

func (x *AddPersonDocumentAttachmentsResponseIntegratedCommand) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *AddPersonDocumentAttachmentsResponseIntegratedCommand) GetStoredFileId() []string {
	if x != nil {
		return x.StoredFileId
	}
	return nil
}

func (x *AddPersonDocumentAttachmentsResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AddPersonDocumentAttachmentsResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddPersonDocumentAttachmentsIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileItem      []*common.FileItem     `protobuf:"bytes,1,rep,name=FileItem,proto3" json:"FileItem,omitempty"`
	RemovedFileId []string               `protobuf:"bytes,2,rep,name=RemovedFileId,proto3" json:"RemovedFileId,omitempty"`
	ManagerId     string                 `protobuf:"bytes,3,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,5,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPersonDocumentAttachmentsIntegratedCommand) Reset() {
	*x = AddPersonDocumentAttachmentsIntegratedCommand{}
	mi := &file_AddPersonDocumentAttachments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPersonDocumentAttachmentsIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPersonDocumentAttachmentsIntegratedCommand) ProtoMessage() {}

func (x *AddPersonDocumentAttachmentsIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_AddPersonDocumentAttachments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPersonDocumentAttachmentsIntegratedCommand.ProtoReflect.Descriptor instead.
func (*AddPersonDocumentAttachmentsIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_AddPersonDocumentAttachments_proto_rawDescGZIP(), []int{1}
}

func (x *AddPersonDocumentAttachmentsIntegratedCommand) GetFileItem() []*common.FileItem {
	if x != nil {
		return x.FileItem
	}
	return nil
}

func (x *AddPersonDocumentAttachmentsIntegratedCommand) GetRemovedFileId() []string {
	if x != nil {
		return x.RemovedFileId
	}
	return nil
}

func (x *AddPersonDocumentAttachmentsIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *AddPersonDocumentAttachmentsIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AddPersonDocumentAttachmentsIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RollbackAddedPersonAttachmentsIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackAddedPersonAttachmentsIntegratedCommand) Reset() {
	*x = RollbackAddedPersonAttachmentsIntegratedCommand{}
	mi := &file_AddPersonDocumentAttachments_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackAddedPersonAttachmentsIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackAddedPersonAttachmentsIntegratedCommand) ProtoMessage() {}

func (x *RollbackAddedPersonAttachmentsIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_AddPersonDocumentAttachments_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackAddedPersonAttachmentsIntegratedCommand.ProtoReflect.Descriptor instead.
func (*RollbackAddedPersonAttachmentsIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_AddPersonDocumentAttachments_proto_rawDescGZIP(), []int{2}
}

func (x *RollbackAddedPersonAttachmentsIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RollbackAddedPersonAttachmentsIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_AddPersonDocumentAttachments_proto protoreflect.FileDescriptor

const file_AddPersonDocumentAttachments_proto_rawDesc = "" +
	"\n" +
	"\"AddPersonDocumentAttachments.proto\x12\x1cAddPersonDocumentAttachments\x1a\fCommon.proto\"\xa9\x01\n" +
	"5AddPersonDocumentAttachmentsResponseIntegratedCommand\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12\"\n" +
	"\fStoredFileId\x18\x02 \x03(\tR\fStoredFileId\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\xd7\x01\n" +
	"-AddPersonDocumentAttachmentsIntegratedCommand\x12,\n" +
	"\bFileItem\x18\x01 \x03(\v2\x10.Common.FileItemR\bFileItem\x12$\n" +
	"\rRemovedFileId\x18\x02 \x03(\tR\rRemovedFileId\x12\x1c\n" +
	"\tManagerId\x18\x03 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x04 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x05 \x01(\tR\x02Id\"g\n" +
	"/RollbackAddedPersonAttachmentsIntegratedCommand\x12$\n" +
	"\rCorrelationId\x18\x01 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x02 \x01(\tR\x02IdBzZ@moneyx.golang.framework/integration/AddPersonDocumentAttachments\xaa\x025Ariyana.Framework.Schema.AddPersonDocumentAttachmentsb\x06proto3"

var (
	file_AddPersonDocumentAttachments_proto_rawDescOnce sync.Once
	file_AddPersonDocumentAttachments_proto_rawDescData []byte
)

func file_AddPersonDocumentAttachments_proto_rawDescGZIP() []byte {
	file_AddPersonDocumentAttachments_proto_rawDescOnce.Do(func() {
		file_AddPersonDocumentAttachments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AddPersonDocumentAttachments_proto_rawDesc), len(file_AddPersonDocumentAttachments_proto_rawDesc)))
	})
	return file_AddPersonDocumentAttachments_proto_rawDescData
}

var file_AddPersonDocumentAttachments_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_AddPersonDocumentAttachments_proto_goTypes = []any{
	(*AddPersonDocumentAttachmentsResponseIntegratedCommand)(nil), // 0: AddPersonDocumentAttachments.AddPersonDocumentAttachmentsResponseIntegratedCommand
	(*AddPersonDocumentAttachmentsIntegratedCommand)(nil),         // 1: AddPersonDocumentAttachments.AddPersonDocumentAttachmentsIntegratedCommand
	(*RollbackAddedPersonAttachmentsIntegratedCommand)(nil),       // 2: AddPersonDocumentAttachments.RollbackAddedPersonAttachmentsIntegratedCommand
	(*common.FileItem)(nil),                                       // 3: Common.FileItem
}
var file_AddPersonDocumentAttachments_proto_depIdxs = []int32{
	3, // 0: AddPersonDocumentAttachments.AddPersonDocumentAttachmentsIntegratedCommand.FileItem:type_name -> Common.FileItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_AddPersonDocumentAttachments_proto_init() }
func file_AddPersonDocumentAttachments_proto_init() {
	if File_AddPersonDocumentAttachments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AddPersonDocumentAttachments_proto_rawDesc), len(file_AddPersonDocumentAttachments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AddPersonDocumentAttachments_proto_goTypes,
		DependencyIndexes: file_AddPersonDocumentAttachments_proto_depIdxs,
		MessageInfos:      file_AddPersonDocumentAttachments_proto_msgTypes,
	}.Build()
	File_AddPersonDocumentAttachments_proto = out.File
	file_AddPersonDocumentAttachments_proto_goTypes = nil
	file_AddPersonDocumentAttachments_proto_depIdxs = nil
}
