// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: BuyTurkcellCharge.proto

package BuyTurkcellCharge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "moneyx.golang.framework/integration/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddAccountingBuyTurkcellChargeDocumentsResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDone        bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=Failure,proto3" json:"Failure,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAccountingBuyTurkcellChargeDocumentsResponseIntegratedCommand) Reset() {
	*x = AddAccountingBuyTurkcellChargeDocumentsResponseIntegratedCommand{}
	mi := &file_BuyTurkcellCharge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAccountingBuyTurkcellChargeDocumentsResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAccountingBuyTurkcellChargeDocumentsResponseIntegratedCommand) ProtoMessage() {}

func (x *AddAccountingBuyTurkcellChargeDocumentsResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyTurkcellCharge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAccountingBuyTurkcellChargeDocumentsResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*AddAccountingBuyTurkcellChargeDocumentsResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyTurkcellCharge_proto_rawDescGZIP(), []int{0}
}

func (x *AddAccountingBuyTurkcellChargeDocumentsResponseIntegratedCommand) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *AddAccountingBuyTurkcellChargeDocumentsResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *AddAccountingBuyTurkcellChargeDocumentsResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AddAccountingBuyTurkcellChargeDocumentsResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TurkcellCheckCustomerActivationResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsEnable      bool                   `protobuf:"varint,1,opt,name=IsEnable,proto3" json:"IsEnable,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=CustomerId,proto3" json:"CustomerId,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,3,opt,name=Failure,proto3" json:"Failure,omitempty"`
	ManagerId     string                 `protobuf:"bytes,4,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurkcellCheckCustomerActivationResponseIntegratedCommand) Reset() {
	*x = TurkcellCheckCustomerActivationResponseIntegratedCommand{}
	mi := &file_BuyTurkcellCharge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurkcellCheckCustomerActivationResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurkcellCheckCustomerActivationResponseIntegratedCommand) ProtoMessage() {}

func (x *TurkcellCheckCustomerActivationResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyTurkcellCharge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurkcellCheckCustomerActivationResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*TurkcellCheckCustomerActivationResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyTurkcellCharge_proto_rawDescGZIP(), []int{1}
}

func (x *TurkcellCheckCustomerActivationResponseIntegratedCommand) GetIsEnable() bool {
	if x != nil {
		return x.IsEnable
	}
	return false
}

func (x *TurkcellCheckCustomerActivationResponseIntegratedCommand) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *TurkcellCheckCustomerActivationResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *TurkcellCheckCustomerActivationResponseIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *TurkcellCheckCustomerActivationResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *TurkcellCheckCustomerActivationResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BuyTurkcellChargeCreditReductionResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDone        bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=Failure,proto3" json:"Failure,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyTurkcellChargeCreditReductionResponseIntegratedCommand) Reset() {
	*x = BuyTurkcellChargeCreditReductionResponseIntegratedCommand{}
	mi := &file_BuyTurkcellCharge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyTurkcellChargeCreditReductionResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyTurkcellChargeCreditReductionResponseIntegratedCommand) ProtoMessage() {}

func (x *BuyTurkcellChargeCreditReductionResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyTurkcellCharge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyTurkcellChargeCreditReductionResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*BuyTurkcellChargeCreditReductionResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyTurkcellCharge_proto_rawDescGZIP(), []int{2}
}

func (x *BuyTurkcellChargeCreditReductionResponseIntegratedCommand) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *BuyTurkcellChargeCreditReductionResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *BuyTurkcellChargeCreditReductionResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BuyTurkcellChargeCreditReductionResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BuyTurkcellChargeByAfghanCellResponseIntegratedCommand struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	IsDone                   bool                   `protobuf:"varint,1,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	Failure                  *common.Failure        `protobuf:"bytes,2,opt,name=Failure,proto3" json:"Failure,omitempty"`
	ServiceProviderRefNumber string                 `protobuf:"bytes,3,opt,name=ServiceProviderRefNumber,proto3" json:"ServiceProviderRefNumber,omitempty"`
	CorrelationId            string                 `protobuf:"bytes,4,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id                       string                 `protobuf:"bytes,5,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *BuyTurkcellChargeByAfghanCellResponseIntegratedCommand) Reset() {
	*x = BuyTurkcellChargeByAfghanCellResponseIntegratedCommand{}
	mi := &file_BuyTurkcellCharge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyTurkcellChargeByAfghanCellResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyTurkcellChargeByAfghanCellResponseIntegratedCommand) ProtoMessage() {}

func (x *BuyTurkcellChargeByAfghanCellResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyTurkcellCharge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyTurkcellChargeByAfghanCellResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*BuyTurkcellChargeByAfghanCellResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyTurkcellCharge_proto_rawDescGZIP(), []int{3}
}

func (x *BuyTurkcellChargeByAfghanCellResponseIntegratedCommand) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *BuyTurkcellChargeByAfghanCellResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *BuyTurkcellChargeByAfghanCellResponseIntegratedCommand) GetServiceProviderRefNumber() string {
	if x != nil {
		return x.ServiceProviderRefNumber
	}
	return ""
}

func (x *BuyTurkcellChargeByAfghanCellResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BuyTurkcellChargeByAfghanCellResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TurkcellCheckManagerChargeActivationResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsEnable      bool                   `protobuf:"varint,1,opt,name=IsEnable,proto3" json:"IsEnable,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=Failure,proto3" json:"Failure,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurkcellCheckManagerChargeActivationResponseIntegratedCommand) Reset() {
	*x = TurkcellCheckManagerChargeActivationResponseIntegratedCommand{}
	mi := &file_BuyTurkcellCharge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurkcellCheckManagerChargeActivationResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurkcellCheckManagerChargeActivationResponseIntegratedCommand) ProtoMessage() {}

func (x *TurkcellCheckManagerChargeActivationResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyTurkcellCharge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurkcellCheckManagerChargeActivationResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*TurkcellCheckManagerChargeActivationResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyTurkcellCharge_proto_rawDescGZIP(), []int{4}
}

func (x *TurkcellCheckManagerChargeActivationResponseIntegratedCommand) GetIsEnable() bool {
	if x != nil {
		return x.IsEnable
	}
	return false
}

func (x *TurkcellCheckManagerChargeActivationResponseIntegratedCommand) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *TurkcellCheckManagerChargeActivationResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *TurkcellCheckManagerChargeActivationResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TurkcellCheckManagerChargeActivationIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManagerId     string                 `protobuf:"bytes,1,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurkcellCheckManagerChargeActivationIntegratedCommand) Reset() {
	*x = TurkcellCheckManagerChargeActivationIntegratedCommand{}
	mi := &file_BuyTurkcellCharge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurkcellCheckManagerChargeActivationIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurkcellCheckManagerChargeActivationIntegratedCommand) ProtoMessage() {}

func (x *TurkcellCheckManagerChargeActivationIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyTurkcellCharge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurkcellCheckManagerChargeActivationIntegratedCommand.ProtoReflect.Descriptor instead.
func (*TurkcellCheckManagerChargeActivationIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyTurkcellCharge_proto_rawDescGZIP(), []int{5}
}

func (x *TurkcellCheckManagerChargeActivationIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *TurkcellCheckManagerChargeActivationIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *TurkcellCheckManagerChargeActivationIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TurkcellCheckCustomerActivationIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	ManagerId     string                 `protobuf:"bytes,3,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,5,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurkcellCheckCustomerActivationIntegratedCommand) Reset() {
	*x = TurkcellCheckCustomerActivationIntegratedCommand{}
	mi := &file_BuyTurkcellCharge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurkcellCheckCustomerActivationIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurkcellCheckCustomerActivationIntegratedCommand) ProtoMessage() {}

func (x *TurkcellCheckCustomerActivationIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyTurkcellCharge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurkcellCheckCustomerActivationIntegratedCommand.ProtoReflect.Descriptor instead.
func (*TurkcellCheckCustomerActivationIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyTurkcellCharge_proto_rawDescGZIP(), []int{6}
}

func (x *TurkcellCheckCustomerActivationIntegratedCommand) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *TurkcellCheckCustomerActivationIntegratedCommand) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *TurkcellCheckCustomerActivationIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *TurkcellCheckCustomerActivationIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *TurkcellCheckCustomerActivationIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BuyTurkcellChargeCreditReductionIntegratedCommand struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	AccountId              string                 `protobuf:"bytes,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	PackageTitle           string                 `protobuf:"bytes,2,opt,name=PackageTitle,proto3" json:"PackageTitle,omitempty"`
	ChargeTransactionId    string                 `protobuf:"bytes,3,opt,name=ChargeTransactionId,proto3" json:"ChargeTransactionId,omitempty"`
	Commission             *common.Money          `protobuf:"bytes,4,opt,name=Commission,proto3" json:"Commission,omitempty"`
	ExchangerDeductedMoney *common.Money          `protobuf:"bytes,5,opt,name=ExchangerDeductedMoney,proto3" json:"ExchangerDeductedMoney,omitempty"`
	OperatorName           string                 `protobuf:"bytes,6,opt,name=OperatorName,proto3" json:"OperatorName,omitempty"`
	PhoneNumber            string                 `protobuf:"bytes,7,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	ManagerId              string                 `protobuf:"bytes,8,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId          string                 `protobuf:"bytes,9,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id                     string                 `protobuf:"bytes,10,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BuyTurkcellChargeCreditReductionIntegratedCommand) Reset() {
	*x = BuyTurkcellChargeCreditReductionIntegratedCommand{}
	mi := &file_BuyTurkcellCharge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyTurkcellChargeCreditReductionIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyTurkcellChargeCreditReductionIntegratedCommand) ProtoMessage() {}

func (x *BuyTurkcellChargeCreditReductionIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyTurkcellCharge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyTurkcellChargeCreditReductionIntegratedCommand.ProtoReflect.Descriptor instead.
func (*BuyTurkcellChargeCreditReductionIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyTurkcellCharge_proto_rawDescGZIP(), []int{7}
}

func (x *BuyTurkcellChargeCreditReductionIntegratedCommand) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *BuyTurkcellChargeCreditReductionIntegratedCommand) GetPackageTitle() string {
	if x != nil {
		return x.PackageTitle
	}
	return ""
}

func (x *BuyTurkcellChargeCreditReductionIntegratedCommand) GetChargeTransactionId() string {
	if x != nil {
		return x.ChargeTransactionId
	}
	return ""
}

func (x *BuyTurkcellChargeCreditReductionIntegratedCommand) GetCommission() *common.Money {
	if x != nil {
		return x.Commission
	}
	return nil
}

func (x *BuyTurkcellChargeCreditReductionIntegratedCommand) GetExchangerDeductedMoney() *common.Money {
	if x != nil {
		return x.ExchangerDeductedMoney
	}
	return nil
}

func (x *BuyTurkcellChargeCreditReductionIntegratedCommand) GetOperatorName() string {
	if x != nil {
		return x.OperatorName
	}
	return ""
}

func (x *BuyTurkcellChargeCreditReductionIntegratedCommand) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *BuyTurkcellChargeCreditReductionIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *BuyTurkcellChargeCreditReductionIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BuyTurkcellChargeCreditReductionIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddAccountingBuyTurkcellChargeDocumentsIntegratedCommand struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	BuyChargeInfo *common.BuyChargeAccountingInfo `protobuf:"bytes,1,opt,name=BuyChargeInfo,proto3" json:"BuyChargeInfo,omitempty"`
	CustomerId    string                          `protobuf:"bytes,2,opt,name=CustomerId,proto3" json:"CustomerId,omitempty"`
	ManagerId     string                          `protobuf:"bytes,3,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId string                          `protobuf:"bytes,4,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                          `protobuf:"bytes,5,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAccountingBuyTurkcellChargeDocumentsIntegratedCommand) Reset() {
	*x = AddAccountingBuyTurkcellChargeDocumentsIntegratedCommand{}
	mi := &file_BuyTurkcellCharge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAccountingBuyTurkcellChargeDocumentsIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAccountingBuyTurkcellChargeDocumentsIntegratedCommand) ProtoMessage() {}

func (x *AddAccountingBuyTurkcellChargeDocumentsIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyTurkcellCharge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAccountingBuyTurkcellChargeDocumentsIntegratedCommand.ProtoReflect.Descriptor instead.
func (*AddAccountingBuyTurkcellChargeDocumentsIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyTurkcellCharge_proto_rawDescGZIP(), []int{8}
}

func (x *AddAccountingBuyTurkcellChargeDocumentsIntegratedCommand) GetBuyChargeInfo() *common.BuyChargeAccountingInfo {
	if x != nil {
		return x.BuyChargeInfo
	}
	return nil
}

func (x *AddAccountingBuyTurkcellChargeDocumentsIntegratedCommand) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *AddAccountingBuyTurkcellChargeDocumentsIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *AddAccountingBuyTurkcellChargeDocumentsIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AddAccountingBuyTurkcellChargeDocumentsIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BuyTurkcellChargeByAfghanCellIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AmountPackage float64                `protobuf:"fixed64,1,opt,name=AmountPackage,proto3" json:"AmountPackage,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=TransactionId,proto3" json:"TransactionId,omitempty"`
	ChargeNumber  string                 `protobuf:"bytes,3,opt,name=ChargeNumber,proto3" json:"ChargeNumber,omitempty"`
	PackageCode   string                 `protobuf:"bytes,4,opt,name=PackageCode,proto3" json:"PackageCode,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyTurkcellChargeByAfghanCellIntegratedCommand) Reset() {
	*x = BuyTurkcellChargeByAfghanCellIntegratedCommand{}
	mi := &file_BuyTurkcellCharge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyTurkcellChargeByAfghanCellIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyTurkcellChargeByAfghanCellIntegratedCommand) ProtoMessage() {}

func (x *BuyTurkcellChargeByAfghanCellIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyTurkcellCharge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyTurkcellChargeByAfghanCellIntegratedCommand.ProtoReflect.Descriptor instead.
func (*BuyTurkcellChargeByAfghanCellIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyTurkcellCharge_proto_rawDescGZIP(), []int{9}
}

func (x *BuyTurkcellChargeByAfghanCellIntegratedCommand) GetAmountPackage() float64 {
	if x != nil {
		return x.AmountPackage
	}
	return 0
}

func (x *BuyTurkcellChargeByAfghanCellIntegratedCommand) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *BuyTurkcellChargeByAfghanCellIntegratedCommand) GetChargeNumber() string {
	if x != nil {
		return x.ChargeNumber
	}
	return ""
}

func (x *BuyTurkcellChargeByAfghanCellIntegratedCommand) GetPackageCode() string {
	if x != nil {
		return x.PackageCode
	}
	return ""
}

func (x *BuyTurkcellChargeByAfghanCellIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BuyTurkcellChargeByAfghanCellIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CommitOrRollbackAddedBuyTurkcellChargeAccountingDocumentIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCommitted   bool                   `protobuf:"varint,1,opt,name=IsCommitted,proto3" json:"IsCommitted,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOrRollbackAddedBuyTurkcellChargeAccountingDocumentIntegratedCommand) Reset() {
	*x = CommitOrRollbackAddedBuyTurkcellChargeAccountingDocumentIntegratedCommand{}
	mi := &file_BuyTurkcellCharge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOrRollbackAddedBuyTurkcellChargeAccountingDocumentIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOrRollbackAddedBuyTurkcellChargeAccountingDocumentIntegratedCommand) ProtoMessage() {}

func (x *CommitOrRollbackAddedBuyTurkcellChargeAccountingDocumentIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyTurkcellCharge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOrRollbackAddedBuyTurkcellChargeAccountingDocumentIntegratedCommand.ProtoReflect.Descriptor instead.
func (*CommitOrRollbackAddedBuyTurkcellChargeAccountingDocumentIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyTurkcellCharge_proto_rawDescGZIP(), []int{10}
}

func (x *CommitOrRollbackAddedBuyTurkcellChargeAccountingDocumentIntegratedCommand) GetIsCommitted() bool {
	if x != nil {
		return x.IsCommitted
	}
	return false
}

func (x *CommitOrRollbackAddedBuyTurkcellChargeAccountingDocumentIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CommitOrRollbackAddedBuyTurkcellChargeAccountingDocumentIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CommitOrRollbackBuyTurkcellChargeCreditReductionIntegratedCommand struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	IsCommitted   bool                               `protobuf:"varint,1,opt,name=IsCommitted,proto3" json:"IsCommitted,omitempty"`
	Context       *common.CreditReductionMetaContext `protobuf:"bytes,2,opt,name=Context,proto3" json:"Context,omitempty"`
	CorrelationId string                             `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                             `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOrRollbackBuyTurkcellChargeCreditReductionIntegratedCommand) Reset() {
	*x = CommitOrRollbackBuyTurkcellChargeCreditReductionIntegratedCommand{}
	mi := &file_BuyTurkcellCharge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOrRollbackBuyTurkcellChargeCreditReductionIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOrRollbackBuyTurkcellChargeCreditReductionIntegratedCommand) ProtoMessage() {}

func (x *CommitOrRollbackBuyTurkcellChargeCreditReductionIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_BuyTurkcellCharge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOrRollbackBuyTurkcellChargeCreditReductionIntegratedCommand.ProtoReflect.Descriptor instead.
func (*CommitOrRollbackBuyTurkcellChargeCreditReductionIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_BuyTurkcellCharge_proto_rawDescGZIP(), []int{11}
}

func (x *CommitOrRollbackBuyTurkcellChargeCreditReductionIntegratedCommand) GetIsCommitted() bool {
	if x != nil {
		return x.IsCommitted
	}
	return false
}

func (x *CommitOrRollbackBuyTurkcellChargeCreditReductionIntegratedCommand) GetContext() *common.CreditReductionMetaContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CommitOrRollbackBuyTurkcellChargeCreditReductionIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CommitOrRollbackBuyTurkcellChargeCreditReductionIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_BuyTurkcellCharge_proto protoreflect.FileDescriptor

const file_BuyTurkcellCharge_proto_rawDesc = "" +
	"\n" +
	"\x17BuyTurkcellCharge.proto\x12\x11BuyTurkcellCharge\x1a\fCommon.proto\"\xbb\x01\n" +
	"@AddAccountingBuyTurkcellChargeDocumentsResponseIntegratedCommand\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12)\n" +
	"\aFailure\x18\x02 \x01(\v2\x0f.Common.FailureR\aFailure\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\xf5\x01\n" +
	"8TurkcellCheckCustomerActivationResponseIntegratedCommand\x12\x1a\n" +
	"\bIsEnable\x18\x01 \x01(\bR\bIsEnable\x12\x1e\n" +
	"\n" +
	"CustomerId\x18\x02 \x01(\tR\n" +
	"CustomerId\x12)\n" +
	"\aFailure\x18\x03 \x01(\v2\x0f.Common.FailureR\aFailure\x12\x1c\n" +
	"\tManagerId\x18\x04 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x05 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x06 \x01(\tR\x02Id\"\xb4\x01\n" +
	"9BuyTurkcellChargeCreditReductionResponseIntegratedCommand\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12)\n" +
	"\aFailure\x18\x02 \x01(\v2\x0f.Common.FailureR\aFailure\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\xed\x01\n" +
	"6BuyTurkcellChargeByAfghanCellResponseIntegratedCommand\x12\x16\n" +
	"\x06IsDone\x18\x01 \x01(\bR\x06IsDone\x12)\n" +
	"\aFailure\x18\x02 \x01(\v2\x0f.Common.FailureR\aFailure\x12:\n" +
	"\x18ServiceProviderRefNumber\x18\x03 \x01(\tR\x18ServiceProviderRefNumber\x12$\n" +
	"\rCorrelationId\x18\x04 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x05 \x01(\tR\x02Id\"\xbc\x01\n" +
	"=TurkcellCheckManagerChargeActivationResponseIntegratedCommand\x12\x1a\n" +
	"\bIsEnable\x18\x01 \x01(\bR\bIsEnable\x12)\n" +
	"\aFailure\x18\x02 \x01(\v2\x0f.Common.FailureR\aFailure\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\x8b\x01\n" +
	"5TurkcellCheckManagerChargeActivationIntegratedCommand\x12\x1c\n" +
	"\tManagerId\x18\x01 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x02 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x03 \x01(\tR\x02Id\"\xc0\x01\n" +
	"0TurkcellCheckCustomerActivationIntegratedCommand\x12\x1a\n" +
	"\bUserName\x18\x01 \x01(\tR\bUserName\x12\x1c\n" +
	"\tAccountId\x18\x02 \x01(\tR\tAccountId\x12\x1c\n" +
	"\tManagerId\x18\x03 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x04 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x05 \x01(\tR\x02Id\"\xb7\x03\n" +
	"1BuyTurkcellChargeCreditReductionIntegratedCommand\x12\x1c\n" +
	"\tAccountId\x18\x01 \x01(\tR\tAccountId\x12\"\n" +
	"\fPackageTitle\x18\x02 \x01(\tR\fPackageTitle\x120\n" +
	"\x13ChargeTransactionId\x18\x03 \x01(\tR\x13ChargeTransactionId\x12-\n" +
	"\n" +
	"Commission\x18\x04 \x01(\v2\r.Common.MoneyR\n" +
	"Commission\x12E\n" +
	"\x16ExchangerDeductedMoney\x18\x05 \x01(\v2\r.Common.MoneyR\x16ExchangerDeductedMoney\x12\"\n" +
	"\fOperatorName\x18\x06 \x01(\tR\fOperatorName\x12 \n" +
	"\vPhoneNumber\x18\a \x01(\tR\vPhoneNumber\x12\x1c\n" +
	"\tManagerId\x18\b \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\t \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\n" +
	" \x01(\tR\x02Id\"\xf5\x01\n" +
	"8AddAccountingBuyTurkcellChargeDocumentsIntegratedCommand\x12E\n" +
	"\rBuyChargeInfo\x18\x01 \x01(\v2\x1f.Common.BuyChargeAccountingInfoR\rBuyChargeInfo\x12\x1e\n" +
	"\n" +
	"CustomerId\x18\x02 \x01(\tR\n" +
	"CustomerId\x12\x1c\n" +
	"\tManagerId\x18\x03 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x04 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x05 \x01(\tR\x02Id\"\xf8\x01\n" +
	".BuyTurkcellChargeByAfghanCellIntegratedCommand\x12$\n" +
	"\rAmountPackage\x18\x01 \x01(\x01R\rAmountPackage\x12$\n" +
	"\rTransactionId\x18\x02 \x01(\tR\rTransactionId\x12\"\n" +
	"\fChargeNumber\x18\x03 \x01(\tR\fChargeNumber\x12 \n" +
	"\vPackageCode\x18\x04 \x01(\tR\vPackageCode\x12$\n" +
	"\rCorrelationId\x18\x05 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x06 \x01(\tR\x02Id\"\xa3\x01\n" +
	"ICommitOrRollbackAddedBuyTurkcellChargeAccountingDocumentIntegratedCommand\x12 \n" +
	"\vIsCommitted\x18\x01 \x01(\bR\vIsCommitted\x12$\n" +
	"\rCorrelationId\x18\x02 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x03 \x01(\tR\x02Id\"\xd9\x01\n" +
	"ACommitOrRollbackBuyTurkcellChargeCreditReductionIntegratedCommand\x12 \n" +
	"\vIsCommitted\x18\x01 \x01(\bR\vIsCommitted\x12<\n" +
	"\aContext\x18\x02 \x01(\v2\".Common.CreditReductionMetaContextR\aContext\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02IdBdZ5moneyx.golang.framework/integration/BuyTurkcellCharge\xaa\x02*Ariyana.Framework.Schema.BuyTurkcellChargeb\x06proto3"

var (
	file_BuyTurkcellCharge_proto_rawDescOnce sync.Once
	file_BuyTurkcellCharge_proto_rawDescData []byte
)

func file_BuyTurkcellCharge_proto_rawDescGZIP() []byte {
	file_BuyTurkcellCharge_proto_rawDescOnce.Do(func() {
		file_BuyTurkcellCharge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_BuyTurkcellCharge_proto_rawDesc), len(file_BuyTurkcellCharge_proto_rawDesc)))
	})
	return file_BuyTurkcellCharge_proto_rawDescData
}

var file_BuyTurkcellCharge_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_BuyTurkcellCharge_proto_goTypes = []any{
	(*AddAccountingBuyTurkcellChargeDocumentsResponseIntegratedCommand)(nil),          // 0: BuyTurkcellCharge.AddAccountingBuyTurkcellChargeDocumentsResponseIntegratedCommand
	(*TurkcellCheckCustomerActivationResponseIntegratedCommand)(nil),                  // 1: BuyTurkcellCharge.TurkcellCheckCustomerActivationResponseIntegratedCommand
	(*BuyTurkcellChargeCreditReductionResponseIntegratedCommand)(nil),                 // 2: BuyTurkcellCharge.BuyTurkcellChargeCreditReductionResponseIntegratedCommand
	(*BuyTurkcellChargeByAfghanCellResponseIntegratedCommand)(nil),                    // 3: BuyTurkcellCharge.BuyTurkcellChargeByAfghanCellResponseIntegratedCommand
	(*TurkcellCheckManagerChargeActivationResponseIntegratedCommand)(nil),             // 4: BuyTurkcellCharge.TurkcellCheckManagerChargeActivationResponseIntegratedCommand
	(*TurkcellCheckManagerChargeActivationIntegratedCommand)(nil),                     // 5: BuyTurkcellCharge.TurkcellCheckManagerChargeActivationIntegratedCommand
	(*TurkcellCheckCustomerActivationIntegratedCommand)(nil),                          // 6: BuyTurkcellCharge.TurkcellCheckCustomerActivationIntegratedCommand
	(*BuyTurkcellChargeCreditReductionIntegratedCommand)(nil),                         // 7: BuyTurkcellCharge.BuyTurkcellChargeCreditReductionIntegratedCommand
	(*AddAccountingBuyTurkcellChargeDocumentsIntegratedCommand)(nil),                  // 8: BuyTurkcellCharge.AddAccountingBuyTurkcellChargeDocumentsIntegratedCommand
	(*BuyTurkcellChargeByAfghanCellIntegratedCommand)(nil),                            // 9: BuyTurkcellCharge.BuyTurkcellChargeByAfghanCellIntegratedCommand
	(*CommitOrRollbackAddedBuyTurkcellChargeAccountingDocumentIntegratedCommand)(nil), // 10: BuyTurkcellCharge.CommitOrRollbackAddedBuyTurkcellChargeAccountingDocumentIntegratedCommand
	(*CommitOrRollbackBuyTurkcellChargeCreditReductionIntegratedCommand)(nil),         // 11: BuyTurkcellCharge.CommitOrRollbackBuyTurkcellChargeCreditReductionIntegratedCommand
	(*common.Failure)(nil),                    // 12: Common.Failure
	(*common.Money)(nil),                      // 13: Common.Money
	(*common.BuyChargeAccountingInfo)(nil),    // 14: Common.BuyChargeAccountingInfo
	(*common.CreditReductionMetaContext)(nil), // 15: Common.CreditReductionMetaContext
}
var file_BuyTurkcellCharge_proto_depIdxs = []int32{
	12, // 0: BuyTurkcellCharge.AddAccountingBuyTurkcellChargeDocumentsResponseIntegratedCommand.Failure:type_name -> Common.Failure
	12, // 1: BuyTurkcellCharge.TurkcellCheckCustomerActivationResponseIntegratedCommand.Failure:type_name -> Common.Failure
	12, // 2: BuyTurkcellCharge.BuyTurkcellChargeCreditReductionResponseIntegratedCommand.Failure:type_name -> Common.Failure
	12, // 3: BuyTurkcellCharge.BuyTurkcellChargeByAfghanCellResponseIntegratedCommand.Failure:type_name -> Common.Failure
	12, // 4: BuyTurkcellCharge.TurkcellCheckManagerChargeActivationResponseIntegratedCommand.Failure:type_name -> Common.Failure
	13, // 5: BuyTurkcellCharge.BuyTurkcellChargeCreditReductionIntegratedCommand.Commission:type_name -> Common.Money
	13, // 6: BuyTurkcellCharge.BuyTurkcellChargeCreditReductionIntegratedCommand.ExchangerDeductedMoney:type_name -> Common.Money
	14, // 7: BuyTurkcellCharge.AddAccountingBuyTurkcellChargeDocumentsIntegratedCommand.BuyChargeInfo:type_name -> Common.BuyChargeAccountingInfo
	15, // 8: BuyTurkcellCharge.CommitOrRollbackBuyTurkcellChargeCreditReductionIntegratedCommand.Context:type_name -> Common.CreditReductionMetaContext
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_BuyTurkcellCharge_proto_init() }
func file_BuyTurkcellCharge_proto_init() {
	if File_BuyTurkcellCharge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_BuyTurkcellCharge_proto_rawDesc), len(file_BuyTurkcellCharge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_BuyTurkcellCharge_proto_goTypes,
		DependencyIndexes: file_BuyTurkcellCharge_proto_depIdxs,
		MessageInfos:      file_BuyTurkcellCharge_proto_msgTypes,
	}.Build()
	File_BuyTurkcellCharge_proto = out.File
	file_BuyTurkcellCharge_proto_goTypes = nil
	file_BuyTurkcellCharge_proto_depIdxs = nil
}
