// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: RemoveMiscellaneousDraft.proto

package RemoveMiscellaneousDraft

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoveMiscellaneousDraftFilesIntegratedCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeletedFileIds []string               `protobuf:"bytes,1,rep,name=DeletedFileIds,proto3" json:"DeletedFileIds,omitempty"`
	ManagerId      string                 `protobuf:"bytes,2,opt,name=ManagerId,proto3" json:"ManagerId,omitempty"`
	CorrelationId  string                 `protobuf:"bytes,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id             string                 `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemoveMiscellaneousDraftFilesIntegratedCommand) Reset() {
	*x = RemoveMiscellaneousDraftFilesIntegratedCommand{}
	mi := &file_RemoveMiscellaneousDraft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMiscellaneousDraftFilesIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMiscellaneousDraftFilesIntegratedCommand) ProtoMessage() {}

func (x *RemoveMiscellaneousDraftFilesIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_RemoveMiscellaneousDraft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMiscellaneousDraftFilesIntegratedCommand.ProtoReflect.Descriptor instead.
func (*RemoveMiscellaneousDraftFilesIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_RemoveMiscellaneousDraft_proto_rawDescGZIP(), []int{0}
}

func (x *RemoveMiscellaneousDraftFilesIntegratedCommand) GetDeletedFileIds() []string {
	if x != nil {
		return x.DeletedFileIds
	}
	return nil
}

func (x *RemoveMiscellaneousDraftFilesIntegratedCommand) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *RemoveMiscellaneousDraftFilesIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RemoveMiscellaneousDraftFilesIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveMiscellaneousDraftFilesResponseIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMiscellaneousDraftFilesResponseIntegratedCommand) Reset() {
	*x = RemoveMiscellaneousDraftFilesResponseIntegratedCommand{}
	mi := &file_RemoveMiscellaneousDraft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMiscellaneousDraftFilesResponseIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMiscellaneousDraftFilesResponseIntegratedCommand) ProtoMessage() {}

func (x *RemoveMiscellaneousDraftFilesResponseIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_RemoveMiscellaneousDraft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMiscellaneousDraftFilesResponseIntegratedCommand.ProtoReflect.Descriptor instead.
func (*RemoveMiscellaneousDraftFilesResponseIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_RemoveMiscellaneousDraft_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveMiscellaneousDraftFilesResponseIntegratedCommand) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *RemoveMiscellaneousDraftFilesResponseIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RemoveMiscellaneousDraftFilesResponseIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RollbackRemovedMiscellaneousDraftFilesIntegratedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRemovedMiscellaneousDraftFilesIntegratedCommand) Reset() {
	*x = RollbackRemovedMiscellaneousDraftFilesIntegratedCommand{}
	mi := &file_RemoveMiscellaneousDraft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRemovedMiscellaneousDraftFilesIntegratedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRemovedMiscellaneousDraftFilesIntegratedCommand) ProtoMessage() {}

func (x *RollbackRemovedMiscellaneousDraftFilesIntegratedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_RemoveMiscellaneousDraft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRemovedMiscellaneousDraftFilesIntegratedCommand.ProtoReflect.Descriptor instead.
func (*RollbackRemovedMiscellaneousDraftFilesIntegratedCommand) Descriptor() ([]byte, []int) {
	return file_RemoveMiscellaneousDraft_proto_rawDescGZIP(), []int{2}
}

func (x *RollbackRemovedMiscellaneousDraftFilesIntegratedCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RollbackRemovedMiscellaneousDraftFilesIntegratedCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_RemoveMiscellaneousDraft_proto protoreflect.FileDescriptor

const file_RemoveMiscellaneousDraft_proto_rawDesc = "" +
	"\n" +
	"\x1eRemoveMiscellaneousDraft.proto\x12\x18RemoveMiscellaneousDraft\"\xac\x01\n" +
	".RemoveMiscellaneousDraftFilesIntegratedCommand\x12&\n" +
	"\x0eDeletedFileIds\x18\x01 \x03(\tR\x0eDeletedFileIds\x12\x1c\n" +
	"\tManagerId\x18\x02 \x01(\tR\tManagerId\x12$\n" +
	"\rCorrelationId\x18\x03 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\tR\x02Id\"\x86\x01\n" +
	"6RemoveMiscellaneousDraftFilesResponseIntegratedCommand\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\bR\x06Status\x12$\n" +
	"\rCorrelationId\x18\x02 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x03 \x01(\tR\x02Id\"o\n" +
	"7RollbackRemovedMiscellaneousDraftFilesIntegratedCommand\x12$\n" +
	"\rCorrelationId\x18\x01 \x01(\tR\rCorrelationId\x12\x0e\n" +
	"\x02Id\x18\x02 \x01(\tR\x02IdBrZ<moneyx.golang.framework/integration/RemoveMiscellaneousDraft\xaa\x021Ariyana.Framework.Schema.RemoveMiscellaneousDraftb\x06proto3"

var (
	file_RemoveMiscellaneousDraft_proto_rawDescOnce sync.Once
	file_RemoveMiscellaneousDraft_proto_rawDescData []byte
)

func file_RemoveMiscellaneousDraft_proto_rawDescGZIP() []byte {
	file_RemoveMiscellaneousDraft_proto_rawDescOnce.Do(func() {
		file_RemoveMiscellaneousDraft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_RemoveMiscellaneousDraft_proto_rawDesc), len(file_RemoveMiscellaneousDraft_proto_rawDesc)))
	})
	return file_RemoveMiscellaneousDraft_proto_rawDescData
}

var file_RemoveMiscellaneousDraft_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_RemoveMiscellaneousDraft_proto_goTypes = []any{
	(*RemoveMiscellaneousDraftFilesIntegratedCommand)(nil),          // 0: RemoveMiscellaneousDraft.RemoveMiscellaneousDraftFilesIntegratedCommand
	(*RemoveMiscellaneousDraftFilesResponseIntegratedCommand)(nil),  // 1: RemoveMiscellaneousDraft.RemoveMiscellaneousDraftFilesResponseIntegratedCommand
	(*RollbackRemovedMiscellaneousDraftFilesIntegratedCommand)(nil), // 2: RemoveMiscellaneousDraft.RollbackRemovedMiscellaneousDraftFilesIntegratedCommand
}
var file_RemoveMiscellaneousDraft_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_RemoveMiscellaneousDraft_proto_init() }
func file_RemoveMiscellaneousDraft_proto_init() {
	if File_RemoveMiscellaneousDraft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_RemoveMiscellaneousDraft_proto_rawDesc), len(file_RemoveMiscellaneousDraft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_RemoveMiscellaneousDraft_proto_goTypes,
		DependencyIndexes: file_RemoveMiscellaneousDraft_proto_depIdxs,
		MessageInfos:      file_RemoveMiscellaneousDraft_proto_msgTypes,
	}.Build()
	File_RemoveMiscellaneousDraft_proto = out.File
	file_RemoveMiscellaneousDraft_proto_goTypes = nil
	file_RemoveMiscellaneousDraft_proto_depIdxs = nil
}
